import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { buildAttributionCanon } from './attribution-canon-source.ts';

const OUT = fileURLToPath(new URL('../src/fixtures/attribution-canon.ts', import.meta.url));

const canon = await buildAttributionCanon();
const { report } = canon;

if (!report.modules.complete) {
  throw new Error('refusing to write a canon whose own module diff is incomplete');
}

const bundleRows = report.resources.changes.filter((row) => row.url.includes('vendor-dates'));
const thirdParty = report.origins.changes.filter((row) => row.party === 'third');

const file = `// generated by scripts/generate-attribution-canon.ts. do not edit by hand.
// run \`pnpm gen:attribution-canon\` to rebuild; attribution-canon.test.ts fails
// if this file and the generator ever disagree.
//
// every figure here was computed by @balise/attribution from two builds with
// real source maps. nothing in it is a number someone chose for the screen.

export const attributionCanon = {
  route: ${JSON.stringify(canon.route)},
  bundle: {
    before: ${JSON.stringify(canon.baselineBundleUrl)},
    after: ${JSON.stringify(canon.candidateBundleUrl)},
    rows: ${JSON.stringify(bundleRows, null, 4)},
  },
  modules: ${JSON.stringify(report.modules.modules.filter((row) => row.delta !== 0), null, 2)},
  packages: ${JSON.stringify(report.modules.packages, null, 2)},
  unattributed: ${JSON.stringify(report.modules.unattributed)},
  coverage: {
    comparable: ${String(report.modules.comparable)},
    complete: ${String(report.modules.complete)},
    resolvedBundles: ${report.modules.after.resolvedBundles},
  },
  reconciliation: ${JSON.stringify(report.reconciliation)},
  blame: ${JSON.stringify(canon.blame, null, 2)},
  // the grown repository files the candidate map placed at a line, which is
  // what the check may annotate. a dependency never appears here.
  placed: ${JSON.stringify(canon.placed, null, 2)},
  origins: ${JSON.stringify(thirdParty, null, 2)},
  // the embedded player ships no source map. the origin diff sizes it; this is
  // why nothing further is said about it.
  thirdPartyBundle: ${JSON.stringify(canon.thirdPartyBundle)},
} as const;
`;

writeFileSync(OUT, file);
console.log(`wrote ${OUT}`);
console.log(
  `bundle ${report.resources.changes.find((row) => row.url.includes('c40e'))?.transferredDelta ?? 0} B transferred`,
);
console.log(`measured ${report.reconciliation.measuredDelta} B decoded, explained ${report.reconciliation.explainedDelta} B`);
for (const row of report.modules.packages) {
  console.log(`  ${row.packageName.padEnd(24)} ${row.delta > 0 ? '+' : ''}${row.delta} B`);
}
