import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { buildMeasurementCanon } from './measurement-canon-source';

const OUT = fileURLToPath(new URL('../src/fixtures/measurement-canon.ts', import.meta.url));

const canon = buildMeasurementCanon();

for (const aggregation of canon.aggregations) {
  if (aggregation.metrics.length === 0) {
    throw new Error(`aggregation ${aggregation.id} produced no metrics`);
  }
}

const file = `// generated by scripts/generate-measurement-canon.ts. do not edit by hand.
// run \`pnpm gen:measurement-canon\` to rebuild; measurement-canon.test.ts
// fails if this file and the generator ever disagree.
//
// every median, dispersion, noise floor and confidence grade below was computed
// by @balise/measure-core from the runs recorded beside it. no statistic here
// was chosen: the mad is the mad of those run values, the floor is the scaled
// median of the historical mads, and the grade is what gradeConfidence
// returned for that dispersion at that sample count.

import type { EnvironmentFingerprint, RawCapture } from '@balise/schemas';
import type { CanonHistoryPoint, CanonMetric } from './measurement-types';

export const measurementCanon = {
  scalingFactor: ${canon.scalingFactor},
  minHistory: ${canon.minHistory},
  runOffsets: ${JSON.stringify(canon.runOffsets)},
  scenarios: ${JSON.stringify(canon.scenarios, null, 2)} as ReadonlyArray<{
    id: string;
    label: string;
    pass: 'cold' | 'warm';
    historyCount: number;
    /**
     * the environment this scenario was measured in, expanded from its named
     * profile by the kernel. two scenarios are comparable only where these
     * match (invariant 3), which is why it is published per scenario rather
     * than stated once for the service.
     */
    fingerprint: EnvironmentFingerprint;
    /** the aggregations this scenario publishes, all read against its one floor. */
    aggregationIds: readonly string[];
  }>,
  aggregations: ${JSON.stringify(canon.aggregations, null, 2)} as ReadonlyArray<{
    id: string;
    scenarioId: string;
    label: string;
    pass: 'cold' | 'warm';
    sampleCount: number;
    fingerprintStable: boolean;
    metrics: readonly CanonMetric[];
    /**
     * the median run's capture, where a surface renders its inventory. absent
     * on an aggregate over several pages, which has no single capture, and on
     * one nothing shows an inventory for.
     */
    capture?: RawCapture;
  }>,
} as const;

export type { CanonHistoryPoint, CanonMetric };
`;

writeFileSync(OUT, file);
console.log(`wrote ${OUT}`);
console.log(`scaling factor ${canon.scalingFactor}, minimum history ${canon.minHistory}`);
for (const aggregation of canon.aggregations) {
  const scenario = canon.scenarios.find((candidate) => candidate.id === aggregation.scenarioId)!;
  console.log(
    `  ${aggregation.id.padEnd(10)} (${scenario.id})  ${aggregation.sampleCount} runs, ${scenario.historyCount} prior aggregations`,
  );
  for (const metric of aggregation.metrics) {
    const floor =
      metric.floor.status === 'established'
        ? `floor ${metric.floor.value.toFixed(1)}`
        : `no floor (${metric.floor.sampleCount}/${metric.floor.requiredCount})`;
    console.log(
      `    ${metric.metricId.padEnd(22)} median ${metric.median.toFixed(1).padStart(11)}  mad ${metric.mad.toFixed(1).padStart(9)}  ${floor.padEnd(22)} ${metric.confidence}`,
    );
  }
  if (aggregation.capture !== undefined) {
    console.log(`    capture: ${aggregation.capture.resources.length} resources`);
  }
}
