import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { buildBudgetCanon } from './budget-canon-source.ts';

const OUT = fileURLToPath(new URL('../src/fixtures/budget-canon.ts', import.meta.url));

const canon = buildBudgetCanon();

if (canon.main.assessments.length === 0 || canon.pull.assessments.length === 0) {
  throw new Error('refusing to write a canon in which no budget was evaluated');
}

const file = `// generated by scripts/generate-budget-canon.ts. do not edit by hand.
// run \`pnpm gen:budget-canon\` to rebuild; budget-canon.test.ts fails if this
// file and the generator ever disagree.
//
// every verdict here was computed by @balise/budgets from the balise.yml below
// and from the same runs the attribution canon explains. nothing in it is a
// status someone chose for the screen.

import type { BudgetAssessment, BudgetConfig, BudgetOverride, CheckSummary } from '@balise/schemas';
import type { CheckProvenance, ScenarioMeasurement } from '@balise/budgets';

export interface BudgetCanon {
  file: string;
  branchName: string;
  service: string;
  /** the file as the customer wrote it, which is what the yaml view renders. */
  source: string;
  config: BudgetConfig;
  override: BudgetOverride;
  /** the branch view: the latest measurement of main, nothing to compare to. */
  main: { assessments: BudgetAssessment[]; summary: CheckSummary };
  /** the pull request: its scenarios against main. */
  pull: { assessments: BudgetAssessment[]; summary: CheckSummary };
  /**
   * the runs the pull request was evaluated on. the check comment is built
   * from these at render time rather than baked in here, so it renders in the
   * interface locale and carries the attribution sentence the screen shows.
   */
  pullScenarios: ScenarioMeasurement[];
  /** what the check reports itself as, for the provenance footer. */
  provenance: CheckProvenance;
}

export const budgetCanon: BudgetCanon = {
  file: 'balise.yml',
  branchName: 'main',
  service: ${JSON.stringify(canon.config.service)},
  source: ${JSON.stringify(canon.source)},
  config: ${JSON.stringify(canon.config, null, 2)},
  override: ${JSON.stringify(canon.override, null, 2)},
  main: {
    assessments: ${JSON.stringify(canon.main.assessments, null, 4)},
    summary: ${JSON.stringify(canon.main.summary, null, 4)},
  },
  pull: {
    assessments: ${JSON.stringify(canon.pull.assessments, null, 4)},
    summary: ${JSON.stringify(canon.pull.summary, null, 4)},
  },
  pullScenarios: ${JSON.stringify(canon.pullScenarios, null, 2)},
  provenance: ${JSON.stringify(canon.provenance, null, 2)},
};
`;

writeFileSync(OUT, file);
console.log(`wrote ${OUT}`);

for (const view of [
  { name: 'main', result: canon.main },
  { name: 'pull', result: canon.pull },
]) {
  const { counts, conclusion, blocking, overridden } = view.result.summary;
  console.log(
    `${view.name.padEnd(5)} ${conclusion.padEnd(8)} conforme ${counts.conforme}  warn ${counts.warn}  breach ${counts.breach}  non evalue ${counts.nonEvalue}  blocking ${blocking.length}  overridden ${overridden.length}`,
  );
}
