import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import type { AssessmentStatus, CriterionTier } from '@balise/schemas';
import { isAnswered } from '@balise/criteria-engine';
import { buildCriteriaCanon } from './criteria-canon-source.ts';

const OUT = fileURLToPath(new URL('../src/fixtures/criteria-canon.ts', import.meta.url));

const canon = buildCriteriaCanon();
const { pack, assessments, completion, blocking, versions } = canon;

if (assessments.length !== pack.criteria.length) {
  throw new Error('refusing to write a canon that does not answer every criterion in the pack');
}

const criteria = new Map(pack.criteria.map((criterion) => [criterion.id, criterion]));
const familyLabel = new Map(pack.families.map((family) => [family.id, family.labelFr]));

function count<T extends string>(values: readonly T[], keys: readonly T[]): Record<T, number> {
  const out = Object.fromEntries(keys.map((key) => [key, 0])) as Record<T, number>;
  for (const value of values) out[value] += 1;
  return out;
}

const STATUSES: readonly AssessmentStatus[] = [
  'conforme',
  'partiellement_conforme',
  'non_conforme',
  'non_applicable',
  'non_evalue',
];
const TIERS: readonly CriterionTier[] = ['automated', 'assisted', 'declarative'];

const byStatus = count(
  assessments.map((assessment) => assessment.status),
  STATUSES,
);
const bySource = count(
  assessments.map((assessment) => assessment.source),
  ['measured', 'attested', 'unevaluated'] as const,
);
const byTier = count(
  pack.criteria.map((criterion) => criterion.tier),
  TIERS,
);

// the rows the workspace table renders, in pack order.
const rows = assessments.map((assessment) => {
  const criterion = criteria.get(assessment.criterionId)!;
  return {
    id: assessment.criterionId,
    family: familyLabel.get(criterion.family) ?? criterion.family,
    familyId: criterion.family,
    statementFr: criterion.statementFr,
    tier: assessment.tier,
    priority: criterion.priority,
    status: assessment.status,
    source: assessment.source,
    evidenceFr: assessment.evidenceFr,
    justification: assessment.justification ?? null,
    attestedBy: assessment.attestedBy ?? null,
    attestedAt: assessment.attestedAt ?? null,
    answered: isAnswered(assessment),
  };
});

// per-family conformity, which is what the published declaration draws bars
// from. the denominator is applicable criteria, as the rate is everywhere.
const families = pack.families.map((family) => {
  const inFamily = assessments.filter(
    (assessment) => criteria.get(assessment.criterionId)!.family === family.id,
  );
  const applicable = inFamily.filter((assessment) => assessment.status !== 'non_applicable');
  const of = (status: AssessmentStatus) => inFamily.filter((a) => a.status === status).length;
  return {
    id: family.id,
    labelFr: family.labelFr,
    total: inFamily.length,
    applicable: applicable.length,
    conforme: of('conforme'),
    partiel: of('partiellement_conforme'),
    nonConforme: of('non_conforme'),
    nonApplicable: of('non_applicable'),
    nonEvalue: of('non_evalue'),
  };
});

const file = `// generated by scripts/generate-criteria-canon.ts. do not edit by hand.
// run \`pnpm gen:criteria-canon\` to rebuild; criteria-canon.test.ts fails if
// this file and the generator ever disagree.
//
// every status, count and blocking finding here was answered by
// @balise/criteria-engine over the rgesn-2024-v2 pack. nothing in it is a
// status someone chose for the screen.
//
// two facts the numbers below carry rather than hide: the pack ships
// tiersSignedOff: false, so \`bySource.measured\` is zero and every answer is
// one a named person put their name to; and \`withEvaluation\` counts the
// criteria carrying a rule this engine could run once the tiers are signed off.

import type { BlockingFinding, CriterionAssessment } from '@balise/schemas';

export const criteriaCanon = {
  pack: {
    id: ${JSON.stringify(pack.id)},
    version: ${JSON.stringify(pack.version)},
    label: ${JSON.stringify(`${pack.id}-${pack.version.replace('.', '-')}`)},
    source: ${JSON.stringify(pack.source)},
    tiersSignedOff: ${String(pack.tiersSignedOff)},
    criteriaCount: ${pack.criteria.length},
    familiesCount: ${pack.families.length},
    /** criteria carrying an evaluation rule, signed off or not. */
    withEvaluation: ${pack.criteria.filter((criterion) => criterion.evaluation !== undefined).length},
  },
  byStatus: ${JSON.stringify(byStatus, null, 2)},
  /** where each answer came from. measured is zero while the tiers are a proposal. */
  bySource: ${JSON.stringify(bySource, null, 2)},
  /** the tier each criterion is proposed at, which is not a count of answers. */
  byTier: ${JSON.stringify(byTier, null, 2)},
  completion: ${JSON.stringify(completion, null, 2)},
  /**
   * the three declaration versions, each answered again against the evidence
   * it could have held. a version's count is the engine's verdict on that
   * version, never the current count carried backwards.
   */
  versions: ${JSON.stringify(versions, null, 2)},
  families: ${JSON.stringify(families, null, 2)},
  rows: ${JSON.stringify(rows, null, 2)},
  blocking: ${JSON.stringify(blocking, null, 2)} as BlockingFinding[],
  publishable: ${String(canon.publishable)},
  assessments: ${JSON.stringify(assessments, null, 2)} as CriterionAssessment[],
} as const;

export type CriteriaRow = (typeof criteriaCanon.rows)[number];
`;

writeFileSync(OUT, file);
console.log(`wrote ${OUT}`);
console.log(
  `${pack.criteria.length} criteria · ${completion.conforme}/${completion.applicable} conforme (${Math.round((completion.conforme / completion.applicable) * 100)}%)`,
);
console.log(`  status  ${STATUSES.map((status) => `${status} ${byStatus[status]}`).join('  ')}`);
console.log(`  source  measured ${bySource.measured}  attested ${bySource.attested}  unevaluated ${bySource.unevaluated}`);
console.log(`  tier    ${TIERS.map((tier) => `${tier} ${byTier[tier]}`).join('  ')}`);
for (const version of versions) {
  console.log(`  ${version.tag.padEnd(4)} ${version.conforme} conforme, ${version.answered}/${version.total} answered`);
}
for (const tier of completion.byTier) {
  console.log(`  answered ${tier.tier.padEnd(12)} ${tier.answered}/${tier.total}`);
}
console.log(`  blocking ${blocking.length}, publishable ${String(canon.publishable)}`);
