import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { buildCarbonCanon } from './carbon-canon-source.ts';

const OUT = fileURLToPath(new URL('../src/fixtures/carbon-canon.ts', import.meta.url));

const canon = buildCarbonCanon();

if (canon.bandModelIds.length < 2) {
  throw new Error('refusing to write a canon whose band carries fewer than two models');
}

const file = `// generated by scripts/generate-carbon-canon.ts. do not edit by hand.
// run \\\`pnpm gen:carbon-canon\\\` to rebuild; carbon-canon.test.ts fails if this
// file and the generator ever disagree.
//
// every figure here was estimated by @balise/carbon-models from measurements
// the other canons publish. nothing in it is a number someone chose to look
// right, and nothing is averaged: the band is the energy models' own spread,
// and ecoindex sits beside it as the score and grade it publishes.
//
// METHODOLOGY.md 10.1 decides which models share the band. this file records
// which ones did.

import type { Assumption, GridIntensity } from '@balise/schemas';

export const carbonCanon = {
  grid: ${JSON.stringify(canon.grid)} as GridIntensity,
  greenHosting: ${canon.greenHosting},
  hostingCheckedAt: ${JSON.stringify(canon.hostingCheckedAt)},
  referenceModelId: ${JSON.stringify(canon.referenceModelId)},
  bandModelIds: ${JSON.stringify(canon.bandModelIds)},
  asideModelIds: ${JSON.stringify(canon.asideModelIds)},
  assumptions: ${JSON.stringify(canon.assumptions, null, 2)} as ReadonlyArray<{
    id: string;
    version: string;
    method: 'energy' | 'score-derived';
    assumptions: readonly Assumption[];
  }>,
  pages: ${JSON.stringify(canon.pages, null, 2)},
} as const;

export type CarbonPage = (typeof carbonCanon.pages)[number];
export type CarbonModelOutput = CarbonPage['inBand'][number];
`;

writeFileSync(OUT, file);
console.log(`wrote ${OUT}`);
console.log(`grid ${canon.grid.gCO2ePerKwh} gCO2e/kWh (${canon.grid.zone}, ${canon.grid.source}), green hosting ${canon.greenHosting}`);
console.log(`band  ${canon.bandModelIds.join(', ')}   aside  ${canon.asideModelIds.join(', ')}`);
for (const page of canon.pages) {
  const aside = page.aside
    .map((output) => `${output.id} ${output.grade ?? ''}${output.score === null ? '' : ` ${output.score.toFixed(0)}`}`)
    .join(' ');
  console.log(
    `  ${page.id.padEnd(10)} ${page.band.reference.toFixed(3)} gCO2e  band ${page.band.low.toFixed(3)} to ${page.band.high.toFixed(3)} (${page.band.modelCount} models)  aside ${aside}`,
  );
}
