import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { buildEngagementCanon } from './engagement-canon-source.ts';

const OUT = fileURLToPath(new URL('../src/fixtures/engagement-canon.ts', import.meta.url));

const canon = buildEngagementCanon();

// an engagement nobody signed cannot be reported as breached. this is the
// contradiction the slice exists to remove, so it is checked here as well as
// in the test.
for (const engagement of canon.engagements) {
  if (!engagement.inOffer && engagement.status !== null) {
    throw new Error(`${engagement.id} carries a contractual status and is not in the offer`);
  }
  if (engagement.measured.band !== null && engagement.measured.model === null) {
    throw new Error(`${engagement.id} states a band with no reference model (invariant 1)`);
  }
}

const file = `// generated by scripts/generate-engagement-canon.ts. do not edit by hand.
// run \`pnpm gen:engagement-canon\` to rebuild; engagement-canon.test.ts fails
// if this file and the generator ever disagree.
//
// the contractual engagements, once. the tender proposes them, the contract
// carries the ones that were signed, and the execution report reports on those.
// the only authored parts are the wording each carries into the annexe and the
// threshold the supplier signs; every margin, status, gauge and trend below is
// derived from what was measured.

import type { EngagementCanon } from '../../scripts/engagement-canon-source';

export const engagementCanon = ${JSON.stringify(canon, null, 2)} as unknown as EngagementCanon;
`;

writeFileSync(OUT, file);
console.log(`wrote ${OUT}`);
for (const engagement of canon.engagements) {
  const margin =
    engagement.margin.kind === 'headroom'
      ? `headroom ${engagement.margin.pct.toFixed(1)} %`
      : engagement.margin.kind === 'process'
        ? 'process'
        : `${engagement.margin.kind} ${engagement.margin.points.toFixed(1)}`;
  console.log(
    `  ${engagement.id.padEnd(20)} ${String(engagement.measured.value.toFixed(3)).padStart(11)}` +
      ` ${engagement.direction} ${String(engagement.threshold).padStart(9)}` +
      ` ${(engagement.status ?? 'not in offer').padEnd(13)} ${margin.padEnd(20)}` +
      ` gauge ${engagement.gaugePct === null ? '-' : engagement.gaugePct.toFixed(0)}` +
      ` history ${engagement.history === null ? '-' : engagement.history.length}` +
      ` trend ${engagement.trend?.classification ?? '-'}`,
  );
}
