import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { buildCorpusCanon } from './corpus-canon-source.ts';

const OUT = fileURLToPath(new URL('../src/fixtures/corpus-canon.ts', import.meta.url));

const canon = buildCorpusCanon();

// a rank is only a rank if the corpus it counts against is the corpus that was
// measured. anything else is the 412 this replaced.
if (canon.rows.length !== canon.size) {
  throw new Error('the corpus states a size it does not hold');
}
for (const row of canon.rows) {
  if (row.carbon.high < row.carbon.reference || row.carbon.low > row.carbon.reference) {
    throw new Error(`${row.domain}: the reference model falls outside its own band`);
  }
}

const file = `// generated by scripts/generate-corpus-canon.ts. do not edit by hand.
// run \`pnpm gen:corpus-canon\` to rebuild; corpus-canon.test.ts fails if this
// file and the generator ever disagree.
//
// the twelve services the fleet and the public index compare. every rank,
// every grade, every trend and every bucket below was computed from the
// captures in capture-canon-source.ts through @balise/measure-core and
// @balise/carbon-models. nothing here is a position typed beside a row.

import type { CorpusCanon } from '../../scripts/corpus-canon-source';

export const corpusCanon = ${JSON.stringify(canon, null, 2)} as unknown as CorpusCanon;
`;

writeFileSync(OUT, file);
console.log(`wrote ${OUT}`);
console.log(
  `${canon.size} services, ordered on ${canon.rankMetric}, band scale 0 to ${canon.scale.max.toFixed(3)} gCO2e`,
);
for (const row of canon.rows) {
  console.log(
    `  ${String(row.rank).padStart(2)} ${row.domain.padEnd(24)}` +
      ` ${String(Math.round(row.measured.transferredBytes / 1000)).padStart(5)} KB` +
      ` ${row.carbon.grade} ${row.carbon.score.toFixed(0).padStart(2)}` +
      ` ${row.carbon.reference.toFixed(3)} gCO2e` +
      ` ${row.confidence.padEnd(6)}` +
      ` ${row.trend.classification.padEnd(22)} ${row.trend.pct >= 0 ? '+' : ''}${row.trend.pct.toFixed(1)}%` +
      ` decl:${row.declaration.state.padEnd(7)} host:${row.hosting.state}`,
  );
}
console.log(
  `  benchmark: ${canon.benchmark.buckets.map((bucket) => bucket.count).join(' ')}` +
    ` (median ${Math.round(canon.benchmark.median / 1000)} KB)`,
);
