import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { buildCanonChain, CITED_REF_IDS } from './ledger-canon-source.ts';

const OUT = fileURLToPath(new URL('../src/fixtures/ledger-canon.ts', import.meta.url));

const chain = await buildCanonChain();
const cited = CITED_REF_IDS.map((refId) => {
  const entry = chain.entries.find((candidate) => candidate.refId === refId);
  if (entry === undefined) {
    throw new Error(`the chain has no entry for ${refId}`);
  }
  return entry;
});

if (chain.verification.status !== 'intact') {
  throw new Error('refusing to write a canon whose own chain does not verify');
}

const file = `// generated by scripts/generate-ledger-canon.ts. do not edit by hand.
// run \`pnpm gen:ledger-canon\` to rebuild; ledger-canon.test.ts fails if this
// file and the generator ever disagree.

import type { LedgerEntry } from '@balise/schemas';

export const ledgerCanon = {
  organizationId: ${JSON.stringify(chain.entries[0]!.organizationId)},
  entryCount: ${chain.entryCount},
  merkleRoot: ${JSON.stringify(chain.merkleRoot)},
  anchoredAt: ${JSON.stringify(chain.anchoredAt)},
  /** the runs the register retains, which is what "measured since" counts. */
  runs: ${JSON.stringify(chain.runs)},
  verification: ${JSON.stringify({ status: chain.verification.status, checkedCount: chain.verification.checkedCount })},
  // the entries the interface and the documents cite. the rest of the chain
  // is history: it exists, it is counted, and nothing displays it.
  //
  // the cast crosses a generated-data boundary: this file is written by the
  // generator, and ledger-canon.test.ts parses every entry through
  // LedgerEntry and recomputes both of its hashes. keeping it a plain literal
  // is what keeps zod out of the browser bundle.
  entries: ${JSON.stringify(cited, null, 2)} as unknown as readonly LedgerEntry[],
} as const;
`;

writeFileSync(OUT, file);
console.log(`wrote ${OUT}`);
console.log(`${chain.entryCount} entries, root ${chain.merkleRoot.slice(0, 16)}…`);
for (const entry of cited) {
  console.log(`  ${String(entry.sequence).padStart(5)} ${entry.kind.padEnd(20)} ${entry.entryHash.slice(0, 8)}`);
}
