import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { buildFindingsCanon } from './findings-canon-source.ts';

const OUT = fileURLToPath(new URL('../src/fixtures/findings-canon.ts', import.meta.url));

const canon = buildFindingsCanon();

for (const [id, page] of Object.entries(canon.pages)) {
  for (const finding of page.result.findings) {
    if (finding.share === null && finding.reference === null) {
      throw new Error(`finding ${finding.id} on ${id} states a quantity with nothing to read it against`);
    }
  }
}

const file = `// generated by scripts/generate-findings-canon.ts. do not edit by hand.
// run \`pnpm gen:findings-canon\` to rebuild; findings-canon.test.ts fails if
// this file and the generator ever disagree.
//
// every finding below was raised by @balise/measure-core from the capture the
// same run publishes. each one is a quantity that capture holds, or a position
// in the reference distribution ecoindex publishes. none of them is a saving:
// what a page would weigh in another format is a counterfactual about a page
// nobody measured, and this product does not state one.

import type { FindingsResult, ReferencePosition } from '@balise/measure-core';

export const findingsCanon = {
  thresholds: ${JSON.stringify(canon.thresholds, null, 2)},
  referenceSource: ${JSON.stringify(canon.referenceSource)},
  pages: ${JSON.stringify(canon.pages, null, 2)} as Record<
    string,
    { aggregationId: string; result: FindingsResult; reference: readonly ReferencePosition[] }
  >,
} as const;
`;

writeFileSync(OUT, file);
console.log(`wrote ${OUT}`);
for (const [id, page] of Object.entries(canon.pages)) {
  console.log(`  ${id}: ${page.result.findings.length} findings, ${page.result.withheld.length} withheld`);
  for (const finding of page.result.findings) {
    const against =
      finding.share !== null
        ? `${(finding.share.value * 100).toFixed(1)} % of ${finding.share.basis}`
        : `p${finding.reference!.percentile.toFixed(1)} of ${finding.reference!.source}`;
    console.log(`    ${finding.severity.padEnd(8)} ${finding.id.padEnd(26)} ${String(finding.value).padStart(9)} ${against}`);
  }
  for (const withheld of page.result.withheld) {
    console.log(`    withheld ${withheld.id} (${withheld.reason}, ${withheld.contributorCount})`);
  }
}
