// generated by scripts/generate-attribution-canon.ts. do not edit by hand.
// run `pnpm gen:attribution-canon` to rebuild; attribution-canon.test.ts fails
// if this file and the generator ever disagree.
//
// every figure here was computed by @balise/attribution from two builds with
// real source maps. nothing in it is a number someone chose for the screen.

export const attributionCanon = {
  route: "/demarches/acte-naissance",
  bundle: {
    before: "https://sevre-et-loire.fr/assets/vendor-dates.a91b.js",
    after: "https://sevre-et-loire.fr/assets/vendor-dates.c40e.js",
    rows: [
    {
        "url": "https://sevre-et-loire.fr/assets/vendor-dates.c40e.js",
        "party": "first",
        "status": "added",
        "beforeTransferredBytes": 0,
        "afterTransferredBytes": 157000,
        "transferredDelta": 157000,
        "beforeDecodedBytes": null,
        "afterDecodedBytes": 470000,
        "decodedDelta": null,
        "beforeRequests": 0,
        "afterRequests": 1
    },
    {
        "url": "https://sevre-et-loire.fr/assets/vendor-dates.a91b.js",
        "party": "first",
        "status": "removed",
        "beforeTransferredBytes": 96000,
        "afterTransferredBytes": 0,
        "transferredDelta": -96000,
        "beforeDecodedBytes": 286000,
        "afterDecodedBytes": null,
        "decodedDelta": null,
        "beforeRequests": 1,
        "afterRequests": 0
    }
],
  },
  modules: [
  {
    "path": "node_modules/date-fns/locale/fr/index.js",
    "packageName": "date-fns",
    "beforeBytes": 0,
    "afterBytes": 62000,
    "delta": 62000,
    "status": "added",
    "span": {
      "firstLine": 1,
      "lastLine": 340
    }
  },
  {
    "path": "node_modules/date-fns/locale/br/index.js",
    "packageName": "date-fns",
    "beforeBytes": 0,
    "afterBytes": 58000,
    "delta": 58000,
    "status": "added",
    "span": {
      "firstLine": 1,
      "lastLine": 320
    }
  },
  {
    "path": "node_modules/date-fns/locale/index.js",
    "packageName": "date-fns",
    "beforeBytes": 0,
    "afterBytes": 40000,
    "delta": 40000,
    "status": "added",
    "span": {
      "firstLine": 1,
      "lastLine": 210
    }
  },
  {
    "path": "src/lib/dates.ts",
    "packageName": null,
    "beforeBytes": 4120,
    "afterBytes": 4240,
    "delta": 120,
    "status": "grown",
    "span": {
      "firstLine": 1,
      "lastLine": 104
    }
  }
],
  packages: [
  {
    "packageName": "date-fns",
    "beforeBytes": 242000,
    "afterBytes": 402000,
    "delta": 160000,
    "status": "grown",
    "moduleCount": 6
  }
],
  unattributed: {"before":18000,"after":41880,"delta":23880},
  coverage: {
    comparable: true,
    complete: true,
    resolvedBundles: 1,
  },
  reconciliation: {"measuredDelta":184000,"explainedDelta":160120,"unexplainedDelta":23880,"complete":true},
  blame: [
  {
    "status": "unavailable",
    "path": "node_modules/date-fns/locale/fr/index.js",
    "packageName": "date-fns",
    "reason": "third-party-module"
  },
  {
    "status": "unavailable",
    "path": "node_modules/date-fns/locale/br/index.js",
    "packageName": "date-fns",
    "reason": "third-party-module"
  },
  {
    "status": "unavailable",
    "path": "node_modules/date-fns/locale/index.js",
    "packageName": "date-fns",
    "reason": "third-party-module"
  },
  {
    "status": "attributed",
    "path": "src/lib/dates.ts",
    "packageName": null,
    "commits": [
      {
        "sha": "a7f2c91d4e8b3a06f5c29b7e14d0a83bc6f2e915",
        "shortSha": "a7f2c91",
        "author": "c. bellanger",
        "authoredAt": "2026-08-12T11:24:00+02:00",
        "subject": "feat(dates): formats d'acte localisés (#412)"
      }
    ]
  }
],
  // the grown repository files the candidate map placed at a line, which is
  // what the check may annotate. a dependency never appears here.
  placed: [
  {
    "path": "src/lib/dates.ts",
    "startLine": 1,
    "endLine": 104,
    "deltaBytes": 120,
    "afterBytes": 4240
  }
],
  origins: [
  {
    "origin": "https://player.dailymotion.com",
    "party": "third",
    "status": "added",
    "vendor": {
      "id": "dailymotion",
      "label": "Dailymotion",
      "category": "media"
    },
    "beforeTransferredBytes": 0,
    "afterTransferredBytes": 198000,
    "transferredDelta": 198000,
    "beforeRequests": 0,
    "afterRequests": 2
  },
  {
    "origin": "https://geo.api.gouv.fr",
    "party": "third",
    "status": "unchanged",
    "vendor": {
      "id": "api-gouv",
      "label": "api.gouv.fr",
      "category": "public-api"
    },
    "beforeTransferredBytes": 12000,
    "afterTransferredBytes": 12000,
    "transferredDelta": 0,
    "beforeRequests": 1,
    "afterRequests": 1
  },
  {
    "origin": "https://matomo.selo.fr",
    "party": "third",
    "status": "unchanged",
    "vendor": null,
    "beforeTransferredBytes": 72000,
    "afterTransferredBytes": 72000,
    "transferredDelta": 0,
    "beforeRequests": 1,
    "afterRequests": 1
  },
  {
    "origin": "https://tarteaucitron.io",
    "party": "third",
    "status": "unchanged",
    "vendor": {
      "id": "tarteaucitron",
      "label": "Tarteaucitron",
      "category": "consent"
    },
    "beforeTransferredBytes": 96000,
    "afterTransferredBytes": 96000,
    "transferredDelta": 0,
    "beforeRequests": 1,
    "afterRequests": 1
  }
],
  // the embedded player ships no source map. the origin diff sizes it; this is
  // why nothing further is said about it.
  thirdPartyBundle: {"status":"unavailable","url":"https://player.dailymotion.com/embed.js","reason":"no-source-map"},
} as const;
