// generated by scripts/generate-budget-canon.ts. do not edit by hand.
// run `pnpm gen:budget-canon` to rebuild; budget-canon.test.ts fails if this
// file and the generator ever disagree.
//
// every verdict here was computed by @balise/budgets from the balise.yml below
// and from the same runs the attribution canon explains. nothing in it is a
// status someone chose for the screen.

import type { BudgetAssessment, BudgetConfig, BudgetOverride, CheckSummary } from '@balise/schemas';
import type { CheckProvenance, ScenarioMeasurement } from '@balise/budgets';

export interface BudgetCanon {
  file: string;
  branchName: string;
  service: string;
  /** the file as the customer wrote it, which is what the yaml view renders. */
  source: string;
  config: BudgetConfig;
  override: BudgetOverride;
  /** the branch view: the latest measurement of main, nothing to compare to. */
  main: { assessments: BudgetAssessment[]; summary: CheckSummary };
  /** the pull request: its scenarios against main. */
  pull: { assessments: BudgetAssessment[]; summary: CheckSummary };
  /**
   * the runs the pull request was evaluated on. the check comment is built
   * from these at render time rather than baked in here, so it renders in the
   * interface locale and carries the attribution sentence the screen shows.
   */
  pullScenarios: ScenarioMeasurement[];
  /** what the check reports itself as, for the provenance footer. */
  provenance: CheckProvenance;
}

export const budgetCanon: BudgetCanon = {
  file: 'balise.yml',
  branchName: 'main',
  service: "portail-metropolitain",
  source: "# balise.yml · sevre-et-loire.fr · pack rgesn-2024-v2\nversion: 1\nservice: portail-metropolitain\nruns: 5\nprofiles: [desktop-fibre, mobile-4g]\nreference_model: swd@4.0\n# deltas below the computed noise floor are never failures\nnoise_floor: auto\n\nbudgets:\n  - scope: /accueil\n    bytes: { warn: 860KB, fail: 900KB }\n  - scope: /demarches/*\n    bytes: { warn: 1250KB, fail: 1300KB }\n    requests: { fail: 90 }\n  - scope: /actualites\n    bytes: { warn: 860KB, fail: 900KB }\n  - scope: journey:demande-acte\n    bytes: { fail: 1400KB }\n  - scope: service\n    third_party_share: { fail: 30% }\n    relative_to_baseline: { warn: +3% }\n\ncheck:\n  block_merge_on: fail\n  annotate_files: true\n",
  config: {
  "version": 1,
  "service": "portail-metropolitain",
  "runs": 5,
  "profiles": [
    "desktop-fibre",
    "mobile-4g"
  ],
  "referenceModel": "swd@4.0",
  "noiseFloor": "auto",
  "rules": [
    {
      "kind": "absolute",
      "scope": {
        "kind": "route",
        "pattern": "/accueil"
      },
      "metricId": "transferred_bytes",
      "unit": "bytes",
      "warn": {
        "value": 860000,
        "sourceText": "860KB",
        "line": 12
      },
      "fail": {
        "value": 900000,
        "sourceText": "900KB",
        "line": 12
      },
      "line": 12
    },
    {
      "kind": "absolute",
      "scope": {
        "kind": "route",
        "pattern": "/demarches/*"
      },
      "metricId": "transferred_bytes",
      "unit": "bytes",
      "warn": {
        "value": 1250000,
        "sourceText": "1250KB",
        "line": 14
      },
      "fail": {
        "value": 1300000,
        "sourceText": "1300KB",
        "line": 14
      },
      "line": 14
    },
    {
      "kind": "absolute",
      "scope": {
        "kind": "route",
        "pattern": "/demarches/*"
      },
      "metricId": "request_count",
      "unit": "count",
      "warn": null,
      "fail": {
        "value": 90,
        "sourceText": "90",
        "line": 15
      },
      "line": 15
    },
    {
      "kind": "absolute",
      "scope": {
        "kind": "route",
        "pattern": "/actualites"
      },
      "metricId": "transferred_bytes",
      "unit": "bytes",
      "warn": {
        "value": 860000,
        "sourceText": "860KB",
        "line": 17
      },
      "fail": {
        "value": 900000,
        "sourceText": "900KB",
        "line": 17
      },
      "line": 17
    },
    {
      "kind": "absolute",
      "scope": {
        "kind": "journey",
        "journey": "demande-acte"
      },
      "metricId": "transferred_bytes",
      "unit": "bytes",
      "warn": null,
      "fail": {
        "value": 1400000,
        "sourceText": "1400KB",
        "line": 19
      },
      "line": 19
    },
    {
      "kind": "absolute",
      "scope": {
        "kind": "service"
      },
      "metricId": "third_party_share_pct",
      "unit": "pct",
      "warn": null,
      "fail": {
        "value": 30,
        "sourceText": "30%",
        "line": 21
      },
      "line": 21
    },
    {
      "kind": "relative",
      "scope": {
        "kind": "service"
      },
      "metricId": "transferred_bytes",
      "unit": "pct",
      "warn": {
        "value": 3,
        "sourceText": "+3%",
        "line": 22
      },
      "fail": null,
      "line": 22
    }
  ],
  "check": {
    "blockMergeOn": "fail",
    "annotateFiles": true
  }
},
  override: {
  "scope": {
    "kind": "route",
    "pattern": "/actualites"
  },
  "metricId": "transferred_bytes",
  "reason": "Mandated by comms for the 14 July campaign, removal scheduled 01 Sep.",
  "by": "m. carbonne",
  "recordedAt": "2026-07-08T11:05:00.000Z",
  "expiresAt": "2026-09-01T00:00:00.000Z",
  "requestedIn": "PR #401",
  "ledgerRef": "102ae192"
},
  main: {
    assessments: [
    {
        "scenarioId": "/accueil",
        "scenarioLabel": "/accueil",
        "pass": "cold",
        "rule": {
            "kind": "absolute",
            "scope": {
                "kind": "route",
                "pattern": "/accueil"
            },
            "metricId": "transferred_bytes",
            "unit": "bytes",
            "warn": {
                "value": 860000,
                "sourceText": "860KB",
                "line": 12
            },
            "fail": {
                "value": 900000,
                "sourceText": "900KB",
                "line": 12
            },
            "line": 12
        },
        "metricId": "transferred_bytes",
        "unit": "bytes",
        "floor": {
            "status": "established",
            "metricId": "transferred_bytes",
            "unit": "bytes",
            "value": 7380,
            "sampleCount": 24,
            "scalingFactor": 1.2
        },
        "override": null,
        "status": "conforme",
        "observed": 840000,
        "headroom": 60000,
        "withinNoise": false,
        "delta": null
    },
    {
        "scenarioId": "/demarches/acte-naissance",
        "scenarioLabel": "/demarches/acte-naissance",
        "pass": "cold",
        "rule": {
            "kind": "absolute",
            "scope": {
                "kind": "route",
                "pattern": "/demarches/*"
            },
            "metricId": "transferred_bytes",
            "unit": "bytes",
            "warn": {
                "value": 1250000,
                "sourceText": "1250KB",
                "line": 14
            },
            "fail": {
                "value": 1300000,
                "sourceText": "1300KB",
                "line": 14
            },
            "line": 14
        },
        "metricId": "transferred_bytes",
        "unit": "bytes",
        "floor": {
            "status": "established",
            "metricId": "transferred_bytes",
            "unit": "bytes",
            "value": 7380,
            "sampleCount": 24,
            "scalingFactor": 1.2
        },
        "override": null,
        "status": "conforme",
        "observed": 1114000,
        "headroom": 186000,
        "withinNoise": false,
        "delta": null
    },
    {
        "scenarioId": "/demarches/acte-naissance",
        "scenarioLabel": "/demarches/acte-naissance",
        "pass": "cold",
        "rule": {
            "kind": "absolute",
            "scope": {
                "kind": "route",
                "pattern": "/demarches/*"
            },
            "metricId": "request_count",
            "unit": "count",
            "warn": null,
            "fail": {
                "value": 90,
                "sourceText": "90",
                "line": 15
            },
            "line": 15
        },
        "metricId": "request_count",
        "unit": "count",
        "floor": {
            "status": "established",
            "metricId": "request_count",
            "unit": "count",
            "value": 1.2,
            "sampleCount": 24,
            "scalingFactor": 1.2
        },
        "override": null,
        "status": "conforme",
        "observed": 82,
        "headroom": 8,
        "withinNoise": false,
        "delta": null
    },
    {
        "scenarioId": "/actualites",
        "scenarioLabel": "/actualites",
        "pass": "cold",
        "rule": {
            "kind": "absolute",
            "scope": {
                "kind": "route",
                "pattern": "/actualites"
            },
            "metricId": "transferred_bytes",
            "unit": "bytes",
            "warn": {
                "value": 860000,
                "sourceText": "860KB",
                "line": 17
            },
            "fail": {
                "value": 900000,
                "sourceText": "900KB",
                "line": 17
            },
            "line": 17
        },
        "metricId": "transferred_bytes",
        "unit": "bytes",
        "floor": {
            "status": "established",
            "metricId": "transferred_bytes",
            "unit": "bytes",
            "value": 7380,
            "sampleCount": 24,
            "scalingFactor": 1.2
        },
        "override": {
            "scope": {
                "kind": "route",
                "pattern": "/actualites"
            },
            "metricId": "transferred_bytes",
            "reason": "Mandated by comms for the 14 July campaign, removal scheduled 01 Sep.",
            "by": "m. carbonne",
            "recordedAt": "2026-07-08T11:05:00.000Z",
            "expiresAt": "2026-09-01T00:00:00.000Z",
            "requestedIn": "PR #401",
            "ledgerRef": "102ae192"
        },
        "status": "breach",
        "observed": 1240000,
        "headroom": -340000,
        "withinNoise": false,
        "delta": null
    },
    {
        "scenarioId": "demande-acte",
        "scenarioLabel": "journey: demande d'acte",
        "pass": "cold",
        "rule": {
            "kind": "absolute",
            "scope": {
                "kind": "journey",
                "journey": "demande-acte"
            },
            "metricId": "transferred_bytes",
            "unit": "bytes",
            "warn": null,
            "fail": {
                "value": 1400000,
                "sourceText": "1400KB",
                "line": 19
            },
            "line": 19
        },
        "metricId": "transferred_bytes",
        "unit": "bytes",
        "floor": {
            "status": "established",
            "metricId": "transferred_bytes",
            "unit": "bytes",
            "value": 7380,
            "sampleCount": 24,
            "scalingFactor": 1.2
        },
        "override": null,
        "status": "conforme",
        "observed": 1258000,
        "headroom": 142000,
        "withinNoise": false,
        "delta": null
    },
    {
        "scenarioId": "/accueil",
        "scenarioLabel": "/accueil",
        "pass": "cold",
        "rule": {
            "kind": "absolute",
            "scope": {
                "kind": "service"
            },
            "metricId": "third_party_share_pct",
            "unit": "pct",
            "warn": null,
            "fail": {
                "value": 30,
                "sourceText": "30%",
                "line": 21
            },
            "line": 21
        },
        "metricId": "third_party_share_pct",
        "unit": "pct",
        "floor": {
            "status": "established",
            "metricId": "third_party_share_pct",
            "unit": "pct",
            "value": 0.6434327575943157,
            "sampleCount": 24,
            "scalingFactor": 1.2
        },
        "override": null,
        "status": "conforme",
        "observed": 22,
        "headroom": 8,
        "withinNoise": false,
        "delta": null
    },
    {
        "scenarioId": "/demarches/acte-naissance",
        "scenarioLabel": "/demarches/acte-naissance",
        "pass": "cold",
        "rule": {
            "kind": "absolute",
            "scope": {
                "kind": "service"
            },
            "metricId": "third_party_share_pct",
            "unit": "pct",
            "warn": null,
            "fail": {
                "value": 30,
                "sourceText": "30%",
                "line": 21
            },
            "line": 21
        },
        "metricId": "third_party_share_pct",
        "unit": "pct",
        "floor": {
            "status": "established",
            "metricId": "third_party_share_pct",
            "unit": "pct",
            "value": 0.6434327575943157,
            "sampleCount": 24,
            "scalingFactor": 1.2
        },
        "override": null,
        "status": "conforme",
        "observed": 16.15798922800718,
        "headroom": 13.842010771992818,
        "withinNoise": false,
        "delta": null
    },
    {
        "scenarioId": "/actualites",
        "scenarioLabel": "/actualites",
        "pass": "cold",
        "rule": {
            "kind": "absolute",
            "scope": {
                "kind": "service"
            },
            "metricId": "third_party_share_pct",
            "unit": "pct",
            "warn": null,
            "fail": {
                "value": 30,
                "sourceText": "30%",
                "line": 21
            },
            "line": 21
        },
        "metricId": "third_party_share_pct",
        "unit": "pct",
        "floor": {
            "status": "established",
            "metricId": "third_party_share_pct",
            "unit": "pct",
            "value": 0.6434327575943157,
            "sampleCount": 24,
            "scalingFactor": 1.2
        },
        "override": null,
        "status": "breach",
        "observed": 38.70967741935484,
        "headroom": -8.70967741935484,
        "withinNoise": false,
        "delta": null
    },
    {
        "scenarioId": "demande-acte",
        "scenarioLabel": "journey: demande d'acte",
        "pass": "cold",
        "rule": {
            "kind": "absolute",
            "scope": {
                "kind": "service"
            },
            "metricId": "third_party_share_pct",
            "unit": "pct",
            "warn": null,
            "fail": {
                "value": 30,
                "sourceText": "30%",
                "line": 21
            },
            "line": 21
        },
        "metricId": "third_party_share_pct",
        "unit": "pct",
        "floor": {
            "status": "established",
            "metricId": "third_party_share_pct",
            "unit": "pct",
            "value": 0.6434327575943157,
            "sampleCount": 24,
            "scalingFactor": 1.2
        },
        "override": null,
        "status": "conforme",
        "observed": 17.965023847376788,
        "headroom": 12.034976152623212,
        "withinNoise": false,
        "delta": null
    },
    {
        "scenarioId": "/accueil",
        "scenarioLabel": "/accueil",
        "pass": "cold",
        "rule": {
            "kind": "relative",
            "scope": {
                "kind": "service"
            },
            "metricId": "transferred_bytes",
            "unit": "pct",
            "warn": {
                "value": 3,
                "sourceText": "+3%",
                "line": 22
            },
            "fail": null,
            "line": 22
        },
        "metricId": "transferred_bytes",
        "unit": "pct",
        "floor": {
            "status": "established",
            "metricId": "transferred_bytes",
            "unit": "bytes",
            "value": 7380,
            "sampleCount": 24,
            "scalingFactor": 1.2
        },
        "override": null,
        "status": "non_evalue",
        "reason": "no-baseline",
        "observed": null,
        "headroom": null,
        "withinNoise": false,
        "delta": null
    },
    {
        "scenarioId": "/demarches/acte-naissance",
        "scenarioLabel": "/demarches/acte-naissance",
        "pass": "cold",
        "rule": {
            "kind": "relative",
            "scope": {
                "kind": "service"
            },
            "metricId": "transferred_bytes",
            "unit": "pct",
            "warn": {
                "value": 3,
                "sourceText": "+3%",
                "line": 22
            },
            "fail": null,
            "line": 22
        },
        "metricId": "transferred_bytes",
        "unit": "pct",
        "floor": {
            "status": "established",
            "metricId": "transferred_bytes",
            "unit": "bytes",
            "value": 7380,
            "sampleCount": 24,
            "scalingFactor": 1.2
        },
        "override": null,
        "status": "non_evalue",
        "reason": "no-baseline",
        "observed": null,
        "headroom": null,
        "withinNoise": false,
        "delta": null
    },
    {
        "scenarioId": "/actualites",
        "scenarioLabel": "/actualites",
        "pass": "cold",
        "rule": {
            "kind": "relative",
            "scope": {
                "kind": "service"
            },
            "metricId": "transferred_bytes",
            "unit": "pct",
            "warn": {
                "value": 3,
                "sourceText": "+3%",
                "line": 22
            },
            "fail": null,
            "line": 22
        },
        "metricId": "transferred_bytes",
        "unit": "pct",
        "floor": {
            "status": "established",
            "metricId": "transferred_bytes",
            "unit": "bytes",
            "value": 7380,
            "sampleCount": 24,
            "scalingFactor": 1.2
        },
        "override": null,
        "status": "non_evalue",
        "reason": "no-baseline",
        "observed": null,
        "headroom": null,
        "withinNoise": false,
        "delta": null
    },
    {
        "scenarioId": "demande-acte",
        "scenarioLabel": "journey: demande d'acte",
        "pass": "cold",
        "rule": {
            "kind": "relative",
            "scope": {
                "kind": "service"
            },
            "metricId": "transferred_bytes",
            "unit": "pct",
            "warn": {
                "value": 3,
                "sourceText": "+3%",
                "line": 22
            },
            "fail": null,
            "line": 22
        },
        "metricId": "transferred_bytes",
        "unit": "pct",
        "floor": {
            "status": "established",
            "metricId": "transferred_bytes",
            "unit": "bytes",
            "value": 7380,
            "sampleCount": 24,
            "scalingFactor": 1.2
        },
        "override": null,
        "status": "non_evalue",
        "reason": "no-baseline",
        "observed": null,
        "headroom": null,
        "withinNoise": false,
        "delta": null
    }
],
    summary: {
    "conclusion": "failure",
    "counts": {
        "conforme": 7,
        "warn": 0,
        "breach": 2,
        "nonEvalue": 4
    },
    "blocking": [
        {
            "scenarioId": "/actualites",
            "scenarioLabel": "/actualites",
            "pass": "cold",
            "rule": {
                "kind": "absolute",
                "scope": {
                    "kind": "service"
                },
                "metricId": "third_party_share_pct",
                "unit": "pct",
                "warn": null,
                "fail": {
                    "value": 30,
                    "sourceText": "30%",
                    "line": 21
                },
                "line": 21
            },
            "metricId": "third_party_share_pct",
            "unit": "pct",
            "floor": {
                "status": "established",
                "metricId": "third_party_share_pct",
                "unit": "pct",
                "value": 0.6434327575943157,
                "sampleCount": 24,
                "scalingFactor": 1.2
            },
            "override": null,
            "status": "breach",
            "observed": 38.70967741935484,
            "headroom": -8.70967741935484,
            "withinNoise": false,
            "delta": null
        }
    ],
    "overridden": [
        {
            "scenarioId": "/actualites",
            "scenarioLabel": "/actualites",
            "pass": "cold",
            "rule": {
                "kind": "absolute",
                "scope": {
                    "kind": "route",
                    "pattern": "/actualites"
                },
                "metricId": "transferred_bytes",
                "unit": "bytes",
                "warn": {
                    "value": 860000,
                    "sourceText": "860KB",
                    "line": 17
                },
                "fail": {
                    "value": 900000,
                    "sourceText": "900KB",
                    "line": 17
                },
                "line": 17
            },
            "metricId": "transferred_bytes",
            "unit": "bytes",
            "floor": {
                "status": "established",
                "metricId": "transferred_bytes",
                "unit": "bytes",
                "value": 7380,
                "sampleCount": 24,
                "scalingFactor": 1.2
            },
            "override": {
                "scope": {
                    "kind": "route",
                    "pattern": "/actualites"
                },
                "metricId": "transferred_bytes",
                "reason": "Mandated by comms for the 14 July campaign, removal scheduled 01 Sep.",
                "by": "m. carbonne",
                "recordedAt": "2026-07-08T11:05:00.000Z",
                "expiresAt": "2026-09-01T00:00:00.000Z",
                "requestedIn": "PR #401",
                "ledgerRef": "102ae192"
            },
            "status": "breach",
            "observed": 1240000,
            "headroom": -340000,
            "withinNoise": false,
            "delta": null
        }
    ]
},
  },
  pull: {
    assessments: [
    {
        "scenarioId": "/accueil",
        "scenarioLabel": "/accueil",
        "pass": "cold",
        "rule": {
            "kind": "absolute",
            "scope": {
                "kind": "route",
                "pattern": "/accueil"
            },
            "metricId": "transferred_bytes",
            "unit": "bytes",
            "warn": {
                "value": 860000,
                "sourceText": "860KB",
                "line": 12
            },
            "fail": {
                "value": 900000,
                "sourceText": "900KB",
                "line": 12
            },
            "line": 12
        },
        "metricId": "transferred_bytes",
        "unit": "bytes",
        "floor": {
            "status": "established",
            "metricId": "transferred_bytes",
            "unit": "bytes",
            "value": 7380,
            "sampleCount": 24,
            "scalingFactor": 1.2
        },
        "override": null,
        "status": "conforme",
        "observed": 842000,
        "headroom": 58000,
        "withinNoise": false,
        "delta": null
    },
    {
        "scenarioId": "/demarches/acte-naissance",
        "scenarioLabel": "/demarches/acte-naissance",
        "pass": "cold",
        "rule": {
            "kind": "absolute",
            "scope": {
                "kind": "route",
                "pattern": "/demarches/*"
            },
            "metricId": "transferred_bytes",
            "unit": "bytes",
            "warn": {
                "value": 1250000,
                "sourceText": "1250KB",
                "line": 14
            },
            "fail": {
                "value": 1300000,
                "sourceText": "1300KB",
                "line": 14
            },
            "line": 14
        },
        "metricId": "transferred_bytes",
        "unit": "bytes",
        "floor": {
            "status": "established",
            "metricId": "transferred_bytes",
            "unit": "bytes",
            "value": 7380,
            "sampleCount": 24,
            "scalingFactor": 1.2
        },
        "override": null,
        "status": "warn",
        "observed": 1298000,
        "headroom": 2000,
        "withinNoise": true,
        "delta": null
    },
    {
        "scenarioId": "/demarches/acte-naissance",
        "scenarioLabel": "/demarches/acte-naissance",
        "pass": "cold",
        "rule": {
            "kind": "absolute",
            "scope": {
                "kind": "route",
                "pattern": "/demarches/*"
            },
            "metricId": "request_count",
            "unit": "count",
            "warn": null,
            "fail": {
                "value": 90,
                "sourceText": "90",
                "line": 15
            },
            "line": 15
        },
        "metricId": "request_count",
        "unit": "count",
        "floor": {
            "status": "established",
            "metricId": "request_count",
            "unit": "count",
            "value": 1.2,
            "sampleCount": 24,
            "scalingFactor": 1.2
        },
        "override": null,
        "status": "conforme",
        "observed": 84,
        "headroom": 6,
        "withinNoise": false,
        "delta": null
    },
    {
        "scenarioId": "demande-acte",
        "scenarioLabel": "journey: demande d'acte",
        "pass": "cold",
        "rule": {
            "kind": "absolute",
            "scope": {
                "kind": "journey",
                "journey": "demande-acte"
            },
            "metricId": "transferred_bytes",
            "unit": "bytes",
            "warn": null,
            "fail": {
                "value": 1400000,
                "sourceText": "1400KB",
                "line": 19
            },
            "line": 19
        },
        "metricId": "transferred_bytes",
        "unit": "bytes",
        "floor": {
            "status": "established",
            "metricId": "transferred_bytes",
            "unit": "bytes",
            "value": 7380,
            "sampleCount": 24,
            "scalingFactor": 1.2
        },
        "override": null,
        "status": "breach",
        "observed": 1442000,
        "headroom": -42000,
        "withinNoise": false,
        "delta": null
    },
    {
        "scenarioId": "/accueil",
        "scenarioLabel": "/accueil",
        "pass": "cold",
        "rule": {
            "kind": "absolute",
            "scope": {
                "kind": "service"
            },
            "metricId": "third_party_share_pct",
            "unit": "pct",
            "warn": null,
            "fail": {
                "value": 30,
                "sourceText": "30%",
                "line": 21
            },
            "line": 21
        },
        "metricId": "third_party_share_pct",
        "unit": "pct",
        "floor": {
            "status": "established",
            "metricId": "third_party_share_pct",
            "unit": "pct",
            "value": 0.6434327575943157,
            "sampleCount": 24,
            "scalingFactor": 1.2
        },
        "override": null,
        "status": "conforme",
        "observed": 22,
        "headroom": 8,
        "withinNoise": false,
        "delta": null
    },
    {
        "scenarioId": "/demarches/acte-naissance",
        "scenarioLabel": "/demarches/acte-naissance",
        "pass": "cold",
        "rule": {
            "kind": "absolute",
            "scope": {
                "kind": "service"
            },
            "metricId": "third_party_share_pct",
            "unit": "pct",
            "warn": null,
            "fail": {
                "value": 30,
                "sourceText": "30%",
                "line": 21
            },
            "line": 21
        },
        "metricId": "third_party_share_pct",
        "unit": "pct",
        "floor": {
            "status": "established",
            "metricId": "third_party_share_pct",
            "unit": "pct",
            "value": 0.6434327575943157,
            "sampleCount": 24,
            "scalingFactor": 1.2
        },
        "override": null,
        "status": "conforme",
        "observed": 29.121725731895225,
        "headroom": 0.878274268104775,
        "withinNoise": false,
        "delta": null
    },
    {
        "scenarioId": "demande-acte",
        "scenarioLabel": "journey: demande d'acte",
        "pass": "cold",
        "rule": {
            "kind": "absolute",
            "scope": {
                "kind": "service"
            },
            "metricId": "third_party_share_pct",
            "unit": "pct",
            "warn": null,
            "fail": {
                "value": 30,
                "sourceText": "30%",
                "line": 21
            },
            "line": 21
        },
        "metricId": "third_party_share_pct",
        "unit": "pct",
        "floor": {
            "status": "established",
            "metricId": "third_party_share_pct",
            "unit": "pct",
            "value": 0.6434327575943157,
            "sampleCount": 24,
            "scalingFactor": 1.2
        },
        "override": null,
        "status": "conforme",
        "observed": 20.527045769764214,
        "headroom": 9.472954230235786,
        "withinNoise": false,
        "delta": null
    },
    {
        "scenarioId": "/accueil",
        "scenarioLabel": "/accueil",
        "pass": "cold",
        "rule": {
            "kind": "relative",
            "scope": {
                "kind": "service"
            },
            "metricId": "transferred_bytes",
            "unit": "pct",
            "warn": {
                "value": 3,
                "sourceText": "+3%",
                "line": 22
            },
            "fail": null,
            "line": 22
        },
        "metricId": "transferred_bytes",
        "unit": "pct",
        "floor": {
            "status": "established",
            "metricId": "transferred_bytes",
            "unit": "bytes",
            "value": 7380,
            "sampleCount": 24,
            "scalingFactor": 1.2
        },
        "override": null,
        "status": "conforme",
        "observed": 0.2380952380952381,
        "headroom": 2.761904761904762,
        "withinNoise": false,
        "delta": {
            "metricId": "transferred_bytes",
            "unit": "bytes",
            "before": 840000,
            "after": 842000,
            "value": 2000,
            "floor": {
                "status": "established",
                "metricId": "transferred_bytes",
                "unit": "bytes",
                "value": 7380,
                "sampleCount": 24,
                "scalingFactor": 1.2
            },
            "classification": "no-significant-change"
        }
    },
    {
        "scenarioId": "/demarches/acte-naissance",
        "scenarioLabel": "/demarches/acte-naissance",
        "pass": "cold",
        "rule": {
            "kind": "relative",
            "scope": {
                "kind": "service"
            },
            "metricId": "transferred_bytes",
            "unit": "pct",
            "warn": {
                "value": 3,
                "sourceText": "+3%",
                "line": 22
            },
            "fail": null,
            "line": 22
        },
        "metricId": "transferred_bytes",
        "unit": "pct",
        "floor": {
            "status": "established",
            "metricId": "transferred_bytes",
            "unit": "bytes",
            "value": 7380,
            "sampleCount": 24,
            "scalingFactor": 1.2
        },
        "override": null,
        "status": "warn",
        "observed": 16.517055655296232,
        "headroom": -13.517055655296232,
        "withinNoise": false,
        "delta": {
            "metricId": "transferred_bytes",
            "unit": "bytes",
            "before": 1114000,
            "after": 1298000,
            "value": 184000,
            "floor": {
                "status": "established",
                "metricId": "transferred_bytes",
                "unit": "bytes",
                "value": 7380,
                "sampleCount": 24,
                "scalingFactor": 1.2
            },
            "classification": "regression"
        }
    },
    {
        "scenarioId": "demande-acte",
        "scenarioLabel": "journey: demande d'acte",
        "pass": "cold",
        "rule": {
            "kind": "relative",
            "scope": {
                "kind": "service"
            },
            "metricId": "transferred_bytes",
            "unit": "pct",
            "warn": {
                "value": 3,
                "sourceText": "+3%",
                "line": 22
            },
            "fail": null,
            "line": 22
        },
        "metricId": "transferred_bytes",
        "unit": "pct",
        "floor": {
            "status": "established",
            "metricId": "transferred_bytes",
            "unit": "bytes",
            "value": 7380,
            "sampleCount": 24,
            "scalingFactor": 1.2
        },
        "override": null,
        "status": "warn",
        "observed": 14.626391096979333,
        "headroom": -11.626391096979333,
        "withinNoise": false,
        "delta": {
            "metricId": "transferred_bytes",
            "unit": "bytes",
            "before": 1258000,
            "after": 1442000,
            "value": 184000,
            "floor": {
                "status": "established",
                "metricId": "transferred_bytes",
                "unit": "bytes",
                "value": 7380,
                "sampleCount": 24,
                "scalingFactor": 1.2
            },
            "classification": "regression"
        }
    }
],
    summary: {
    "conclusion": "failure",
    "counts": {
        "conforme": 6,
        "warn": 3,
        "breach": 1,
        "nonEvalue": 0
    },
    "blocking": [
        {
            "scenarioId": "demande-acte",
            "scenarioLabel": "journey: demande d'acte",
            "pass": "cold",
            "rule": {
                "kind": "absolute",
                "scope": {
                    "kind": "journey",
                    "journey": "demande-acte"
                },
                "metricId": "transferred_bytes",
                "unit": "bytes",
                "warn": null,
                "fail": {
                    "value": 1400000,
                    "sourceText": "1400KB",
                    "line": 19
                },
                "line": 19
            },
            "metricId": "transferred_bytes",
            "unit": "bytes",
            "floor": {
                "status": "established",
                "metricId": "transferred_bytes",
                "unit": "bytes",
                "value": 7380,
                "sampleCount": 24,
                "scalingFactor": 1.2
            },
            "override": null,
            "status": "breach",
            "observed": 1442000,
            "headroom": -42000,
            "withinNoise": false,
            "delta": null
        }
    ],
    "overridden": []
},
  },
  pullScenarios: [
  {
    "id": "/accueil",
    "kind": "route",
    "label": "/accueil",
    "candidate": {
      "pass": "cold",
      "sampleCount": 5,
      "metrics": [
        {
          "metricId": "transferred_bytes",
          "unit": "bytes",
          "median": 842000,
          "mad": 3000,
          "min": 836000,
          "max": 848000,
          "sampleCount": 5
        },
        {
          "metricId": "request_count",
          "unit": "count",
          "median": 61,
          "mad": 1,
          "min": 59,
          "max": 63,
          "sampleCount": 5
        },
        {
          "metricId": "third_party_bytes",
          "unit": "bytes",
          "median": 185240,
          "mad": 660,
          "min": 183920,
          "max": 186560,
          "sampleCount": 5
        },
        {
          "metricId": "third_party_share_pct",
          "unit": "pct",
          "median": 22,
          "mad": 0.14941022280471827,
          "min": 21.68867924528302,
          "max": 22.315789473684212,
          "sampleCount": 5
        }
      ]
    },
    "baseline": {
      "pass": "cold",
      "sampleCount": 5,
      "metrics": [
        {
          "metricId": "transferred_bytes",
          "unit": "bytes",
          "median": 840000,
          "mad": 3000,
          "min": 834000,
          "max": 846000,
          "sampleCount": 5
        },
        {
          "metricId": "request_count",
          "unit": "count",
          "median": 61,
          "mad": 1,
          "min": 59,
          "max": 63,
          "sampleCount": 5
        },
        {
          "metricId": "third_party_bytes",
          "unit": "bytes",
          "median": 184800,
          "mad": 660,
          "min": 183480,
          "max": 186120,
          "sampleCount": 5
        },
        {
          "metricId": "third_party_share_pct",
          "unit": "pct",
          "median": 22,
          "mad": 0.14976710856323905,
          "min": 21.687943262411345,
          "max": 22.31654676258993,
          "sampleCount": 5
        }
      ]
    },
    "floors": [
      {
        "status": "established",
        "metricId": "transferred_bytes",
        "unit": "bytes",
        "value": 7380,
        "sampleCount": 24,
        "scalingFactor": 1.2
      },
      {
        "status": "established",
        "metricId": "request_count",
        "unit": "count",
        "value": 1.2,
        "sampleCount": 24,
        "scalingFactor": 1.2
      },
      {
        "status": "established",
        "metricId": "third_party_share_pct",
        "unit": "pct",
        "value": 0.6434327575943157,
        "sampleCount": 24,
        "scalingFactor": 1.2
      }
    ]
  },
  {
    "id": "/demarches/acte-naissance",
    "kind": "route",
    "label": "/demarches/acte-naissance",
    "candidate": {
      "pass": "cold",
      "sampleCount": 5,
      "metrics": [
        {
          "metricId": "transferred_bytes",
          "unit": "bytes",
          "median": 1298000,
          "mad": 9000,
          "min": 1280000,
          "max": 1316000,
          "sampleCount": 5
        },
        {
          "metricId": "request_count",
          "unit": "count",
          "median": 84,
          "mad": 1,
          "min": 82,
          "max": 86,
          "sampleCount": 5
        },
        {
          "metricId": "dom_node_count",
          "unit": "count",
          "median": 2140,
          "mad": 160,
          "min": 1820,
          "max": 2460,
          "sampleCount": 5
        },
        {
          "metricId": "js_execution_ms",
          "unit": "ms",
          "median": 612,
          "mad": 15,
          "min": 582,
          "max": 642,
          "sampleCount": 5
        },
        {
          "metricId": "third_party_bytes",
          "unit": "bytes",
          "median": 378000,
          "mad": 3000,
          "min": 372000,
          "max": 384000,
          "sampleCount": 5
        },
        {
          "metricId": "third_party_share_pct",
          "unit": "pct",
          "median": 29.121725731895225,
          "mad": 0.4154476924012336,
          "min": 28.267477203647417,
          "max": 30,
          "sampleCount": 5
        }
      ]
    },
    "baseline": {
      "pass": "cold",
      "sampleCount": 5,
      "metrics": [
        {
          "metricId": "transferred_bytes",
          "unit": "bytes",
          "median": 1114000,
          "mad": 6000,
          "min": 1102000,
          "max": 1126000,
          "sampleCount": 5
        },
        {
          "metricId": "request_count",
          "unit": "count",
          "median": 82,
          "mad": 1,
          "min": 80,
          "max": 84,
          "sampleCount": 5
        },
        {
          "metricId": "dom_node_count",
          "unit": "count",
          "median": 2118,
          "mad": 150,
          "min": 1818,
          "max": 2418,
          "sampleCount": 5
        },
        {
          "metricId": "js_execution_ms",
          "unit": "ms",
          "median": 548,
          "mad": 12,
          "min": 524,
          "max": 572,
          "sampleCount": 5
        },
        {
          "metricId": "third_party_bytes",
          "unit": "bytes",
          "median": 180000,
          "mad": 2000,
          "min": 176000,
          "max": 184000,
          "sampleCount": 5
        },
        {
          "metricId": "third_party_share_pct",
          "unit": "pct",
          "median": 16.15798922800718,
          "mad": 0.2591134239863244,
          "min": 15.630550621669629,
          "max": 16.696914700544465,
          "sampleCount": 5
        }
      ]
    },
    "floors": [
      {
        "status": "established",
        "metricId": "transferred_bytes",
        "unit": "bytes",
        "value": 7380,
        "sampleCount": 24,
        "scalingFactor": 1.2
      },
      {
        "status": "established",
        "metricId": "request_count",
        "unit": "count",
        "value": 1.2,
        "sampleCount": 24,
        "scalingFactor": 1.2
      },
      {
        "status": "established",
        "metricId": "third_party_share_pct",
        "unit": "pct",
        "value": 0.6434327575943157,
        "sampleCount": 24,
        "scalingFactor": 1.2
      }
    ]
  },
  {
    "id": "demande-acte",
    "kind": "journey",
    "label": "journey: demande d'acte",
    "candidate": {
      "pass": "cold",
      "sampleCount": 5,
      "metrics": [
        {
          "metricId": "transferred_bytes",
          "unit": "bytes",
          "median": 1442000,
          "mad": 9000,
          "min": 1424000,
          "max": 1460000,
          "sampleCount": 5
        },
        {
          "metricId": "request_count",
          "unit": "count",
          "median": 100,
          "mad": 1,
          "min": 98,
          "max": 102,
          "sampleCount": 5
        },
        {
          "metricId": "third_party_bytes",
          "unit": "bytes",
          "median": 296000,
          "mad": 1847.4341192787979,
          "min": 292305.13176144246,
          "max": 299694.86823855754,
          "sampleCount": 5
        },
        {
          "metricId": "third_party_share_pct",
          "unit": "pct",
          "median": 20.527045769764214,
          "mad": 0.24479565008924808,
          "min": 20.020899435715236,
          "max": 21.04598793810095,
          "sampleCount": 5
        }
      ]
    },
    "baseline": {
      "pass": "cold",
      "sampleCount": 5,
      "metrics": [
        {
          "metricId": "transferred_bytes",
          "unit": "bytes",
          "median": 1258000,
          "mad": 9000,
          "min": 1240000,
          "max": 1276000,
          "sampleCount": 5
        },
        {
          "metricId": "request_count",
          "unit": "count",
          "median": 96,
          "mad": 1,
          "min": 94,
          "max": 98,
          "sampleCount": 5
        },
        {
          "metricId": "third_party_bytes",
          "unit": "bytes",
          "median": 226000,
          "mad": 1616.8521462639037,
          "min": 222766.2957074722,
          "max": 229233.7042925278,
          "sampleCount": 5
        },
        {
          "metricId": "third_party_share_pct",
          "unit": "pct",
          "median": 17.965023847376788,
          "mad": 0.24578118872721078,
          "min": 17.45817364478622,
          "max": 18.486589055849016,
          "sampleCount": 5
        }
      ]
    },
    "floors": [
      {
        "status": "established",
        "metricId": "transferred_bytes",
        "unit": "bytes",
        "value": 7380,
        "sampleCount": 24,
        "scalingFactor": 1.2
      },
      {
        "status": "established",
        "metricId": "request_count",
        "unit": "count",
        "value": 1.2,
        "sampleCount": 24,
        "scalingFactor": 1.2
      },
      {
        "status": "established",
        "metricId": "third_party_share_pct",
        "unit": "pct",
        "value": 0.6434327575943157,
        "sampleCount": 24,
        "scalingFactor": 1.2
      }
    ]
  }
],
  provenance: {
  "methodologyVersion": "v1.2",
  "models": [
    "ecoindex@0.1.0",
    "swd@0.1.0",
    "onebyte@0.1.0"
  ],
  "runId": "#4812",
  "ledgerRef": "8ec4b0aa",
  "verificationUrl": "balise.fr/v/8ec4b0aa",
  "fingerprintMatched": true
},
};
