// generated by scripts/generate-budget-canon.ts. do not edit by hand.
// run `pnpm gen:budget-canon` to rebuild; budget-canon.test.ts fails if this
// file and the generator ever disagree.
//
// every verdict here was computed by @balise/budgets from the balise.yml below
// and from the same runs the attribution canon explains. nothing in it is a
// status someone chose for the screen.

import type { BudgetAssessment, BudgetConfig, BudgetOverride, CheckSummary } from '@balise/schemas';

export interface BudgetMeasurement {
  scenarioId: string;
  label: string;
  baseBytes: number;
  headBytes: number;
  madBytes: number;
  floorBytes: number;
}

export interface BudgetCanon {
  file: string;
  branchName: string;
  service: string;
  /** the file as the customer wrote it, which is what the yaml view renders. */
  source: string;
  config: BudgetConfig;
  override: BudgetOverride;
  /** the branch view: the latest measurement of main, nothing to compare to. */
  main: { assessments: BudgetAssessment[]; summary: CheckSummary };
  /** the pull request: its scenarios against main. */
  pull: { assessments: BudgetAssessment[]; summary: CheckSummary };
  measurements: BudgetMeasurement[];
}

export const budgetCanon: BudgetCanon = {
  file: 'balise.yml',
  branchName: 'main',
  service: "portail-metropolitain",
  source: "# balise.yml · sevre-et-loire.fr · pack rgesn-2024-v2\nversion: 1\nservice: portail-metropolitain\nruns: 5\nprofiles: [desktop-fibre, mobile-4g]\nreference_model: swd@4.0\n# deltas below the computed noise floor are never failures\nnoise_floor: auto\n\nbudgets:\n  - scope: /accueil\n    bytes: { warn: 860KB, fail: 900KB }\n  - scope: /demarches/*\n    bytes: { warn: 1250KB, fail: 1300KB }\n    requests: { fail: 90 }\n  - scope: /actualites\n    bytes: { warn: 860KB, fail: 900KB }\n  - scope: journey:demande-acte\n    bytes: { fail: 1400KB }\n  - scope: service\n    third_party_share: { fail: 30% }\n    relative_to_baseline: { warn: +3% }\n\ncheck:\n  block_merge_on: fail\n  annotate_files: true\n",
  config: {
  "version": 1,
  "service": "portail-metropolitain",
  "runs": 5,
  "profiles": [
    "desktop-fibre",
    "mobile-4g"
  ],
  "referenceModel": "swd@4.0",
  "noiseFloor": "auto",
  "rules": [
    {
      "kind": "absolute",
      "scope": {
        "kind": "route",
        "pattern": "/accueil"
      },
      "metricId": "transferred_bytes",
      "unit": "bytes",
      "warn": {
        "value": 860000,
        "sourceText": "860KB",
        "line": 12
      },
      "fail": {
        "value": 900000,
        "sourceText": "900KB",
        "line": 12
      },
      "line": 12
    },
    {
      "kind": "absolute",
      "scope": {
        "kind": "route",
        "pattern": "/demarches/*"
      },
      "metricId": "transferred_bytes",
      "unit": "bytes",
      "warn": {
        "value": 1250000,
        "sourceText": "1250KB",
        "line": 14
      },
      "fail": {
        "value": 1300000,
        "sourceText": "1300KB",
        "line": 14
      },
      "line": 14
    },
    {
      "kind": "absolute",
      "scope": {
        "kind": "route",
        "pattern": "/demarches/*"
      },
      "metricId": "request_count",
      "unit": "count",
      "warn": null,
      "fail": {
        "value": 90,
        "sourceText": "90",
        "line": 15
      },
      "line": 15
    },
    {
      "kind": "absolute",
      "scope": {
        "kind": "route",
        "pattern": "/actualites"
      },
      "metricId": "transferred_bytes",
      "unit": "bytes",
      "warn": {
        "value": 860000,
        "sourceText": "860KB",
        "line": 17
      },
      "fail": {
        "value": 900000,
        "sourceText": "900KB",
        "line": 17
      },
      "line": 17
    },
    {
      "kind": "absolute",
      "scope": {
        "kind": "journey",
        "journey": "demande-acte"
      },
      "metricId": "transferred_bytes",
      "unit": "bytes",
      "warn": null,
      "fail": {
        "value": 1400000,
        "sourceText": "1400KB",
        "line": 19
      },
      "line": 19
    },
    {
      "kind": "absolute",
      "scope": {
        "kind": "service"
      },
      "metricId": "third_party_share_pct",
      "unit": "pct",
      "warn": null,
      "fail": {
        "value": 30,
        "sourceText": "30%",
        "line": 21
      },
      "line": 21
    },
    {
      "kind": "relative",
      "scope": {
        "kind": "service"
      },
      "metricId": "transferred_bytes",
      "unit": "pct",
      "warn": {
        "value": 3,
        "sourceText": "+3%",
        "line": 22
      },
      "fail": null,
      "line": 22
    }
  ],
  "check": {
    "blockMergeOn": "fail",
    "annotateFiles": true
  }
},
  override: {
  "scope": {
    "kind": "route",
    "pattern": "/actualites"
  },
  "metricId": "transferred_bytes",
  "reason": "Mandated by comms for the 14 July campaign, removal scheduled 01 Sep.",
  "by": "m. carbonne",
  "recordedAt": "2026-07-08T11:05:00.000Z",
  "expiresAt": "2026-09-01T00:00:00.000Z",
  "requestedIn": "PR #401",
  "ledgerRef": "8737fb74"
},
  main: {
    assessments: [
    {
        "scenarioId": "/accueil",
        "scenarioLabel": "/accueil",
        "pass": "cold",
        "rule": {
            "kind": "absolute",
            "scope": {
                "kind": "route",
                "pattern": "/accueil"
            },
            "metricId": "transferred_bytes",
            "unit": "bytes",
            "warn": {
                "value": 860000,
                "sourceText": "860KB",
                "line": 12
            },
            "fail": {
                "value": 900000,
                "sourceText": "900KB",
                "line": 12
            },
            "line": 12
        },
        "metricId": "transferred_bytes",
        "unit": "bytes",
        "floor": {
            "status": "established",
            "metricId": "transferred_bytes",
            "unit": "bytes",
            "value": 7000,
            "sampleCount": 24,
            "scalingFactor": 1.2
        },
        "override": null,
        "status": "conforme",
        "observed": 840000,
        "headroom": 60000,
        "withinNoise": false,
        "delta": null
    },
    {
        "scenarioId": "/demarches/acte-naissance",
        "scenarioLabel": "/demarches/acte-naissance",
        "pass": "cold",
        "rule": {
            "kind": "absolute",
            "scope": {
                "kind": "route",
                "pattern": "/demarches/*"
            },
            "metricId": "transferred_bytes",
            "unit": "bytes",
            "warn": {
                "value": 1250000,
                "sourceText": "1250KB",
                "line": 14
            },
            "fail": {
                "value": 1300000,
                "sourceText": "1300KB",
                "line": 14
            },
            "line": 14
        },
        "metricId": "transferred_bytes",
        "unit": "bytes",
        "floor": {
            "status": "established",
            "metricId": "transferred_bytes",
            "unit": "bytes",
            "value": 7000,
            "sampleCount": 24,
            "scalingFactor": 1.2
        },
        "override": null,
        "status": "conforme",
        "observed": 1114000,
        "headroom": 186000,
        "withinNoise": false,
        "delta": null
    },
    {
        "scenarioId": "/demarches/acte-naissance",
        "scenarioLabel": "/demarches/acte-naissance",
        "pass": "cold",
        "rule": {
            "kind": "absolute",
            "scope": {
                "kind": "route",
                "pattern": "/demarches/*"
            },
            "metricId": "request_count",
            "unit": "count",
            "warn": null,
            "fail": {
                "value": 90,
                "sourceText": "90",
                "line": 15
            },
            "line": 15
        },
        "metricId": "request_count",
        "unit": "count",
        "floor": {
            "status": "established",
            "metricId": "request_count",
            "unit": "count",
            "value": 1,
            "sampleCount": 24,
            "scalingFactor": 1.2
        },
        "override": null,
        "status": "conforme",
        "observed": 82,
        "headroom": 8,
        "withinNoise": false,
        "delta": null
    },
    {
        "scenarioId": "/actualites",
        "scenarioLabel": "/actualites",
        "pass": "cold",
        "rule": {
            "kind": "absolute",
            "scope": {
                "kind": "route",
                "pattern": "/actualites"
            },
            "metricId": "transferred_bytes",
            "unit": "bytes",
            "warn": {
                "value": 860000,
                "sourceText": "860KB",
                "line": 17
            },
            "fail": {
                "value": 900000,
                "sourceText": "900KB",
                "line": 17
            },
            "line": 17
        },
        "metricId": "transferred_bytes",
        "unit": "bytes",
        "floor": {
            "status": "established",
            "metricId": "transferred_bytes",
            "unit": "bytes",
            "value": 7000,
            "sampleCount": 24,
            "scalingFactor": 1.2
        },
        "override": {
            "scope": {
                "kind": "route",
                "pattern": "/actualites"
            },
            "metricId": "transferred_bytes",
            "reason": "Mandated by comms for the 14 July campaign, removal scheduled 01 Sep.",
            "by": "m. carbonne",
            "recordedAt": "2026-07-08T11:05:00.000Z",
            "expiresAt": "2026-09-01T00:00:00.000Z",
            "requestedIn": "PR #401",
            "ledgerRef": "8737fb74"
        },
        "status": "breach",
        "observed": 1240000,
        "headroom": -340000,
        "withinNoise": false,
        "delta": null
    },
    {
        "scenarioId": "demande-acte",
        "scenarioLabel": "journey: demande d'acte",
        "pass": "cold",
        "rule": {
            "kind": "absolute",
            "scope": {
                "kind": "journey",
                "journey": "demande-acte"
            },
            "metricId": "transferred_bytes",
            "unit": "bytes",
            "warn": null,
            "fail": {
                "value": 1400000,
                "sourceText": "1400KB",
                "line": 19
            },
            "line": 19
        },
        "metricId": "transferred_bytes",
        "unit": "bytes",
        "floor": {
            "status": "established",
            "metricId": "transferred_bytes",
            "unit": "bytes",
            "value": 7000,
            "sampleCount": 24,
            "scalingFactor": 1.2
        },
        "override": null,
        "status": "conforme",
        "observed": 1258000,
        "headroom": 142000,
        "withinNoise": false,
        "delta": null
    },
    {
        "scenarioId": "/accueil",
        "scenarioLabel": "/accueil",
        "pass": "cold",
        "rule": {
            "kind": "absolute",
            "scope": {
                "kind": "service"
            },
            "metricId": "third_party_share_pct",
            "unit": "pct",
            "warn": null,
            "fail": {
                "value": 30,
                "sourceText": "30%",
                "line": 21
            },
            "line": 21
        },
        "metricId": "third_party_share_pct",
        "unit": "pct",
        "floor": {
            "status": "established",
            "metricId": "third_party_share_pct",
            "unit": "pct",
            "value": 0.5,
            "sampleCount": 24,
            "scalingFactor": 1.2
        },
        "override": null,
        "status": "conforme",
        "observed": 22,
        "headroom": 8,
        "withinNoise": false,
        "delta": null
    },
    {
        "scenarioId": "/demarches/acte-naissance",
        "scenarioLabel": "/demarches/acte-naissance",
        "pass": "cold",
        "rule": {
            "kind": "absolute",
            "scope": {
                "kind": "service"
            },
            "metricId": "third_party_share_pct",
            "unit": "pct",
            "warn": null,
            "fail": {
                "value": 30,
                "sourceText": "30%",
                "line": 21
            },
            "line": 21
        },
        "metricId": "third_party_share_pct",
        "unit": "pct",
        "floor": {
            "status": "established",
            "metricId": "third_party_share_pct",
            "unit": "pct",
            "value": 0.5,
            "sampleCount": 24,
            "scalingFactor": 1.2
        },
        "override": null,
        "status": "conforme",
        "observed": 16.15798922800718,
        "headroom": 13.842010771992818,
        "withinNoise": false,
        "delta": null
    },
    {
        "scenarioId": "/actualites",
        "scenarioLabel": "/actualites",
        "pass": "cold",
        "rule": {
            "kind": "absolute",
            "scope": {
                "kind": "service"
            },
            "metricId": "third_party_share_pct",
            "unit": "pct",
            "warn": null,
            "fail": {
                "value": 30,
                "sourceText": "30%",
                "line": 21
            },
            "line": 21
        },
        "metricId": "third_party_share_pct",
        "unit": "pct",
        "floor": {
            "status": "established",
            "metricId": "third_party_share_pct",
            "unit": "pct",
            "value": 0.5,
            "sampleCount": 24,
            "scalingFactor": 1.2
        },
        "override": null,
        "status": "breach",
        "observed": 38.70967741935484,
        "headroom": -8.70967741935484,
        "withinNoise": false,
        "delta": null
    },
    {
        "scenarioId": "demande-acte",
        "scenarioLabel": "journey: demande d'acte",
        "pass": "cold",
        "rule": {
            "kind": "absolute",
            "scope": {
                "kind": "service"
            },
            "metricId": "third_party_share_pct",
            "unit": "pct",
            "warn": null,
            "fail": {
                "value": 30,
                "sourceText": "30%",
                "line": 21
            },
            "line": 21
        },
        "metricId": "third_party_share_pct",
        "unit": "pct",
        "floor": {
            "status": "established",
            "metricId": "third_party_share_pct",
            "unit": "pct",
            "value": 0.5,
            "sampleCount": 24,
            "scalingFactor": 1.2
        },
        "override": null,
        "status": "conforme",
        "observed": 17.965023847376788,
        "headroom": 12.034976152623212,
        "withinNoise": false,
        "delta": null
    },
    {
        "scenarioId": "/accueil",
        "scenarioLabel": "/accueil",
        "pass": "cold",
        "rule": {
            "kind": "relative",
            "scope": {
                "kind": "service"
            },
            "metricId": "transferred_bytes",
            "unit": "pct",
            "warn": {
                "value": 3,
                "sourceText": "+3%",
                "line": 22
            },
            "fail": null,
            "line": 22
        },
        "metricId": "transferred_bytes",
        "unit": "pct",
        "floor": {
            "status": "established",
            "metricId": "transferred_bytes",
            "unit": "bytes",
            "value": 7000,
            "sampleCount": 24,
            "scalingFactor": 1.2
        },
        "override": null,
        "status": "non_evalue",
        "reason": "no-baseline",
        "observed": null,
        "headroom": null,
        "withinNoise": false,
        "delta": null
    },
    {
        "scenarioId": "/demarches/acte-naissance",
        "scenarioLabel": "/demarches/acte-naissance",
        "pass": "cold",
        "rule": {
            "kind": "relative",
            "scope": {
                "kind": "service"
            },
            "metricId": "transferred_bytes",
            "unit": "pct",
            "warn": {
                "value": 3,
                "sourceText": "+3%",
                "line": 22
            },
            "fail": null,
            "line": 22
        },
        "metricId": "transferred_bytes",
        "unit": "pct",
        "floor": {
            "status": "established",
            "metricId": "transferred_bytes",
            "unit": "bytes",
            "value": 7000,
            "sampleCount": 24,
            "scalingFactor": 1.2
        },
        "override": null,
        "status": "non_evalue",
        "reason": "no-baseline",
        "observed": null,
        "headroom": null,
        "withinNoise": false,
        "delta": null
    },
    {
        "scenarioId": "/actualites",
        "scenarioLabel": "/actualites",
        "pass": "cold",
        "rule": {
            "kind": "relative",
            "scope": {
                "kind": "service"
            },
            "metricId": "transferred_bytes",
            "unit": "pct",
            "warn": {
                "value": 3,
                "sourceText": "+3%",
                "line": 22
            },
            "fail": null,
            "line": 22
        },
        "metricId": "transferred_bytes",
        "unit": "pct",
        "floor": {
            "status": "established",
            "metricId": "transferred_bytes",
            "unit": "bytes",
            "value": 7000,
            "sampleCount": 24,
            "scalingFactor": 1.2
        },
        "override": null,
        "status": "non_evalue",
        "reason": "no-baseline",
        "observed": null,
        "headroom": null,
        "withinNoise": false,
        "delta": null
    },
    {
        "scenarioId": "demande-acte",
        "scenarioLabel": "journey: demande d'acte",
        "pass": "cold",
        "rule": {
            "kind": "relative",
            "scope": {
                "kind": "service"
            },
            "metricId": "transferred_bytes",
            "unit": "pct",
            "warn": {
                "value": 3,
                "sourceText": "+3%",
                "line": 22
            },
            "fail": null,
            "line": 22
        },
        "metricId": "transferred_bytes",
        "unit": "pct",
        "floor": {
            "status": "established",
            "metricId": "transferred_bytes",
            "unit": "bytes",
            "value": 7000,
            "sampleCount": 24,
            "scalingFactor": 1.2
        },
        "override": null,
        "status": "non_evalue",
        "reason": "no-baseline",
        "observed": null,
        "headroom": null,
        "withinNoise": false,
        "delta": null
    }
],
    summary: {
    "conclusion": "failure",
    "counts": {
        "conforme": 7,
        "warn": 0,
        "breach": 2,
        "nonEvalue": 4
    },
    "blocking": [
        {
            "scenarioId": "/actualites",
            "scenarioLabel": "/actualites",
            "pass": "cold",
            "rule": {
                "kind": "absolute",
                "scope": {
                    "kind": "service"
                },
                "metricId": "third_party_share_pct",
                "unit": "pct",
                "warn": null,
                "fail": {
                    "value": 30,
                    "sourceText": "30%",
                    "line": 21
                },
                "line": 21
            },
            "metricId": "third_party_share_pct",
            "unit": "pct",
            "floor": {
                "status": "established",
                "metricId": "third_party_share_pct",
                "unit": "pct",
                "value": 0.5,
                "sampleCount": 24,
                "scalingFactor": 1.2
            },
            "override": null,
            "status": "breach",
            "observed": 38.70967741935484,
            "headroom": -8.70967741935484,
            "withinNoise": false,
            "delta": null
        }
    ],
    "overridden": [
        {
            "scenarioId": "/actualites",
            "scenarioLabel": "/actualites",
            "pass": "cold",
            "rule": {
                "kind": "absolute",
                "scope": {
                    "kind": "route",
                    "pattern": "/actualites"
                },
                "metricId": "transferred_bytes",
                "unit": "bytes",
                "warn": {
                    "value": 860000,
                    "sourceText": "860KB",
                    "line": 17
                },
                "fail": {
                    "value": 900000,
                    "sourceText": "900KB",
                    "line": 17
                },
                "line": 17
            },
            "metricId": "transferred_bytes",
            "unit": "bytes",
            "floor": {
                "status": "established",
                "metricId": "transferred_bytes",
                "unit": "bytes",
                "value": 7000,
                "sampleCount": 24,
                "scalingFactor": 1.2
            },
            "override": {
                "scope": {
                    "kind": "route",
                    "pattern": "/actualites"
                },
                "metricId": "transferred_bytes",
                "reason": "Mandated by comms for the 14 July campaign, removal scheduled 01 Sep.",
                "by": "m. carbonne",
                "recordedAt": "2026-07-08T11:05:00.000Z",
                "expiresAt": "2026-09-01T00:00:00.000Z",
                "requestedIn": "PR #401",
                "ledgerRef": "8737fb74"
            },
            "status": "breach",
            "observed": 1240000,
            "headroom": -340000,
            "withinNoise": false,
            "delta": null
        }
    ]
},
  },
  pull: {
    assessments: [
    {
        "scenarioId": "/accueil",
        "scenarioLabel": "/accueil",
        "pass": "cold",
        "rule": {
            "kind": "absolute",
            "scope": {
                "kind": "route",
                "pattern": "/accueil"
            },
            "metricId": "transferred_bytes",
            "unit": "bytes",
            "warn": {
                "value": 860000,
                "sourceText": "860KB",
                "line": 12
            },
            "fail": {
                "value": 900000,
                "sourceText": "900KB",
                "line": 12
            },
            "line": 12
        },
        "metricId": "transferred_bytes",
        "unit": "bytes",
        "floor": {
            "status": "established",
            "metricId": "transferred_bytes",
            "unit": "bytes",
            "value": 7000,
            "sampleCount": 24,
            "scalingFactor": 1.2
        },
        "override": null,
        "status": "conforme",
        "observed": 842000,
        "headroom": 58000,
        "withinNoise": false,
        "delta": null
    },
    {
        "scenarioId": "/demarches/acte-naissance",
        "scenarioLabel": "/demarches/acte-naissance",
        "pass": "cold",
        "rule": {
            "kind": "absolute",
            "scope": {
                "kind": "route",
                "pattern": "/demarches/*"
            },
            "metricId": "transferred_bytes",
            "unit": "bytes",
            "warn": {
                "value": 1250000,
                "sourceText": "1250KB",
                "line": 14
            },
            "fail": {
                "value": 1300000,
                "sourceText": "1300KB",
                "line": 14
            },
            "line": 14
        },
        "metricId": "transferred_bytes",
        "unit": "bytes",
        "floor": {
            "status": "established",
            "metricId": "transferred_bytes",
            "unit": "bytes",
            "value": 7000,
            "sampleCount": 24,
            "scalingFactor": 1.2
        },
        "override": null,
        "status": "warn",
        "observed": 1298000,
        "headroom": 2000,
        "withinNoise": true,
        "delta": null
    },
    {
        "scenarioId": "/demarches/acte-naissance",
        "scenarioLabel": "/demarches/acte-naissance",
        "pass": "cold",
        "rule": {
            "kind": "absolute",
            "scope": {
                "kind": "route",
                "pattern": "/demarches/*"
            },
            "metricId": "request_count",
            "unit": "count",
            "warn": null,
            "fail": {
                "value": 90,
                "sourceText": "90",
                "line": 15
            },
            "line": 15
        },
        "metricId": "request_count",
        "unit": "count",
        "floor": {
            "status": "established",
            "metricId": "request_count",
            "unit": "count",
            "value": 1,
            "sampleCount": 24,
            "scalingFactor": 1.2
        },
        "override": null,
        "status": "conforme",
        "observed": 84,
        "headroom": 6,
        "withinNoise": false,
        "delta": null
    },
    {
        "scenarioId": "demande-acte",
        "scenarioLabel": "journey: demande d'acte",
        "pass": "cold",
        "rule": {
            "kind": "absolute",
            "scope": {
                "kind": "journey",
                "journey": "demande-acte"
            },
            "metricId": "transferred_bytes",
            "unit": "bytes",
            "warn": null,
            "fail": {
                "value": 1400000,
                "sourceText": "1400KB",
                "line": 19
            },
            "line": 19
        },
        "metricId": "transferred_bytes",
        "unit": "bytes",
        "floor": {
            "status": "established",
            "metricId": "transferred_bytes",
            "unit": "bytes",
            "value": 7000,
            "sampleCount": 24,
            "scalingFactor": 1.2
        },
        "override": null,
        "status": "breach",
        "observed": 1442000,
        "headroom": -42000,
        "withinNoise": false,
        "delta": null
    },
    {
        "scenarioId": "/accueil",
        "scenarioLabel": "/accueil",
        "pass": "cold",
        "rule": {
            "kind": "absolute",
            "scope": {
                "kind": "service"
            },
            "metricId": "third_party_share_pct",
            "unit": "pct",
            "warn": null,
            "fail": {
                "value": 30,
                "sourceText": "30%",
                "line": 21
            },
            "line": 21
        },
        "metricId": "third_party_share_pct",
        "unit": "pct",
        "floor": {
            "status": "established",
            "metricId": "third_party_share_pct",
            "unit": "pct",
            "value": 0.5,
            "sampleCount": 24,
            "scalingFactor": 1.2
        },
        "override": null,
        "status": "conforme",
        "observed": 22,
        "headroom": 8,
        "withinNoise": false,
        "delta": null
    },
    {
        "scenarioId": "/demarches/acte-naissance",
        "scenarioLabel": "/demarches/acte-naissance",
        "pass": "cold",
        "rule": {
            "kind": "absolute",
            "scope": {
                "kind": "service"
            },
            "metricId": "third_party_share_pct",
            "unit": "pct",
            "warn": null,
            "fail": {
                "value": 30,
                "sourceText": "30%",
                "line": 21
            },
            "line": 21
        },
        "metricId": "third_party_share_pct",
        "unit": "pct",
        "floor": {
            "status": "established",
            "metricId": "third_party_share_pct",
            "unit": "pct",
            "value": 0.5,
            "sampleCount": 24,
            "scalingFactor": 1.2
        },
        "override": null,
        "status": "conforme",
        "observed": 29.121725731895225,
        "headroom": 0.878274268104775,
        "withinNoise": false,
        "delta": null
    },
    {
        "scenarioId": "demande-acte",
        "scenarioLabel": "journey: demande d'acte",
        "pass": "cold",
        "rule": {
            "kind": "absolute",
            "scope": {
                "kind": "service"
            },
            "metricId": "third_party_share_pct",
            "unit": "pct",
            "warn": null,
            "fail": {
                "value": 30,
                "sourceText": "30%",
                "line": 21
            },
            "line": 21
        },
        "metricId": "third_party_share_pct",
        "unit": "pct",
        "floor": {
            "status": "established",
            "metricId": "third_party_share_pct",
            "unit": "pct",
            "value": 0.5,
            "sampleCount": 24,
            "scalingFactor": 1.2
        },
        "override": null,
        "status": "conforme",
        "observed": 20.527045769764214,
        "headroom": 9.472954230235786,
        "withinNoise": false,
        "delta": null
    },
    {
        "scenarioId": "/accueil",
        "scenarioLabel": "/accueil",
        "pass": "cold",
        "rule": {
            "kind": "relative",
            "scope": {
                "kind": "service"
            },
            "metricId": "transferred_bytes",
            "unit": "pct",
            "warn": {
                "value": 3,
                "sourceText": "+3%",
                "line": 22
            },
            "fail": null,
            "line": 22
        },
        "metricId": "transferred_bytes",
        "unit": "pct",
        "floor": {
            "status": "established",
            "metricId": "transferred_bytes",
            "unit": "bytes",
            "value": 7000,
            "sampleCount": 24,
            "scalingFactor": 1.2
        },
        "override": null,
        "status": "conforme",
        "observed": 0.2380952380952381,
        "headroom": 2.761904761904762,
        "withinNoise": false,
        "delta": {
            "metricId": "transferred_bytes",
            "unit": "bytes",
            "before": 840000,
            "after": 842000,
            "value": 2000,
            "floor": {
                "status": "established",
                "metricId": "transferred_bytes",
                "unit": "bytes",
                "value": 7000,
                "sampleCount": 24,
                "scalingFactor": 1.2
            },
            "classification": "no-significant-change"
        }
    },
    {
        "scenarioId": "/demarches/acte-naissance",
        "scenarioLabel": "/demarches/acte-naissance",
        "pass": "cold",
        "rule": {
            "kind": "relative",
            "scope": {
                "kind": "service"
            },
            "metricId": "transferred_bytes",
            "unit": "pct",
            "warn": {
                "value": 3,
                "sourceText": "+3%",
                "line": 22
            },
            "fail": null,
            "line": 22
        },
        "metricId": "transferred_bytes",
        "unit": "pct",
        "floor": {
            "status": "established",
            "metricId": "transferred_bytes",
            "unit": "bytes",
            "value": 7000,
            "sampleCount": 24,
            "scalingFactor": 1.2
        },
        "override": null,
        "status": "warn",
        "observed": 16.517055655296232,
        "headroom": -13.517055655296232,
        "withinNoise": false,
        "delta": {
            "metricId": "transferred_bytes",
            "unit": "bytes",
            "before": 1114000,
            "after": 1298000,
            "value": 184000,
            "floor": {
                "status": "established",
                "metricId": "transferred_bytes",
                "unit": "bytes",
                "value": 7000,
                "sampleCount": 24,
                "scalingFactor": 1.2
            },
            "classification": "regression"
        }
    },
    {
        "scenarioId": "demande-acte",
        "scenarioLabel": "journey: demande d'acte",
        "pass": "cold",
        "rule": {
            "kind": "relative",
            "scope": {
                "kind": "service"
            },
            "metricId": "transferred_bytes",
            "unit": "pct",
            "warn": {
                "value": 3,
                "sourceText": "+3%",
                "line": 22
            },
            "fail": null,
            "line": 22
        },
        "metricId": "transferred_bytes",
        "unit": "pct",
        "floor": {
            "status": "established",
            "metricId": "transferred_bytes",
            "unit": "bytes",
            "value": 7000,
            "sampleCount": 24,
            "scalingFactor": 1.2
        },
        "override": null,
        "status": "warn",
        "observed": 14.626391096979333,
        "headroom": -11.626391096979333,
        "withinNoise": false,
        "delta": {
            "metricId": "transferred_bytes",
            "unit": "bytes",
            "before": 1258000,
            "after": 1442000,
            "value": 184000,
            "floor": {
                "status": "established",
                "metricId": "transferred_bytes",
                "unit": "bytes",
                "value": 7000,
                "sampleCount": 24,
                "scalingFactor": 1.2
            },
            "classification": "regression"
        }
    }
],
    summary: {
    "conclusion": "failure",
    "counts": {
        "conforme": 6,
        "warn": 3,
        "breach": 1,
        "nonEvalue": 0
    },
    "blocking": [
        {
            "scenarioId": "demande-acte",
            "scenarioLabel": "journey: demande d'acte",
            "pass": "cold",
            "rule": {
                "kind": "absolute",
                "scope": {
                    "kind": "journey",
                    "journey": "demande-acte"
                },
                "metricId": "transferred_bytes",
                "unit": "bytes",
                "warn": null,
                "fail": {
                    "value": 1400000,
                    "sourceText": "1400KB",
                    "line": 19
                },
                "line": 19
            },
            "metricId": "transferred_bytes",
            "unit": "bytes",
            "floor": {
                "status": "established",
                "metricId": "transferred_bytes",
                "unit": "bytes",
                "value": 7000,
                "sampleCount": 24,
                "scalingFactor": 1.2
            },
            "override": null,
            "status": "breach",
            "observed": 1442000,
            "headroom": -42000,
            "withinNoise": false,
            "delta": null
        }
    ],
    "overridden": []
},
  },
  measurements: [
  {
    "scenarioId": "/accueil",
    "label": "/accueil",
    "baseBytes": 840000,
    "headBytes": 842000,
    "madBytes": 3000,
    "floorBytes": 7000
  },
  {
    "scenarioId": "/demarches/acte-naissance",
    "label": "/demarches/acte-naissance",
    "baseBytes": 1114000,
    "headBytes": 1298000,
    "madBytes": 9000,
    "floorBytes": 7000
  },
  {
    "scenarioId": "demande-acte",
    "label": "journey: demande d'acte",
    "baseBytes": 1258000,
    "headBytes": 1442000,
    "madBytes": 9000,
    "floorBytes": 7000
  }
],
};
