// generated by scripts/generate-carbon-canon.ts. do not edit by hand.
// run \`pnpm gen:carbon-canon\` to rebuild; carbon-canon.test.ts fails if this
// file and the generator ever disagree.
//
// every figure here was estimated by @balise/carbon-models from measurements
// the other canons publish. nothing in it is a number someone chose to look
// right, and nothing is averaged: the band is the energy models' own spread,
// and ecoindex sits beside it as the score and grade it publishes.
//
// METHODOLOGY.md 10.1 decides which models share the band. this file records
// which ones did.

import type { Assumption, GridIntensity } from '@balise/schemas';

export const carbonCanon = {
  grid: {"gCO2ePerKwh":56,"source":"declared-default","zone":"FR"} as GridIntensity,
  greenHosting: 1,
  hostingCheckedAt: "2026-08-15",
  referenceModelId: "swd",
  bandModelIds: ["swd","onebyte"],
  asideModelIds: ["ecoindex"],
  assumptions: [
  {
    "id": "ecoindex",
    "version": "0.1.0",
    "method": "score-derived",
    "assumptions": [
      {
        "id": "ecoindex-published-method",
        "textFr": "Tables de quantiles et formule issues de la méthode EcoIndex publiée (ecoindex.fr), conformes à l'implémentation de référence du CNUMR.",
        "textEn": "Quantile tables and formula from the published EcoIndex method (ecoindex.fr), matching the CNUMR reference implementation."
      },
      {
        "id": "ecoindex-ges-from-score",
        "textFr": "Le GES (gCO2e par page) dérive du seul score : 2 + 2 x (50 - score) / 100. Ni l'intensité du réseau électrique ni l'hébergement ne sont pris en compte.",
        "textEn": "GES (gCO2e per page) derives from the score alone: 2 + 2 x (50 - score) / 100. Grid intensity and hosting are not taken into account."
      },
      {
        "id": "ecoindex-size-unit",
        "textFr": "Le poids de page est interprété en kilooctets décimaux (1 Ko = 1000 octets).",
        "textEn": "Page weight is interpreted in decimal kilobytes (1 KB = 1000 bytes)."
      },
      {
        "id": "ecoindex-per-page",
        "textFr": "Valeur par page chargée à froid, sans modélisation du cache ni des visites répétées.",
        "textEn": "Per cold page load; no cache or return-visit modelling."
      }
    ]
  },
  {
    "id": "swd",
    "version": "0.1.0",
    "method": "energy",
    "assumptions": [
      {
        "id": "swd-published-constants",
        "textFr": "Constantes publiées du modèle Sustainable Web Design v4 (sustainablewebdesign.org) : énergie opérationnelle 0,055 / 0,059 / 0,080 kWh par Go (centre de données, réseau, terminal) et énergie intrinsèque 0,012 / 0,013 / 0,081 kWh par Go.",
        "textEn": "Published Sustainable Web Design v4 constants (sustainablewebdesign.org): operational energy 0.055 / 0.059 / 0.080 kWh per GB (data centre, network, device) and embodied energy 0.012 / 0.013 / 0.081 kWh per GB."
      },
      {
        "id": "swd-single-grid",
        "textFr": "Une seule intensité de réseau électrique est appliquée aux trois segments opérationnels : celle de la zone déclarée ou mesurée du visiteur.",
        "textEn": "A single grid intensity is applied to all three operational segments: the declared or measured visitor zone."
      },
      {
        "id": "swd-embodied-global",
        "textFr": "Les émissions intrinsèques sont calculées à l'intensité moyenne mondiale (494 gCO2e/kWh), conformément au modèle v4. Elles sont incluses dans la valeur.",
        "textEn": "Embodied emissions are computed at the global average intensity (494 gCO2e/kWh) per the v4 model, and are included in the value."
      },
      {
        "id": "swd-first-visit",
        "textFr": "Valeur pour une visite à froid, sans remise pour visiteurs récurrents ni cache. Les passes à froid et à chaud sont mesurées séparément.",
        "textEn": "Cold-visit figure; no return-visitor or cache discount. Cold and warm passes are measured separately."
      },
      {
        "id": "swd-green-hosting",
        "textFr": "Le facteur d'hébergement vert (0 à 1) réduit uniquement les émissions opérationnelles du centre de données.",
        "textEn": "The green hosting factor (0 to 1) reduces operational data centre emissions only."
      }
    ]
  },
  {
    "id": "onebyte",
    "version": "0.1.0",
    "method": "energy",
    "assumptions": [
      {
        "id": "onebyte-fixed-intensity",
        "textFr": "Intensités fixes issues de l'implémentation de référence : 519 gCO2e/kWh (centre de données, mix américain) et 475 gCO2e/kWh (réseau, moyenne mondiale AIE 2018). L'intensité réelle du réseau du visiteur n'est pas appliquée.",
        "textEn": "Fixed intensities from the reference implementation: 519 gCO2e/kWh (data centre, US mix) and 475 gCO2e/kWh (network, IEA 2018 global average). The visitor grid intensity is not applied."
      },
      {
        "id": "onebyte-no-device",
        "textFr": "L'énergie des terminaux est exclue du total calculé, comme dans l'implémentation de référence.",
        "textEn": "Device energy is excluded from the computed total, as in the reference implementation."
      },
      {
        "id": "onebyte-binary-green",
        "textFr": "Le modèle ne connaît qu'un hébergement vert binaire : il est considéré vert uniquement si le facteur d'hébergement vert vaut exactement 1.",
        "textEn": "The model only knows binary green hosting: it is treated as green only when the green hosting factor is exactly 1."
      },
      {
        "id": "onebyte-no-embodied",
        "textFr": "Aucune émission intrinsèque (fabrication) n'est incluse dans la valeur calculée.",
        "textEn": "No embodied (manufacturing) emissions are included in the computed value."
      },
      {
        "id": "onebyte-dated",
        "textFr": "Modèle ancien, conservé pour comparaison car encore cité par certains acheteurs.",
        "textEn": "Dated model, kept for comparison because some buyers still cite it."
      }
    ]
  }
] as ReadonlyArray<{
    id: string;
    version: string;
    method: 'energy' | 'score-derived';
    assumptions: readonly Assumption[];
  }>,
  pages: [
  {
    "id": "candidate",
    "label": "/demarches/acte-naissance",
    "metrics": {
      "transferredBytes": 1298000,
      "requestCount": 84,
      "domNodeCount": 2140
    },
    "band": {
      "low": 0.078072104,
      "high": 0.30108191666666667,
      "reference": 0.078072104,
      "modelCount": 2
    },
    "noise": {
      "low": 0.07762821176000001,
      "high": 0.07851599624,
      "floorBytes": 7380
    },
    "inBand": [
      {
        "id": "swd",
        "version": "0.1.0",
        "specVersion": "4.0",
        "method": "energy",
        "gridSensitive": true,
        "value": 0.078072104,
        "unit": "gCO2e",
        "low": null,
        "high": null,
        "score": null,
        "grade": null,
        "notes": [
          "operational grid 56 gCO2e/kWh (FR, declared-default)",
          "embodied at global average 494 gCO2e/kWh",
          "green hosting factor 1"
        ],
        "isReference": true
      },
      {
        "id": "onebyte",
        "version": "0.1.0",
        "specVersion": "2021",
        "method": "energy",
        "gridSensitive": false,
        "value": 0.30108191666666667,
        "unit": "gCO2e",
        "low": null,
        "high": null,
        "score": null,
        "grade": null,
        "notes": [
          "green data centre path"
        ],
        "isReference": false
      }
    ],
    "aside": [
      {
        "id": "ecoindex",
        "version": "0.1.0",
        "specVersion": "1.0",
        "method": "score-derived",
        "gridSensitive": false,
        "value": 2.4362984231154865,
        "unit": "gCO2e",
        "low": null,
        "high": null,
        "score": 28.185078844225686,
        "grade": "E",
        "notes": [
          "EcoIndex score 28.19 / 100, grade E"
        ],
        "isReference": false
      }
    ]
  },
  {
    "id": "baseline",
    "label": "/demarches/acte-naissance (référence)",
    "metrics": {
      "transferredBytes": 1114000,
      "requestCount": 82,
      "domNodeCount": 2118
    },
    "band": {
      "low": 0.06700487200000001,
      "high": 0.2584015833333333,
      "reference": 0.06700487200000001,
      "modelCount": 2
    },
    "noise": {
      "low": 0.06656097976,
      "high": 0.06744876424,
      "floorBytes": 7380
    },
    "inBand": [
      {
        "id": "swd",
        "version": "0.1.0",
        "specVersion": "4.0",
        "method": "energy",
        "gridSensitive": true,
        "value": 0.06700487200000001,
        "unit": "gCO2e",
        "low": null,
        "high": null,
        "score": null,
        "grade": null,
        "notes": [
          "operational grid 56 gCO2e/kWh (FR, declared-default)",
          "embodied at global average 494 gCO2e/kWh",
          "green hosting factor 1"
        ],
        "isReference": true
      },
      {
        "id": "onebyte",
        "version": "0.1.0",
        "specVersion": "2021",
        "method": "energy",
        "gridSensitive": false,
        "value": 0.2584015833333333,
        "unit": "gCO2e",
        "low": null,
        "high": null,
        "score": null,
        "grade": null,
        "notes": [
          "green data centre path"
        ],
        "isReference": false
      }
    ],
    "aside": [
      {
        "id": "ecoindex",
        "version": "0.1.0",
        "specVersion": "1.0",
        "method": "score-derived",
        "gridSensitive": false,
        "value": 2.4082472245132123,
        "unit": "gCO2e",
        "low": null,
        "high": null,
        "score": 29.587638774339382,
        "grade": "E",
        "notes": [
          "EcoIndex score 29.59 / 100, grade E"
        ],
        "isReference": false
      }
    ]
  },
  {
    "id": "dashboard",
    "label": "médiane du service",
    "metrics": {
      "transferredBytes": 1258000,
      "requestCount": 82,
      "domNodeCount": 2140
    },
    "band": {
      "low": 0.075666184,
      "high": 0.29180358333333334,
      "reference": 0.075666184,
      "modelCount": 2
    },
    "noise": {
      "low": 0.07522229176,
      "high": 0.07611007623999999,
      "floorBytes": 7380
    },
    "inBand": [
      {
        "id": "swd",
        "version": "0.1.0",
        "specVersion": "4.0",
        "method": "energy",
        "gridSensitive": true,
        "value": 0.075666184,
        "unit": "gCO2e",
        "low": null,
        "high": null,
        "score": null,
        "grade": null,
        "notes": [
          "operational grid 56 gCO2e/kWh (FR, declared-default)",
          "embodied at global average 494 gCO2e/kWh",
          "green hosting factor 1"
        ],
        "isReference": true
      },
      {
        "id": "onebyte",
        "version": "0.1.0",
        "specVersion": "2021",
        "method": "energy",
        "gridSensitive": false,
        "value": 0.29180358333333334,
        "unit": "gCO2e",
        "low": null,
        "high": null,
        "score": null,
        "grade": null,
        "notes": [
          "green data centre path"
        ],
        "isReference": false
      }
    ],
    "aside": [
      {
        "id": "ecoindex",
        "version": "0.1.0",
        "specVersion": "1.0",
        "method": "score-derived",
        "gridSensitive": false,
        "value": 2.424253820797123,
        "unit": "gCO2e",
        "low": null,
        "high": null,
        "score": 28.787308960143847,
        "grade": "E",
        "notes": [
          "EcoIndex score 28.79 / 100, grade E"
        ],
        "isReference": false
      }
    ]
  },
  {
    "id": "scan",
    "label": "bibliotheques-selo.fr",
    "metrics": {
      "transferredBytes": 980000,
      "requestCount": 61,
      "domNodeCount": 1830
    },
    "band": {
      "low": 0.05894504,
      "high": 0.22731916666666666,
      "reference": 0.05894504,
      "modelCount": 2
    },
    "noise": null,
    "inBand": [
      {
        "id": "swd",
        "version": "0.1.0",
        "specVersion": "4.0",
        "method": "energy",
        "gridSensitive": true,
        "value": 0.05894504,
        "unit": "gCO2e",
        "low": null,
        "high": null,
        "score": null,
        "grade": null,
        "notes": [
          "operational grid 56 gCO2e/kWh (FR, declared-default)",
          "embodied at global average 494 gCO2e/kWh",
          "green hosting factor 1"
        ],
        "isReference": true
      },
      {
        "id": "onebyte",
        "version": "0.1.0",
        "specVersion": "2021",
        "method": "energy",
        "gridSensitive": false,
        "value": 0.22731916666666666,
        "unit": "gCO2e",
        "low": null,
        "high": null,
        "score": null,
        "grade": null,
        "notes": [
          "green data centre path"
        ],
        "isReference": false
      }
    ],
    "aside": [
      {
        "id": "ecoindex",
        "version": "0.1.0",
        "specVersion": "1.0",
        "method": "score-derived",
        "gridSensitive": false,
        "value": 2.2803131721664007,
        "unit": "gCO2e",
        "low": null,
        "high": null,
        "score": 35.984341391679976,
        "grade": "E",
        "notes": [
          "EcoIndex score 35.98 / 100, grade E"
        ],
        "isReference": false
      }
    ]
  }
],
} as const;

export type CarbonPage = (typeof carbonCanon.pages)[number];
export type CarbonModelOutput = CarbonPage['inBand'][number];
