// generated by scripts/generate-corpus-canon.ts. do not edit by hand.
// run `pnpm gen:corpus-canon` to rebuild; corpus-canon.test.ts fails if this
// file and the generator ever disagree.
//
// the twelve services the fleet and the public index compare. every rank,
// every grade, every trend and every bucket below was computed from the
// captures in capture-canon-source.ts through @balise/measure-core and
// @balise/carbon-models. nothing here is a position typed beside a row.

import type { CorpusCanon } from '../../scripts/corpus-canon-source';

export const corpusCanon = {
  "rankMetric": "transferred_bytes",
  "declarationDueDays": 270,
  "declarationExpiredDays": 365,
  "scale": {
    "min": 0,
    "max": 1.2848118339999999
  },
  "size": 12,
  "withoutDeclaration": 2,
  "hostingVerified": 5,
  "hostingUnchecked": 4,
  "benchmark": {
    "min": 0,
    "max": 4418000,
    "buckets": [
      {
        "from": 0,
        "to": 552250,
        "count": 3
      },
      {
        "from": 552250,
        "to": 1104500,
        "count": 4
      },
      {
        "from": 1104500,
        "to": 1656750,
        "count": 2
      },
      {
        "from": 1656750,
        "to": 2209000,
        "count": 1
      },
      {
        "from": 2209000,
        "to": 2761250,
        "count": 0
      },
      {
        "from": 2761250,
        "to": 3313500,
        "count": 1
      },
      {
        "from": 3313500,
        "to": 3865750,
        "count": 0
      },
      {
        "from": 3865750,
        "to": 4418000,
        "count": 1
      }
    ],
    "median": 911000,
    "serviceCount": 12
  },
  "rows": [
    {
      "domain": "craonnais.fr",
      "organisme": "Ville de Craonnais",
      "sector": "communes",
      "agency": "Sextant",
      "inFleet": true,
      "contract": null,
      "rgesnPct": 82,
      "scenarioId": "corpus:craonnais.fr",
      "measured": {
        "transferredBytes": 210000,
        "requestCount": 18,
        "domNodeCount": 300,
        "thirdPartySharePct": 5.714285714285714
      },
      "confidence": "high",
      "sampleCount": 5,
      "carbon": {
        "reference": 0.012631080000000001,
        "low": 0.012631080000000001,
        "high": 0.04871125,
        "modelCount": 2,
        "noise": {
          "low": 0.012522326401199999,
          "high": 0.012739833598799998
        },
        "score": 81.60541192396423,
        "grade": "A",
        "gradeTone": "none"
      },
      "weight": {
        "percentile": 11.86752845621461,
        "tone": "none"
      },
      "trend": {
        "before": 244000,
        "after": 210000,
        "pct": -13.934426229508196,
        "classification": "improvement"
      },
      "declaration": {
        "state": "current",
        "version": 4,
        "ageDays": 21
      },
      "hosting": {
        "state": "verified",
        "checkedAt": "2026-08-15"
      },
      "rank": 1
    },
    {
      "domain": "mairie-lanvaux.fr",
      "organisme": "Commune de Lanvaux",
      "sector": "communes",
      "agency": null,
      "inFleet": false,
      "contract": null,
      "rgesnPct": null,
      "scenarioId": "corpus:mairie-lanvaux.fr",
      "measured": {
        "transferredBytes": 318000,
        "requestCount": 26,
        "domNodeCount": 520,
        "thirdPartySharePct": 3.7735849056603774
      },
      "confidence": "high",
      "sampleCount": 5,
      "carbon": {
        "reference": 0.020106504,
        "low": 0.020106504,
        "high": 0.09247853399999999,
        "modelCount": 2,
        "noise": {
          "low": 0.01993338700056,
          "high": 0.02027962099944
        },
        "score": 70.51882892500898,
        "grade": "B",
        "gradeTone": "none"
      },
      "weight": {
        "percentile": 14.95624320768747,
        "tone": "none"
      },
      "trend": {
        "before": 316000,
        "after": 318000,
        "pct": 0.6329113924050633,
        "classification": "no-significant-change"
      },
      "declaration": {
        "state": "expired",
        "version": 1,
        "ageDays": 402
      },
      "hosting": {
        "state": "unchecked",
        "checkedAt": null
      },
      "rank": 2
    },
    {
      "domain": "ville-de-plessac.fr",
      "organisme": "Commune de Plessac",
      "sector": "communes",
      "agency": null,
      "inFleet": false,
      "contract": null,
      "rgesnPct": null,
      "scenarioId": "corpus:ville-de-plessac.fr",
      "measured": {
        "transferredBytes": 402000,
        "requestCount": 34,
        "domNodeCount": 780,
        "thirdPartySharePct": 10.945273631840797
      },
      "confidence": "high",
      "sampleCount": 5,
      "carbon": {
        "reference": 0.025417656000000004,
        "low": 0.025417656000000004,
        "high": 0.11690682599999999,
        "modelCount": 2,
        "noise": {
          "low": 0.025198809981839994,
          "high": 0.02563650201816
        },
        "score": 59.653614081160505,
        "grade": "C",
        "gradeTone": "none"
      },
      "weight": {
        "percentile": 17.578315513036955,
        "tone": "none"
      },
      "trend": {
        "before": 404000,
        "after": 402000,
        "pct": -0.49504950495049505,
        "classification": "no-significant-change"
      },
      "declaration": {
        "state": "due",
        "version": 1,
        "ageDays": 311
      },
      "hosting": {
        "state": "unchecked",
        "checkedAt": null
      },
      "rank": 3
    },
    {
      "domain": "musees-selo.fr",
      "organisme": "Musées de Sèvre-et-Loire",
      "sector": "epci",
      "agency": "Kerlann",
      "inFleet": false,
      "contract": null,
      "rgesnPct": null,
      "scenarioId": "corpus:musees-selo.fr",
      "measured": {
        "transferredBytes": 604000,
        "requestCount": 44,
        "domNodeCount": 1240,
        "thirdPartySharePct": 8.940397350993377
      },
      "confidence": "high",
      "sampleCount": 5,
      "carbon": {
        "reference": 0.036329392,
        "low": 0.036329392,
        "high": 0.14010283333333332,
        "modelCount": 2,
        "noise": {
          "low": 0.03601659593488,
          "high": 0.036642188065120006
        },
        "score": 47.142857248342146,
        "grade": "D",
        "gradeTone": "caution"
      },
      "weight": {
        "percentile": 24.08301095010163,
        "tone": "none"
      },
      "trend": {
        "before": 588000,
        "after": 604000,
        "pct": 2.7210884353741496,
        "classification": "regression"
      },
      "declaration": {
        "state": "current",
        "version": 3,
        "ageDays": 64
      },
      "hosting": {
        "state": "verified",
        "checkedAt": "2026-08-12"
      },
      "rank": 4
    },
    {
      "domain": "prefecture-arvor.fr",
      "organisme": "Préfecture d'Arvor",
      "sector": "etat",
      "agency": null,
      "inFleet": false,
      "contract": null,
      "rgesnPct": null,
      "scenarioId": "corpus:prefecture-arvor.fr",
      "measured": {
        "transferredBytes": 712000,
        "requestCount": 48,
        "domNodeCount": 1486,
        "thirdPartySharePct": 5.056179775280898
      },
      "confidence": "high",
      "sampleCount": 5,
      "carbon": {
        "reference": 0.045018336,
        "low": 0.045018336,
        "high": 0.20705885599999999,
        "modelCount": 2,
        "noise": {
          "low": 0.04463072812704,
          "high": 0.04540594387295999
        },
        "score": 42.93358946371941,
        "grade": "D",
        "gradeTone": "caution"
      },
      "weight": {
        "percentile": 27.64282411993924,
        "tone": "none"
      },
      "trend": {
        "before": 716000,
        "after": 712000,
        "pct": -0.5586592178770949,
        "classification": "no-significant-change"
      },
      "declaration": {
        "state": "current",
        "version": 2,
        "ageDays": 178
      },
      "hosting": {
        "state": "standard",
        "checkedAt": "2026-08-15"
      },
      "rank": 5
    },
    {
      "domain": "sevre-et-loire.fr",
      "organisme": "Métropole de Sèvre-et-Loire",
      "sector": "epci",
      "agency": "Sextant",
      "inFleet": true,
      "contract": "0417 · Q3 due",
      "rgesnPct": null,
      "scenarioId": "corpus:sevre-et-loire.fr",
      "measured": {
        "transferredBytes": 842000,
        "requestCount": 52,
        "domNodeCount": 1620,
        "thirdPartySharePct": 8.788598574821853
      },
      "confidence": "high",
      "sampleCount": 5,
      "carbon": {
        "reference": 0.050644616,
        "low": 0.050644616,
        "high": 0.19530891666666667,
        "modelCount": 2,
        "noise": {
          "low": 0.050208565856240006,
          "high": 0.05108066614376
        },
        "score": 40.29269385364012,
        "grade": "D",
        "gradeTone": "caution"
      },
      "weight": {
        "percentile": 31.896719083673077,
        "tone": "none"
      },
      "trend": {
        "before": 925000,
        "after": 842000,
        "pct": -8.972972972972974,
        "classification": "improvement"
      },
      "declaration": {
        "state": "current",
        "version": 2,
        "ageDays": 156
      },
      "hosting": {
        "state": "verified",
        "checkedAt": "2026-08-15"
      },
      "rank": 6
    },
    {
      "domain": "bibliotheques-selo.fr",
      "organisme": "Réseau des bibliothèques de Sèvre-et-Loire",
      "sector": "communes",
      "agency": "Sextant",
      "inFleet": true,
      "contract": null,
      "rgesnPct": 71,
      "scenarioId": "corpus:bibliotheques-selo.fr",
      "measured": {
        "transferredBytes": 980000,
        "requestCount": 61,
        "domNodeCount": 1830,
        "thirdPartySharePct": 5.1020408163265305
      },
      "confidence": "high",
      "sampleCount": 5,
      "carbon": {
        "reference": 0.05894504,
        "low": 0.05894504,
        "high": 0.22731916666666666,
        "modelCount": 2,
        "noise": {
          "low": 0.0584375232056,
          "high": 0.05945255679440001
        },
        "score": 35.984341391679976,
        "grade": "E",
        "gradeTone": "caution"
      },
      "weight": {
        "percentile": 36.30950158670898,
        "tone": "none"
      },
      "trend": {
        "before": 962000,
        "after": 980000,
        "pct": 1.8711018711018712,
        "classification": "regression"
      },
      "declaration": {
        "state": "none",
        "version": null,
        "ageDays": null
      },
      "hosting": {
        "state": "verified",
        "checkedAt": "2026-08-15"
      },
      "rank": 7
    },
    {
      "domain": "eau-selo.fr",
      "organisme": "Régie des eaux de Sèvre-et-Loire",
      "sector": "epci",
      "agency": "Sextant",
      "inFleet": true,
      "contract": null,
      "rgesnPct": 64,
      "scenarioId": "corpus:eau-selo.fr",
      "measured": {
        "transferredBytes": 1246000,
        "requestCount": 58,
        "domNodeCount": 1410,
        "thirdPartySharePct": 41.091492776886035
      },
      "confidence": "high",
      "sampleCount": 5,
      "carbon": {
        "reference": 0.074944408,
        "low": 0.074944408,
        "high": 0.28902008333333334,
        "modelCount": 2,
        "noise": {
          "low": 0.07429913664712,
          "high": 0.07558967935288001
        },
        "score": 38.50618769160874,
        "grade": "E",
        "gradeTone": "caution"
      },
      "weight": {
        "percentile": 44.41654180401559,
        "tone": "none"
      },
      "trend": {
        "before": 1088000,
        "after": 1246000,
        "pct": 14.522058823529413,
        "classification": "regression"
      },
      "declaration": {
        "state": "current",
        "version": 2,
        "ageDays": 88
      },
      "hosting": {
        "state": "verified",
        "checkedAt": "2026-08-15"
      },
      "rank": 8
    },
    {
      "domain": "ars-bretagne.fr",
      "organisme": "ARS Bretagne",
      "sector": "etat",
      "agency": null,
      "inFleet": false,
      "contract": null,
      "rgesnPct": null,
      "scenarioId": "corpus:ars-bretagne.fr",
      "measured": {
        "transferredBytes": 1588000,
        "requestCount": 74,
        "domNodeCount": 2260,
        "thirdPartySharePct": 5.289672544080604
      },
      "confidence": "high",
      "sampleCount": 5,
      "carbon": {
        "reference": 0.100406064,
        "low": 0.100406064,
        "high": 0.46181104399999995,
        "modelCount": 2,
        "noise": {
          "low": 0.09954156778896,
          "high": 0.10127056021103999
        },
        "score": 28.558709920843043,
        "grade": "E",
        "gradeTone": "caution"
      },
      "weight": {
        "percentile": 53.49287321830458,
        "tone": "caution"
      },
      "trend": {
        "before": 1624000,
        "after": 1588000,
        "pct": -2.2167487684729066,
        "classification": "improvement"
      },
      "declaration": {
        "state": "due",
        "version": 1,
        "ageDays": 290
      },
      "hosting": {
        "state": "unchecked",
        "checkedAt": null
      },
      "rank": 9
    },
    {
      "domain": "transports-selo.fr",
      "organisme": "Réseau Naïade",
      "sector": "transport",
      "agency": "Sextant",
      "inFleet": true,
      "contract": "0392 · active",
      "rgesnPct": 44,
      "scenarioId": "corpus:transports-selo.fr",
      "measured": {
        "transferredBytes": 2184000,
        "requestCount": 96,
        "domNodeCount": 3140,
        "thirdPartySharePct": 22.71062271062271
      },
      "confidence": "high",
      "sampleCount": 5,
      "carbon": {
        "reference": 0.13808995200000002,
        "low": 0.13808995200000002,
        "high": 0.6351355919999999,
        "modelCount": 2,
        "noise": {
          "low": 0.13690099751328003,
          "high": 0.13927890648671998
        },
        "score": 21.389108605419736,
        "grade": "F",
        "gradeTone": "breach"
      },
      "weight": {
        "percentile": 65.64860350746962,
        "tone": "caution"
      },
      "trend": {
        "before": 1805000,
        "after": 2184000,
        "pct": 20.997229916897506,
        "classification": "regression"
      },
      "declaration": {
        "state": "current",
        "version": 1,
        "ageDays": 248
      },
      "hosting": {
        "state": "standard",
        "checkedAt": "2026-08-15"
      },
      "rank": 10
    },
    {
      "domain": "chu-armorique.fr",
      "organisme": "CHU d'Armorique",
      "sector": "sante",
      "agency": "Sextant",
      "inFleet": true,
      "contract": null,
      "rgesnPct": 38,
      "scenarioId": "corpus:chu-armorique.fr",
      "measured": {
        "transferredBytes": 3062000,
        "requestCount": 118,
        "domNodeCount": 4620,
        "thirdPartySharePct": 7.250163291966036
      },
      "confidence": "low",
      "sampleCount": 5,
      "carbon": {
        "reference": 0.193604136,
        "low": 0.193604136,
        "high": 0.8904694059999999,
        "modelCount": 2,
        "noise": null,
        "score": 16.224768376984073,
        "grade": "F",
        "gradeTone": "breach"
      },
      "weight": {
        "percentile": 76.82792183530115,
        "tone": "breach"
      },
      "trend": {
        "before": 2980000,
        "after": 3062000,
        "pct": 2.7516778523489935,
        "classification": "indeterminate"
      },
      "declaration": {
        "state": "expired",
        "version": 1,
        "ageDays": 426
      },
      "hosting": {
        "state": "standard",
        "checkedAt": "2026-08-15"
      },
      "rank": 11
    },
    {
      "domain": "portail-arvor.fr",
      "organisme": "Département d'Arvor",
      "sector": "departements",
      "agency": null,
      "inFleet": false,
      "contract": null,
      "rgesnPct": null,
      "scenarioId": "corpus:portail-arvor.fr",
      "measured": {
        "transferredBytes": 4418000,
        "requestCount": 142,
        "domNodeCount": 6180,
        "thirdPartySharePct": 7.424173834314169
      },
      "confidence": "high",
      "sampleCount": 5,
      "carbon": {
        "reference": 0.279341304,
        "low": 0.279341304,
        "high": 1.2848118339999999,
        "modelCount": 2,
        "noise": {
          "low": 0.2769361753725601,
          "high": 0.2817464326274399
        },
        "score": 11.965596180341663,
        "grade": "F",
        "gradeTone": "breach"
      },
      "weight": {
        "percentile": 86.05384337204163,
        "tone": "breach"
      },
      "trend": {
        "before": 3297000,
        "after": 4418000,
        "pct": 34.00060661207158,
        "classification": "regression"
      },
      "declaration": {
        "state": "none",
        "version": null,
        "ageDays": null
      },
      "hosting": {
        "state": "unchecked",
        "checkedAt": null
      },
      "rank": 12
    }
  ]
} as unknown as CorpusCanon;
