// generated by scripts/generate-engagement-canon.ts. do not edit by hand.
// run `pnpm gen:engagement-canon` to rebuild; engagement-canon.test.ts fails
// if this file and the generator ever disagree.
//
// the contractual engagements, once. the tender proposes them, the contract
// carries the ones that were signed, and the execution report reports on those.
// the only authored parts are the wording each carries into the annexe and the
// threshold the supplier signs; every margin, status, gauge and trend below is
// derived from what was measured.

import type { EngagementCanon } from '../../scripts/engagement-canon-source';

export const engagementCanon = {
  "referenceModelId": "swd",
  "periodsElapsed": 1,
  "reportsDelivered": 2,
  "headroomDefinitionFr": "Marge = (seuil - valeur mesurée) / seuil. Le dénominateur est le seuil signé, jamais la valeur mesurée.",
  "engagements": [
    {
      "id": "page-weight",
      "labelFr": "Poids médian des 10 pages principales",
      "basis": {
        "kind": "metric",
        "aggregationId": "service",
        "metricId": "transferred_bytes"
      },
      "threshold": 1400000,
      "direction": "lte",
      "unit": "bytes",
      "inOffer": true,
      "measured": {
        "value": 1258000,
        "confidence": "high",
        "mad": 6000,
        "band": null,
        "model": null
      },
      "margin": {
        "kind": "headroom",
        "pct": 10.142857142857142
      },
      "status": "tenu",
      "gaugePct": 89.85714285714286,
      "history": [
        1258000,
        1258000,
        1258000,
        1258000,
        1258000,
        1258000,
        1258000,
        1258000,
        1258000,
        1258000,
        1258000,
        1258000,
        1258000,
        1258000,
        1258000,
        1258000,
        1258000,
        1258000,
        1258000,
        1258000,
        1258000,
        1258000,
        1258000,
        1258000
      ],
      "trend": {
        "classification": "no-significant-change",
        "before": 1258000,
        "after": 1258000,
        "periods": 24
      }
    },
    {
      "id": "carbon-per-visit",
      "labelFr": "Empreinte estimée par visite (SWD v4)",
      "basis": {
        "kind": "carbon",
        "pageId": "dashboard",
        "aggregationId": "service"
      },
      "threshold": 0.1,
      "direction": "lte",
      "unit": "gCO2e",
      "inOffer": true,
      "measured": {
        "value": 0.075666184,
        "confidence": "high",
        "mad": null,
        "band": {
          "low": 0.075666184,
          "high": 0.29180358333333334,
          "modelCount": 2
        },
        "model": {
          "id": "swd",
          "version": "0.1.0"
        }
      },
      "margin": {
        "kind": "headroom",
        "pct": 24.33381600000001
      },
      "status": "tenu",
      "gaugePct": 75.66618399999999,
      "history": [
        0.075666184,
        0.075666184,
        0.075666184,
        0.075666184,
        0.075666184,
        0.075666184,
        0.075666184,
        0.075666184,
        0.075666184,
        0.075666184,
        0.075666184,
        0.075666184,
        0.075666184,
        0.075666184,
        0.075666184,
        0.075666184,
        0.075666184,
        0.075666184,
        0.075666184,
        0.075666184,
        0.075666184,
        0.075666184,
        0.075666184,
        0.075666184
      ],
      "trend": {
        "classification": "no-significant-change",
        "before": 1258000,
        "after": 1258000,
        "periods": 24
      }
    },
    {
      "id": "rgesn-conformity",
      "labelFr": "Taux de conformité RGESN à 12 mois",
      "basis": {
        "kind": "conformity"
      },
      "threshold": 75,
      "direction": "gte",
      "unit": "pct",
      "inOffer": true,
      "measured": {
        "value": 58.57142857142858,
        "confidence": null,
        "mad": null,
        "band": null,
        "model": null
      },
      "margin": {
        "kind": "stretch",
        "points": 16.428571428571423
      },
      "status": "enCours",
      "gaugePct": 78.0952380952381,
      "history": null,
      "trend": null
    },
    {
      "id": "quarterly-report",
      "labelFr": "Rapport d'exécution trimestriel horodaté",
      "basis": {
        "kind": "process"
      },
      "threshold": 4,
      "direction": "gte",
      "unit": "count",
      "inOffer": true,
      "measured": {
        "value": 2,
        "confidence": null,
        "mad": null,
        "band": null,
        "model": null
      },
      "margin": {
        "kind": "process"
      },
      "status": "tenu",
      "gaugePct": 50,
      "history": null,
      "trend": null
    },
    {
      "id": "third-party-share",
      "labelFr": "Part des tiers dans les octets transférés",
      "basis": {
        "kind": "metric",
        "aggregationId": "service",
        "metricId": "third_party_share_pct"
      },
      "threshold": 30,
      "direction": "lte",
      "unit": "pct",
      "inOffer": false,
      "measured": {
        "value": 37.99682034976153,
        "confidence": "high",
        "mad": 0.5230583026414735,
        "band": null,
        "model": null
      },
      "margin": {
        "kind": "notMet",
        "points": 7.996820349761528
      },
      "status": null,
      "gaugePct": null,
      "history": [
        37.99682034976153,
        37.99682034976153,
        37.99682034976153,
        37.99682034976153,
        37.99682034976153,
        37.99682034976153,
        37.99682034976153,
        37.99682034976153,
        37.99682034976153,
        37.99682034976153,
        37.99682034976153,
        37.99682034976153,
        37.99682034976153,
        37.99682034976153,
        37.99682034976153,
        37.99682034976153,
        37.99682034976153,
        37.99682034976153,
        37.99682034976153,
        37.99682034976153,
        37.99682034976153,
        37.99682034976153,
        37.99682034976153,
        37.99682034976153
      ],
      "trend": {
        "classification": "no-significant-change",
        "before": 37.99682034976153,
        "after": 37.99682034976153,
        "periods": 24
      }
    }
  ],
  "offered": [
    {
      "id": "page-weight",
      "labelFr": "Poids médian des 10 pages principales",
      "basis": {
        "kind": "metric",
        "aggregationId": "service",
        "metricId": "transferred_bytes"
      },
      "threshold": 1400000,
      "direction": "lte",
      "unit": "bytes",
      "inOffer": true,
      "measured": {
        "value": 1258000,
        "confidence": "high",
        "mad": 6000,
        "band": null,
        "model": null
      },
      "margin": {
        "kind": "headroom",
        "pct": 10.142857142857142
      },
      "status": "tenu",
      "gaugePct": 89.85714285714286,
      "history": [
        1258000,
        1258000,
        1258000,
        1258000,
        1258000,
        1258000,
        1258000,
        1258000,
        1258000,
        1258000,
        1258000,
        1258000,
        1258000,
        1258000,
        1258000,
        1258000,
        1258000,
        1258000,
        1258000,
        1258000,
        1258000,
        1258000,
        1258000,
        1258000
      ],
      "trend": {
        "classification": "no-significant-change",
        "before": 1258000,
        "after": 1258000,
        "periods": 24
      }
    },
    {
      "id": "carbon-per-visit",
      "labelFr": "Empreinte estimée par visite (SWD v4)",
      "basis": {
        "kind": "carbon",
        "pageId": "dashboard",
        "aggregationId": "service"
      },
      "threshold": 0.1,
      "direction": "lte",
      "unit": "gCO2e",
      "inOffer": true,
      "measured": {
        "value": 0.075666184,
        "confidence": "high",
        "mad": null,
        "band": {
          "low": 0.075666184,
          "high": 0.29180358333333334,
          "modelCount": 2
        },
        "model": {
          "id": "swd",
          "version": "0.1.0"
        }
      },
      "margin": {
        "kind": "headroom",
        "pct": 24.33381600000001
      },
      "status": "tenu",
      "gaugePct": 75.66618399999999,
      "history": [
        0.075666184,
        0.075666184,
        0.075666184,
        0.075666184,
        0.075666184,
        0.075666184,
        0.075666184,
        0.075666184,
        0.075666184,
        0.075666184,
        0.075666184,
        0.075666184,
        0.075666184,
        0.075666184,
        0.075666184,
        0.075666184,
        0.075666184,
        0.075666184,
        0.075666184,
        0.075666184,
        0.075666184,
        0.075666184,
        0.075666184,
        0.075666184
      ],
      "trend": {
        "classification": "no-significant-change",
        "before": 1258000,
        "after": 1258000,
        "periods": 24
      }
    },
    {
      "id": "rgesn-conformity",
      "labelFr": "Taux de conformité RGESN à 12 mois",
      "basis": {
        "kind": "conformity"
      },
      "threshold": 75,
      "direction": "gte",
      "unit": "pct",
      "inOffer": true,
      "measured": {
        "value": 58.57142857142858,
        "confidence": null,
        "mad": null,
        "band": null,
        "model": null
      },
      "margin": {
        "kind": "stretch",
        "points": 16.428571428571423
      },
      "status": "enCours",
      "gaugePct": 78.0952380952381,
      "history": null,
      "trend": null
    },
    {
      "id": "quarterly-report",
      "labelFr": "Rapport d'exécution trimestriel horodaté",
      "basis": {
        "kind": "process"
      },
      "threshold": 4,
      "direction": "gte",
      "unit": "count",
      "inOffer": true,
      "measured": {
        "value": 2,
        "confidence": null,
        "mad": null,
        "band": null,
        "model": null
      },
      "margin": {
        "kind": "process"
      },
      "status": "tenu",
      "gaugePct": 50,
      "history": null,
      "trend": null
    }
  ],
  "proposedOnly": [
    {
      "id": "third-party-share",
      "labelFr": "Part des tiers dans les octets transférés",
      "basis": {
        "kind": "metric",
        "aggregationId": "service",
        "metricId": "third_party_share_pct"
      },
      "threshold": 30,
      "direction": "lte",
      "unit": "pct",
      "inOffer": false,
      "measured": {
        "value": 37.99682034976153,
        "confidence": "high",
        "mad": 0.5230583026414735,
        "band": null,
        "model": null
      },
      "margin": {
        "kind": "notMet",
        "points": 7.996820349761528
      },
      "status": null,
      "gaugePct": null,
      "history": [
        37.99682034976153,
        37.99682034976153,
        37.99682034976153,
        37.99682034976153,
        37.99682034976153,
        37.99682034976153,
        37.99682034976153,
        37.99682034976153,
        37.99682034976153,
        37.99682034976153,
        37.99682034976153,
        37.99682034976153,
        37.99682034976153,
        37.99682034976153,
        37.99682034976153,
        37.99682034976153,
        37.99682034976153,
        37.99682034976153,
        37.99682034976153,
        37.99682034976153,
        37.99682034976153,
        37.99682034976153,
        37.99682034976153,
        37.99682034976153
      ],
      "trend": {
        "classification": "no-significant-change",
        "before": 37.99682034976153,
        "after": 37.99682034976153,
        "periods": 24
      }
    }
  ]
} as unknown as EngagementCanon;
