// generated by scripts/generate-findings-canon.ts. do not edit by hand.
// run `pnpm gen:findings-canon` to rebuild; findings-canon.test.ts fails if
// this file and the generator ever disagree.
//
// every finding below was raised by @balise/measure-core from the capture the
// same run publishes. each one is a quantity that capture holds, or a position
// in the reference distribution ecoindex publishes. none of them is a saving:
// what a page would weigh in another format is a counterfactual about a page
// nobody measured, and this product does not state one.

import type { FindingsResult, ReferencePosition } from '@balise/measure-core';

export const findingsCanon = {
  thresholds: {
  "unusedDecodedShare": {
    "caution": 0.4,
    "breach": 0.6
  },
  "thirdPartyShare": {
    "caution": 0.2,
    "breach": 0.35
  },
  "imageShare": {
    "caution": 0.5,
    "breach": 0.65
  },
  "fontShare": {
    "caution": 0.1,
    "breach": 0.2
  },
  "singleResourceShare": {
    "caution": 0.15,
    "breach": 0.25
  },
  "referencePercentile": {
    "caution": 50,
    "breach": 75
  },
  "minimumBytes": 50000
},
  referenceSource: {"id":"ecoindex","specVersion":"1.0"},
  pages: {
  "scan": {
    "aggregationId": "scan",
    "reference": [
      {
        "metricId": "dom_node_count",
        "source": "ecoindex",
        "sourceVersion": "1.0",
        "percentile": 90.21386430678466,
        "value": 1830
      },
      {
        "metricId": "request_count",
        "source": "ecoindex",
        "sourceVersion": "1.0",
        "percentile": 38.57142857142858,
        "value": 61
      },
      {
        "metricId": "transferred_bytes",
        "source": "ecoindex",
        "sourceVersion": "1.0",
        "percentile": 36.30950158670898,
        "value": 980000
      }
    ],
    "result": {
      "findings": [
        {
          "id": "image-weight",
          "severity": "breach",
          "value": 650000,
          "unit": "bytes",
          "share": {
            "value": 0.6632653061224489,
            "basis": "page-transferred-bytes"
          },
          "contributorCount": 46,
          "unavailableCount": 0,
          "evidence": [
            {
              "url": "https://bibliotheques-selo.fr/wp-content/uploads/2019/04/bandeau-bibliotheque.png",
              "resourceType": "image",
              "transferredBytes": 258000,
              "decodedBytes": 258000,
              "unusedDecodedBytes": null
            },
            {
              "url": "https://bibliotheques-selo.fr/wp-content/uploads/2026/08/actualite-rentree.png",
              "resourceType": "image",
              "transferredBytes": 92000,
              "decodedBytes": 92000,
              "unusedDecodedBytes": null
            },
            {
              "url": "https://bibliotheques-selo.fr/wp-content/uploads/2026/08/actualite-club-lecture.png",
              "resourceType": "image",
              "transferredBytes": 84000,
              "decodedBytes": 84000,
              "unusedDecodedBytes": null
            }
          ],
          "reference": null
        },
        {
          "id": "heaviest-resource",
          "severity": "breach",
          "value": 258000,
          "unit": "bytes",
          "share": {
            "value": 0.26326530612244897,
            "basis": "page-transferred-bytes"
          },
          "contributorCount": 1,
          "unavailableCount": 0,
          "evidence": [
            {
              "url": "https://bibliotheques-selo.fr/wp-content/uploads/2019/04/bandeau-bibliotheque.png",
              "resourceType": "image",
              "transferredBytes": 258000,
              "decodedBytes": 258000,
              "unusedDecodedBytes": null
            }
          ],
          "reference": null
        },
        {
          "id": "reference-dom-node-count",
          "severity": "breach",
          "value": 1830,
          "unit": "count",
          "share": null,
          "contributorCount": 0,
          "unavailableCount": 0,
          "evidence": [],
          "reference": {
            "metricId": "dom_node_count",
            "source": "ecoindex",
            "sourceVersion": "1.0",
            "percentile": 90.21386430678466,
            "value": 1830
          }
        },
        {
          "id": "font-weight",
          "severity": "caution",
          "value": 102000,
          "unit": "bytes",
          "share": {
            "value": 0.10408163265306122,
            "basis": "page-transferred-bytes"
          },
          "contributorCount": 6,
          "unavailableCount": 0,
          "evidence": [
            {
              "url": "https://bibliotheques-selo.fr/wp-content/themes/selo/fonts/opensans-regular.woff",
              "resourceType": "font",
              "transferredBytes": 17000,
              "decodedBytes": 17000,
              "unusedDecodedBytes": null
            },
            {
              "url": "https://bibliotheques-selo.fr/wp-content/themes/selo/fonts/opensans-bold.woff",
              "resourceType": "font",
              "transferredBytes": 17000,
              "decodedBytes": 17000,
              "unusedDecodedBytes": null
            },
            {
              "url": "https://bibliotheques-selo.fr/wp-content/themes/selo/fonts/opensans-italic.woff",
              "resourceType": "font",
              "transferredBytes": 17000,
              "decodedBytes": 17000,
              "unusedDecodedBytes": null
            }
          ],
          "reference": null
        }
      ],
      "withheld": [
        {
          "id": "unused-script-bytes",
          "reason": "coverage-not-captured",
          "contributorCount": 5
        },
        {
          "id": "unused-stylesheet-bytes",
          "reason": "coverage-not-captured",
          "contributorCount": 3
        }
      ],
      "totalTransferredBytes": 980000
    }
  },
  "candidate": {
    "aggregationId": "candidate",
    "reference": [
      {
        "metricId": "dom_node_count",
        "source": "ecoindex",
        "sourceVersion": "1.0",
        "percentile": 92.5,
        "value": 2140
      },
      {
        "metricId": "request_count",
        "source": "ecoindex",
        "sourceVersion": "1.0",
        "percentile": 53.75,
        "value": 84
      },
      {
        "metricId": "transferred_bytes",
        "source": "ecoindex",
        "sourceVersion": "1.0",
        "percentile": 45.889526934645886,
        "value": 1298000
      }
    ],
    "result": {
      "findings": [
        {
          "id": "unused-stylesheet-bytes",
          "severity": "breach",
          "value": 148000,
          "unit": "bytes",
          "share": {
            "value": 0.6915887850467289,
            "basis": "group-decoded-bytes"
          },
          "contributorCount": 1,
          "unavailableCount": 0,
          "evidence": [
            {
              "url": "https://sevre-et-loire.fr/assets/app.9d1e.css",
              "resourceType": "stylesheet",
              "transferredBytes": 38000,
              "decodedBytes": 214000,
              "unusedDecodedBytes": 148000
            }
          ],
          "reference": null
        },
        {
          "id": "reference-dom-node-count",
          "severity": "breach",
          "value": 2140,
          "unit": "count",
          "share": null,
          "contributorCount": 0,
          "unavailableCount": 0,
          "evidence": [],
          "reference": {
            "metricId": "dom_node_count",
            "source": "ecoindex",
            "sourceVersion": "1.0",
            "percentile": 92.5,
            "value": 2140
          }
        },
        {
          "id": "unused-script-bytes",
          "severity": "caution",
          "value": 1049000,
          "unit": "bytes",
          "share": {
            "value": 0.556203605514316,
            "basis": "group-decoded-bytes"
          },
          "contributorCount": 5,
          "unavailableCount": 0,
          "evidence": [
            {
              "url": "https://sevre-et-loire.fr/assets/vendor-dates.c40e.js",
              "resourceType": "script",
              "transferredBytes": 157000,
              "decodedBytes": 470000,
              "unusedDecodedBytes": 442000
            },
            {
              "url": "https://player.dailymotion.com/embed.js",
              "resourceType": "script",
              "transferredBytes": 176000,
              "decodedBytes": 512000,
              "unusedDecodedBytes": 214000
            },
            {
              "url": "https://sevre-et-loire.fr/assets/app.7c2f.js",
              "resourceType": "script",
              "transferredBytes": 122000,
              "decodedBytes": 402000,
              "unusedDecodedBytes": 176000
            }
          ],
          "reference": null
        },
        {
          "id": "third-party-weight",
          "severity": "caution",
          "value": 378000,
          "unit": "bytes",
          "share": {
            "value": 0.29121725731895226,
            "basis": "page-transferred-bytes"
          },
          "contributorCount": 4,
          "unavailableCount": 0,
          "evidence": [
            {
              "url": "https://player.dailymotion.com/embed.js",
              "resourceType": "script",
              "transferredBytes": 176000,
              "decodedBytes": 512000,
              "unusedDecodedBytes": 214000
            },
            {
              "url": "https://tarteaucitron.io/load.js",
              "resourceType": "script",
              "transferredBytes": 96000,
              "decodedBytes": 288000,
              "unusedDecodedBytes": 121000
            },
            {
              "url": "https://matomo.selo.fr/matomo.js",
              "resourceType": "script",
              "transferredBytes": 72000,
              "decodedBytes": 214000,
              "unusedDecodedBytes": 96000
            }
          ],
          "reference": null
        },
        {
          "id": "font-weight",
          "severity": "caution",
          "value": 186000,
          "unit": "bytes",
          "share": {
            "value": 0.14329738058551617,
            "basis": "page-transferred-bytes"
          },
          "contributorCount": 3,
          "unavailableCount": 0,
          "evidence": [
            {
              "url": "https://sevre-et-loire.fr/assets/fonts/martian-mono.woff2",
              "resourceType": "font",
              "transferredBytes": 62000,
              "decodedBytes": 62000,
              "unusedDecodedBytes": null
            },
            {
              "url": "https://sevre-et-loire.fr/assets/fonts/public-sans.woff2",
              "resourceType": "font",
              "transferredBytes": 62000,
              "decodedBytes": 62000,
              "unusedDecodedBytes": null
            },
            {
              "url": "https://sevre-et-loire.fr/assets/fonts/archivo-expanded.woff2",
              "resourceType": "font",
              "transferredBytes": 62000,
              "decodedBytes": 62000,
              "unusedDecodedBytes": null
            }
          ],
          "reference": null
        },
        {
          "id": "reference-request-count",
          "severity": "caution",
          "value": 84,
          "unit": "count",
          "share": null,
          "contributorCount": 0,
          "unavailableCount": 0,
          "evidence": [],
          "reference": {
            "metricId": "request_count",
            "source": "ecoindex",
            "sourceVersion": "1.0",
            "percentile": 53.75,
            "value": 84
          }
        }
      ],
      "withheld": [],
      "totalTransferredBytes": 1298000
    }
  }
} as Record<
    string,
    { aggregationId: string; result: FindingsResult; reference: readonly ReferencePosition[] }
  >,
} as const;
