// generated by scripts/generate-ledger-canon.ts. do not edit by hand.
// run `pnpm gen:ledger-canon` to rebuild; ledger-canon.test.ts fails if this
// file and the generator ever disagree.

import type { LedgerEntry } from '@balise/schemas';

export const ledgerCanon = {
  organizationId: "org_atelier_sextant",
  entryCount: 4821,
  merkleRoot: "8a01e31d97f4ca90bcf0ad32d926f962e230db9cd2dc7559b007fdd5eea6c9b5",
  anchoredAt: "2026-08-15T04:00:00.000Z",
  /** the runs the register retains, which is what "measured since" counts. */
  runs: {"count":4812,"firstAt":"2026-03-03T09:00:00.000Z","lastAt":"2026-08-15T14:02:41.000Z"},
  verification: {"status":"intact","checkedCount":4821},
  // the entries the interface and the documents cite. the rest of the chain
  // is history: it exists, it is counted, and nothing displays it.
  //
  // the cast crosses a generated-data boundary: this file is written by the
  // generator, and ledger-canon.test.ts parses every entry through
  // LedgerEntry and recomputes both of its hashes. keeping it a plain literal
  // is what keeps zod out of the browser bundle.
  entries: [
  {
    "organizationId": "org_atelier_sextant",
    "kind": "run",
    "refId": "run_4812",
    "payload": {
      "runId": "#4812",
      "scenario": "/demarches/acte-naissance",
      "profile": "mobile-4g",
      "pass": "cold",
      "runs": 5,
      "methodologyVersion": "v1.2",
      "fingerprint": {
        "browserBuild": "127.0.6533.88",
        "imageDigest": "sha256:4e91c2a7",
        "throttleProfile": "mobile-4g",
        "region": "eu-west-par"
      },
      "models": [
        "ecoindex@0.1.0",
        "swd@0.1.0",
        "onebyte@0.1.0"
      ],
      "metrics": {
        "transferredBytes": 1298000,
        "transferredBytesMad": 9000,
        "requestCount": 84,
        "domNodeCount": 2140,
        "carbonPerVisitG": 0.078072104,
        "carbonBandLowG": 0.078072104,
        "carbonBandHighG": 0.30108191666666667
      },
      "confidence": "high"
    },
    "sequence": 4819,
    "createdAt": "2026-08-15T14:02:41.000Z",
    "payloadHash": "c75a770cf93f18a9593ea0836c7eccddf37f67097be34cf25f092586cbf3c801",
    "prevHash": "80e857d927d659dc4e5414762ef9108421ffe87c249bd1711dfbdb0a7754aedf",
    "entryHash": "26b4fd8ab1ea44b275f1c3e2809d65e4025ca029efc518fe55b1f9adca5fb5cc"
  },
  {
    "organizationId": "org_atelier_sextant",
    "kind": "report_generated",
    "refId": "rapport_2026_sl_0417_t2_2026",
    "payload": {
      "contract": "2026-SL-0417",
      "quarter": "T2 2026",
      "period": "2026-04-02/2026-06-30",
      "article": "8.4",
      "runsInPeriod": 2621,
      "methodologyVersion": "v1.2"
    },
    "sequence": 3908,
    "createdAt": "2026-07-15T09:40:00.000Z",
    "payloadHash": "a65a26d38bada4097b778b31ad1994a1175e078dbff5fff6c4007b6a238e8985",
    "prevHash": "ffd48121f508012b60a6d2f8e41b11c25bb3db797897f913e4d8390fe800ef2a",
    "entryHash": "7057ee15cfb595df241c33db20f1bdbc29ff7c0165a8c4167b68b00937d28e82"
  },
  {
    "organizationId": "org_atelier_sextant",
    "kind": "report_generated",
    "refId": "rapport_2026_sl_0417_t3_2026",
    "payload": {
      "contract": "2026-SL-0417",
      "quarter": "T3 2026",
      "period": "2026-07-01/2026-08-15",
      "article": "8.4",
      "runsInPeriod": 1328,
      "methodologyVersion": "v1.2"
    },
    "sequence": 4820,
    "createdAt": "2026-08-15T15:20:08.000Z",
    "payloadHash": "e980bf33f5bef0ae554d87bb984f56d7f298e28789706341993d829c97240d7a",
    "prevHash": "26b4fd8ab1ea44b275f1c3e2809d65e4025ca029efc518fe55b1f9adca5fb5cc",
    "entryHash": "d69edf2fcfc91d0ae09a39dc5350c07e286ac2f18f26e5e87f9c982217531726"
  },
  {
    "organizationId": "org_atelier_sextant",
    "kind": "declaration_version",
    "refId": "declaration_v1",
    "payload": {
      "version": "v1",
      "packVersion": "rgesn-2024-v2",
      "conforme": 26,
      "applicable": 78
    },
    "sequence": 20,
    "createdAt": "2026-03-04T00:00:00.000Z",
    "payloadHash": "37fc04fc36a13a9d3004b9167a53358a9e5346df86052d497077a5e4d3f76979",
    "prevHash": "5912038027a289b2b13522d295efc23e5edd5a76b3f204f199ca1718c568415b",
    "entryHash": "384e81546b715fbb5a2340059823db58574bbea0fcb61ed64f30512f9f1140bb"
  },
  {
    "organizationId": "org_atelier_sextant",
    "kind": "declaration_version",
    "refId": "declaration_v2",
    "payload": {
      "version": "v2",
      "packVersion": "rgesn-2024-v2",
      "conforme": 34,
      "applicable": 77
    },
    "sequence": 254,
    "createdAt": "2026-03-12T00:00:00.000Z",
    "payloadHash": "48782bf2206dc8a01ebbb276fcc955b398c4de65fed3508645dac0b79ffbf97c",
    "prevHash": "d61d52f6589094ce35924bc5b745d5a09bd8562399eb5c2d3553ca8d1273d99d",
    "entryHash": "f42dae04c9dd3eefb7c2ee14dc7f2cff8876a304ebc484836eee10adb04c660d"
  },
  {
    "organizationId": "org_atelier_sextant",
    "kind": "declaration_version",
    "refId": "declaration_v3",
    "payload": {
      "version": "v3",
      "packVersion": "rgesn-2024-v2",
      "conforme": 41,
      "applicable": 70
    },
    "sequence": 4801,
    "createdAt": "2026-08-15T00:00:00.000Z",
    "payloadHash": "7b0eeb929df4f775096c469f542ae937b027e36eb65c2a05507c65b1544b3bf8",
    "prevHash": "813aa697f43fa4373ffa0498a5ddf41cac544e8e3438dcac91d250e305a08fdb",
    "entryHash": "2d1a9836315cff937c7ece07645f1b9a2b2c3c70a881e21e19716dff72c3042f"
  },
  {
    "organizationId": "org_atelier_sextant",
    "kind": "budget_override",
    "refId": "override_pr_401",
    "payload": {
      "pullRequest": "PR #401",
      "route": "/actualites",
      "reason": "Mandated by comms for the 14 July campaign, removal scheduled 01 Sep.",
      "authorisedBy": "m. carbonne"
    },
    "sequence": 3704,
    "createdAt": "2026-07-08T11:05:00.000Z",
    "payloadHash": "5bf30bfdc5f5ad6b540b1c1766726f9f992d3770f17a407511a5a271d6e71682",
    "prevHash": "3fdd6445142e38db9d8b75030b89b8f5d865334db34a1ece0a5ffb7ecce5eb1c",
    "entryHash": "102ae1927d6c5e26efe9c6065c07db3fa8077ee950da148ba2a5b9fd25a2f726"
  },
  {
    "organizationId": "org_atelier_sextant",
    "kind": "rebaseline",
    "refId": "rebaseline_4790",
    "payload": {
      "branch": "main",
      "toRun": "#4790",
      "reason": "post-refonte",
      "author": "c. bellanger"
    },
    "sequence": 4462,
    "createdAt": "2026-08-03T09:15:00.000Z",
    "payloadHash": "58f7607f8714c3c60cfc16629d0b49be70bc185ce4741594abb6b2763ec7a29e",
    "prevHash": "cca5aee5ec98f09fa35483b8844033fda6eb2d648a4f27336def1739db94c829",
    "entryHash": "5fb4e619a18a7880fb97280e3762aa3b532264e30e5ad919dae1aeee38fd732f"
  },
  {
    "organizationId": "org_atelier_sextant",
    "kind": "rebaseline",
    "refId": "rebaseline_4612",
    "payload": {
      "branch": "main",
      "toRun": "#4612",
      "reason": "new hosting",
      "author": "m. carbonne"
    },
    "sequence": 3790,
    "createdAt": "2026-07-11T08:30:00.000Z",
    "payloadHash": "622d0460b5bb6298ab62cd5fb42948879bab213be0ff336d6b136f9080f86a61",
    "prevHash": "d40af2f983d8bd7fdaa9472f8fb6384b9bcb3cd7e0a129a34ecd8361179a2351",
    "entryHash": "7d084dfddae374b8dadeca84d1d39339c6b06a3eba450cb84737c206a9051dd8"
  },
  {
    "organizationId": "org_atelier_sextant",
    "kind": "methodology_version",
    "refId": "methodology_v1.2",
    "payload": {
      "version": "v1.2",
      "url": "balise.fr/methodologie"
    },
    "sequence": 0,
    "createdAt": "2026-03-01T00:00:00.000Z",
    "payloadHash": "2d138d5a14efb55ab3e14590c2d330e068d836e203a620e8459254f50db360ef",
    "prevHash": "0000000000000000000000000000000000000000000000000000000000000000",
    "entryHash": "a708fe0f40f0bda78a15654cae4661b77c6491b500911f96c2be5968d30223db"
  }
] as unknown as readonly LedgerEntry[],
} as const;
