// generated by scripts/generate-ledger-canon.ts. do not edit by hand.
// run `pnpm gen:ledger-canon` to rebuild; ledger-canon.test.ts fails if this
// file and the generator ever disagree.

import type { LedgerEntry } from '@balise/schemas';

export const ledgerCanon = {
  organizationId: "org_atelier_sextant",
  entryCount: 4820,
  merkleRoot: "0fd4d25d652906ee343df1c216dd26277bc53804c24fe9a6f3d2014d24f2da35",
  anchoredAt: "2026-08-15T04:00:00.000Z",
  verification: {"status":"intact","checkedCount":4820},
  // the entries the interface and the documents cite. the rest of the chain
  // is history: it exists, it is counted, and nothing displays it.
  //
  // the cast crosses a generated-data boundary: this file is written by the
  // generator, and ledger-canon.test.ts parses every entry through
  // LedgerEntry and recomputes both of its hashes. keeping it a plain literal
  // is what keeps zod out of the browser bundle.
  entries: [
  {
    "organizationId": "org_atelier_sextant",
    "kind": "run",
    "refId": "run_4812",
    "payload": {
      "runId": "#4812",
      "scenario": "/accueil",
      "profile": "mobile-4g",
      "pass": "cold",
      "runs": 5,
      "methodologyVersion": "v1.2",
      "fingerprint": {
        "browserBuild": "127.0.6533.88",
        "imageDigest": "sha256:4e91c2a7",
        "throttleProfile": "mobile-4g",
        "region": "eu-west-par"
      },
      "models": [
        "ecoindex@0.1.0",
        "swd@0.1.0",
        "onebyte@0.1.0"
      ],
      "metrics": {
        "transferredBytes": 1258000,
        "transferredBytesMad": 6000,
        "requestCount": 84,
        "domNodeCount": 2140,
        "carbonPerVisitG": 0.075666184,
        "carbonBandLowG": 0.075666184,
        "carbonBandHighG": 0.29180358333333334
      },
      "confidence": "high"
    },
    "sequence": 4818,
    "createdAt": "2026-08-15T14:02:41.000Z",
    "payloadHash": "bbdfce3d258bb24c30f543c16f1e9260d92952be39e7ce831411749309ba67af",
    "prevHash": "ed09b53a002f15112d3c5b2b4f4e6ddf1aab9623dab0c4135e9cbccd2453c941",
    "entryHash": "4d62064c32d0274f356ce4a5901395263abb9db2235654cdc930a1fa2de0989e"
  },
  {
    "organizationId": "org_atelier_sextant",
    "kind": "report_generated",
    "refId": "rapport_2026_sl_0417_t3",
    "payload": {
      "contract": "2026-SL-0417",
      "quarter": "T3 2026",
      "period": "2026-07-01/2026-09-30",
      "article": "8.4",
      "runsInPeriod": 1284,
      "methodologyVersion": "v1.2"
    },
    "sequence": 4819,
    "createdAt": "2026-08-15T15:20:08.000Z",
    "payloadHash": "fd70dbfeb08568cb91a20cf8352a41c5c4102f04bfe4f9d8a3f7a562bb5bc820",
    "prevHash": "4d62064c32d0274f356ce4a5901395263abb9db2235654cdc930a1fa2de0989e",
    "entryHash": "4532205ce24b3433aa5c520b2187a9f357c73bf4e16eeb5b74fef1bf96d2ee5c"
  },
  {
    "organizationId": "org_atelier_sextant",
    "kind": "declaration_version",
    "refId": "declaration_v1",
    "payload": {
      "version": "v1",
      "packVersion": "rgesn-2024-v2",
      "conforme": 28,
      "applicable": 70
    },
    "sequence": 32,
    "createdAt": "2026-03-04T10:12:00.000Z",
    "payloadHash": "80ea86b8f26461b0003595dd82b6b5dd91920048b2ea04cb736ecf1a641a2357",
    "prevHash": "0ec8bca55b38acff26e27f00eb9a0a555c6c9f9543ef5c58e751f0bba4263aac",
    "entryHash": "6f192bc3deea6c1760699c32bd6220c45c75b5d374d1ae9cb16876b31f834a4b"
  },
  {
    "organizationId": "org_atelier_sextant",
    "kind": "declaration_version",
    "refId": "declaration_v2",
    "payload": {
      "version": "v2",
      "packVersion": "rgesn-2024-v2",
      "conforme": 34,
      "applicable": 70
    },
    "sequence": 274,
    "createdAt": "2026-03-12T16:40:00.000Z",
    "payloadHash": "ce202c8bafd875129b94aadb3c28ecbf78e8eb7476cbacf5a6633e08aaf97c38",
    "prevHash": "010840e624c0e2f1d21470907dc21fd5a161d14cc848c0d54cc5c37adfe939d6",
    "entryHash": "920b0146e3b4f03d4fd3342c9da2376bd7d67d693afe279cb99475aa30728820"
  },
  {
    "organizationId": "org_atelier_sextant",
    "kind": "declaration_version",
    "refId": "declaration_v3",
    "payload": {
      "version": "v3",
      "packVersion": "rgesn-2024-v2",
      "conforme": 41,
      "applicable": 70
    },
    "sequence": 4816,
    "createdAt": "2026-08-15T13:00:00.000Z",
    "payloadHash": "7b0eeb929df4f775096c469f542ae937b027e36eb65c2a05507c65b1544b3bf8",
    "prevHash": "c4c2fbe7528f31d8f4db1163789af538cf38ea5a63daeee1acb6ce85df3da8a1",
    "entryHash": "754c6fbbf787e88e24c2adb54f70ea673620e4f3219b044eac6c82fc704f33e1"
  },
  {
    "organizationId": "org_atelier_sextant",
    "kind": "budget_override",
    "refId": "override_pr_401",
    "payload": {
      "pullRequest": "PR #401",
      "route": "/actualites",
      "reason": "Mandated by comms for the 14 July campaign, removal scheduled 01 Sep.",
      "authorisedBy": "m. carbonne"
    },
    "sequence": 3704,
    "createdAt": "2026-07-08T11:05:00.000Z",
    "payloadHash": "5bf30bfdc5f5ad6b540b1c1766726f9f992d3770f17a407511a5a271d6e71682",
    "prevHash": "720a42e135c5dbf83bff3230f328743005bae5cbb238441bea16e1320e793b5c",
    "entryHash": "8737fb74a797ff0c12f0bfdf79013fd574d59e30ded5bea77f13c259842c1492"
  },
  {
    "organizationId": "org_atelier_sextant",
    "kind": "rebaseline",
    "refId": "rebaseline_4790",
    "payload": {
      "branch": "main",
      "toRun": "#4790",
      "reason": "post-refonte",
      "author": "c. bellanger"
    },
    "sequence": 4461,
    "createdAt": "2026-08-03T09:15:00.000Z",
    "payloadHash": "58f7607f8714c3c60cfc16629d0b49be70bc185ce4741594abb6b2763ec7a29e",
    "prevHash": "9afa17c9340cd4094f021d20c167469e1bf8346aa718370b8e312018b0e4796c",
    "entryHash": "be35597ce811e884d109736035a27002379714a6ad260da8e223ebbbeb9b4df2"
  },
  {
    "organizationId": "org_atelier_sextant",
    "kind": "rebaseline",
    "refId": "rebaseline_4612",
    "payload": {
      "branch": "main",
      "toRun": "#4612",
      "reason": "new hosting",
      "author": "m. carbonne"
    },
    "sequence": 3790,
    "createdAt": "2026-07-11T08:30:00.000Z",
    "payloadHash": "622d0460b5bb6298ab62cd5fb42948879bab213be0ff336d6b136f9080f86a61",
    "prevHash": "aff0a25c72c8c615a743d8b1a96911d01123e373fd19601475134f51e270d075",
    "entryHash": "57192464d5228e1b7a27dd56385eb4f78783959f640c718a12449dee758f6444"
  },
  {
    "organizationId": "org_atelier_sextant",
    "kind": "methodology_version",
    "refId": "methodology_v1.2",
    "payload": {
      "version": "v1.2",
      "url": "balise.fr/methodologie"
    },
    "sequence": 0,
    "createdAt": "2026-03-01T00:00:00.000Z",
    "payloadHash": "2d138d5a14efb55ab3e14590c2d330e068d836e203a620e8459254f50db360ef",
    "prevHash": "0000000000000000000000000000000000000000000000000000000000000000",
    "entryHash": "a708fe0f40f0bda78a15654cae4661b77c6491b500911f96c2be5968d30223db"
  }
] as unknown as readonly LedgerEntry[],
} as const;
