// generated by scripts/generate-ledger-canon.ts. do not edit by hand.
// run `pnpm gen:ledger-canon` to rebuild; ledger-canon.test.ts fails if this
// file and the generator ever disagree.

import type { LedgerEntry } from '@balise/schemas';

export const ledgerCanon = {
  organizationId: "org_atelier_sextant",
  entryCount: 4821,
  merkleRoot: "86a59c5e0b86bee3e6c69cc4ac703222b72aff10531b84f48eec2f5698e71705",
  anchoredAt: "2026-08-15T04:00:00.000Z",
  /** the runs the register retains, which is what "measured since" counts. */
  runs: {"count":4812,"firstAt":"2026-03-03T09:00:00.000Z","lastAt":"2026-08-15T14:02:41.000Z"},
  verification: {"status":"intact","checkedCount":4821},
  // the entries the interface and the documents cite. the rest of the chain
  // is history: it exists, it is counted, and nothing displays it.
  //
  // the cast crosses a generated-data boundary: this file is written by the
  // generator, and ledger-canon.test.ts parses every entry through
  // LedgerEntry and recomputes both of its hashes. keeping it a plain literal
  // is what keeps zod out of the browser bundle.
  entries: [
  {
    "organizationId": "org_atelier_sextant",
    "kind": "run",
    "refId": "run_4812",
    "payload": {
      "runId": "#4812",
      "scenario": "/demarches/acte-naissance",
      "profile": "mobile-4g",
      "pass": "cold",
      "runs": 5,
      "methodologyVersion": "v1.2",
      "fingerprint": {
        "browserBuild": "127.0.6533.88",
        "imageDigest": "sha256:4e91c2a7",
        "throttleProfile": "mobile-4g",
        "region": "eu-west-par"
      },
      "models": [
        "ecoindex@0.1.0",
        "swd@0.1.0",
        "onebyte@0.1.0"
      ],
      "metrics": {
        "transferredBytes": 1298000,
        "transferredBytesMad": 9000,
        "requestCount": 84,
        "domNodeCount": 2140,
        "carbonPerVisitG": 0.078072104,
        "carbonBandLowG": 0.078072104,
        "carbonBandHighG": 0.30108191666666667
      },
      "confidence": "high"
    },
    "sequence": 4819,
    "createdAt": "2026-08-15T14:02:41.000Z",
    "payloadHash": "c75a770cf93f18a9593ea0836c7eccddf37f67097be34cf25f092586cbf3c801",
    "prevHash": "bfa88adedf4df063882edca282595740dd76cab1e4a44e5d301cc092ab418015",
    "entryHash": "8ec4b0aa694aaf334772379a0e41340be99470cc792a4fe68ceab4a0c8479b5e"
  },
  {
    "organizationId": "org_atelier_sextant",
    "kind": "run",
    "refId": "run_4790",
    "payload": {
      "runId": "#4790",
      "scenario": "/demarches/acte-naissance",
      "profile": "desktop-fibre",
      "pass": "cold",
      "runs": 5,
      "methodologyVersion": "v1.2"
    },
    "sequence": 4795,
    "createdAt": "2026-08-14T19:54:47.348Z",
    "payloadHash": "2f05d22583006d47c53d91c4dee8667e28e541ec91262355ecc9b2a3e32f291d",
    "prevHash": "23a9cf7cf1676dcae7245e52c88c3ddc9ce0a408347d4d6cb2122e08d228ed0b",
    "entryHash": "e5537c8f2ff9062daf3bc92dbe38d1aa1ecbdf11cf97fa25d4178712897844af"
  },
  {
    "organizationId": "org_atelier_sextant",
    "kind": "run",
    "refId": "run_4612",
    "payload": {
      "runId": "#4612",
      "scenario": "/accueil",
      "profile": "desktop-fibre",
      "pass": "cold",
      "runs": 5,
      "methodologyVersion": "v1.2"
    },
    "sequence": 4616,
    "createdAt": "2026-08-08T17:12:44.159Z",
    "payloadHash": "835fa0cf06851fe96842fd5fa9603ec1b4e232e9ad76b36ef92d355f02d891af",
    "prevHash": "3ba677ef66d3e74e6cba440baeaf3759ea3d7e44a2709a27bbab593888781de7",
    "entryHash": "b603c68b45ce38eb5e2ba8f5ce433f5767390ac16f28b702e65dc9165857456f"
  },
  {
    "organizationId": "org_atelier_sextant",
    "kind": "report_generated",
    "refId": "rapport_2026_sl_0417_t2_2026",
    "payload": {
      "contract": "2026-SL-0417",
      "quarter": "T2 2026",
      "period": "2026-04-02/2026-06-30",
      "article": "8.4",
      "runsInPeriod": 2621,
      "methodologyVersion": "v1.2"
    },
    "sequence": 3907,
    "createdAt": "2026-07-15T09:40:00.000Z",
    "payloadHash": "a65a26d38bada4097b778b31ad1994a1175e078dbff5fff6c4007b6a238e8985",
    "prevHash": "f2d8c2d5c128ae77fe3b24beff5ace77b4f8838ef462d99d94147795f9976899",
    "entryHash": "8d6a718455d3bb4fa1b743c51b4c03cb4a52a816216cf76cb742474c83c2d257"
  },
  {
    "organizationId": "org_atelier_sextant",
    "kind": "report_generated",
    "refId": "rapport_2026_sl_0417_t3_2026",
    "payload": {
      "contract": "2026-SL-0417",
      "quarter": "T3 2026",
      "period": "2026-07-01/2026-08-15",
      "article": "8.4",
      "runsInPeriod": 1328,
      "methodologyVersion": "v1.2"
    },
    "sequence": 4820,
    "createdAt": "2026-08-15T15:20:08.000Z",
    "payloadHash": "e980bf33f5bef0ae554d87bb984f56d7f298e28789706341993d829c97240d7a",
    "prevHash": "8ec4b0aa694aaf334772379a0e41340be99470cc792a4fe68ceab4a0c8479b5e",
    "entryHash": "cfb4356cd83b366558291d9bac8cef72f9a36fe6210f442c42c3fa52ccd5b693"
  },
  {
    "organizationId": "org_atelier_sextant",
    "kind": "declaration_version",
    "refId": "declaration_v1",
    "payload": {
      "version": "v1",
      "packVersion": "rgesn-2024-v2",
      "conforme": 26,
      "applicable": 78
    },
    "sequence": 20,
    "createdAt": "2026-03-04T00:00:00.000Z",
    "payloadHash": "37fc04fc36a13a9d3004b9167a53358a9e5346df86052d497077a5e4d3f76979",
    "prevHash": "5912038027a289b2b13522d295efc23e5edd5a76b3f204f199ca1718c568415b",
    "entryHash": "384e81546b715fbb5a2340059823db58574bbea0fcb61ed64f30512f9f1140bb"
  },
  {
    "organizationId": "org_atelier_sextant",
    "kind": "declaration_version",
    "refId": "declaration_v2",
    "payload": {
      "version": "v2",
      "packVersion": "rgesn-2024-v2",
      "conforme": 34,
      "applicable": 77
    },
    "sequence": 254,
    "createdAt": "2026-03-12T00:00:00.000Z",
    "payloadHash": "48782bf2206dc8a01ebbb276fcc955b398c4de65fed3508645dac0b79ffbf97c",
    "prevHash": "d61d52f6589094ce35924bc5b745d5a09bd8562399eb5c2d3553ca8d1273d99d",
    "entryHash": "f42dae04c9dd3eefb7c2ee14dc7f2cff8876a304ebc484836eee10adb04c660d"
  },
  {
    "organizationId": "org_atelier_sextant",
    "kind": "declaration_version",
    "refId": "declaration_v3",
    "payload": {
      "version": "v3",
      "packVersion": "rgesn-2024-v2",
      "conforme": 41,
      "applicable": 70
    },
    "sequence": 4801,
    "createdAt": "2026-08-15T00:00:00.000Z",
    "payloadHash": "7b0eeb929df4f775096c469f542ae937b027e36eb65c2a05507c65b1544b3bf8",
    "prevHash": "ffd51463a6658a46d9c0170d9835788c2d3c7fe3fb6f29dc13cb8b5581f199e7",
    "entryHash": "b6ff321bc9b4e8fe80db9e98a1df048d0fcf70d47f42333c5ad4afba8b4f7e4d"
  },
  {
    "organizationId": "org_atelier_sextant",
    "kind": "budget_override",
    "refId": "override_pr_401",
    "payload": {
      "pullRequest": "PR #401",
      "route": "/actualites",
      "reason": "Mandated by comms for the 14 July campaign, removal scheduled 01 Sep.",
      "authorisedBy": "m. carbonne"
    },
    "sequence": 3704,
    "createdAt": "2026-07-08T11:05:00.000Z",
    "payloadHash": "5bf30bfdc5f5ad6b540b1c1766726f9f992d3770f17a407511a5a271d6e71682",
    "prevHash": "3fdd6445142e38db9d8b75030b89b8f5d865334db34a1ece0a5ffb7ecce5eb1c",
    "entryHash": "102ae1927d6c5e26efe9c6065c07db3fa8077ee950da148ba2a5b9fd25a2f726"
  },
  {
    "organizationId": "org_atelier_sextant",
    "kind": "rebaseline",
    "refId": "rebaseline_4790",
    "payload": {
      "branch": "main",
      "toRun": "#4790",
      "reason": "post-refonte",
      "author": "c. bellanger"
    },
    "sequence": 4796,
    "createdAt": "2026-08-14T20:30:47.348Z",
    "payloadHash": "58f7607f8714c3c60cfc16629d0b49be70bc185ce4741594abb6b2763ec7a29e",
    "prevHash": "e5537c8f2ff9062daf3bc92dbe38d1aa1ecbdf11cf97fa25d4178712897844af",
    "entryHash": "c1f57a039cbdf21939713d27ecd62d91d9e41f6f18b1c8c57c3b1685e4e3101b"
  },
  {
    "organizationId": "org_atelier_sextant",
    "kind": "rebaseline",
    "refId": "rebaseline_4612",
    "payload": {
      "branch": "main",
      "toRun": "#4612",
      "reason": "new hosting",
      "author": "m. carbonne"
    },
    "sequence": 4617,
    "createdAt": "2026-08-08T17:59:44.159Z",
    "payloadHash": "622d0460b5bb6298ab62cd5fb42948879bab213be0ff336d6b136f9080f86a61",
    "prevHash": "b603c68b45ce38eb5e2ba8f5ce433f5767390ac16f28b702e65dc9165857456f",
    "entryHash": "3de94127cc5488a85c6e204eb4d9df34971a1f22310f94606c48b9f9e5380ecd"
  },
  {
    "organizationId": "org_atelier_sextant",
    "kind": "methodology_version",
    "refId": "methodology_v1.2",
    "payload": {
      "version": "v1.2",
      "url": "balise.fr/methodologie"
    },
    "sequence": 0,
    "createdAt": "2026-03-01T00:00:00.000Z",
    "payloadHash": "2d138d5a14efb55ab3e14590c2d330e068d836e203a620e8459254f50db360ef",
    "prevHash": "0000000000000000000000000000000000000000000000000000000000000000",
    "entryHash": "a708fe0f40f0bda78a15654cae4661b77c6491b500911f96c2be5968d30223db"
  }
] as unknown as readonly LedgerEntry[],
} as const;
