// generated by scripts/generate-measurement-canon.ts. do not edit by hand.
// run `pnpm gen:measurement-canon` to rebuild; measurement-canon.test.ts
// fails if this file and the generator ever disagree.
//
// every median, dispersion, noise floor and confidence grade below was computed
// by @balise/measure-core from the runs recorded beside it. no statistic here
// was chosen: the mad is the mad of those run values, the floor is the scaled
// median of the historical mads, and the grade is what gradeConfidence
// returned for that dispersion at that sample count.

import type { RawCapture } from '@balise/schemas';
import type { CanonHistoryPoint, CanonMetric } from './measurement-types';

export const measurementCanon = {
  scalingFactor: 1.2,
  minHistory: 20,
  runOffsets: [-0.45,1,0,-1,0.5],
  scenarios: [
  {
    "id": "service",
    "label": "médiane du service",
    "pass": "cold",
    "historyCount": 24,
    "aggregationIds": [
      "service"
    ]
  },
  {
    "id": "route-acte-naissance",
    "label": "/demarches/acte-naissance",
    "pass": "cold",
    "historyCount": 24,
    "aggregationIds": [
      "baseline",
      "candidate"
    ]
  },
  {
    "id": "journey-demande-acte",
    "label": "journey:demande-acte",
    "pass": "cold",
    "historyCount": 24,
    "aggregationIds": [
      "journey"
    ]
  },
  {
    "id": "scan",
    "label": "bibliotheques-selo.fr",
    "pass": "cold",
    "historyCount": 0,
    "aggregationIds": [
      "scan"
    ]
  }
] as ReadonlyArray<{
    id: string;
    label: string;
    pass: 'cold' | 'warm';
    historyCount: number;
    /** the aggregations this scenario publishes, all read against its one floor. */
    aggregationIds: readonly string[];
  }>,
  aggregations: [
  {
    "id": "service",
    "scenarioId": "service",
    "label": "médiane du service",
    "pass": "cold",
    "sampleCount": 5,
    "fingerprintStable": true,
    "metrics": [
      {
        "metricId": "transferred_bytes",
        "unit": "bytes",
        "median": 1258000,
        "mad": 6000,
        "min": 1246000,
        "max": 1270000,
        "sampleCount": 5,
        "runValues": [
          1252600,
          1270000,
          1258000,
          1246000,
          1264000
        ],
        "floor": {
          "status": "established",
          "metricId": "transferred_bytes",
          "unit": "bytes",
          "value": 7380,
          "sampleCount": 24,
          "scalingFactor": 1.2
        },
        "confidence": "high"
      },
      {
        "metricId": "request_count",
        "unit": "count",
        "median": 82,
        "mad": 1,
        "min": 80,
        "max": 84,
        "sampleCount": 5,
        "runValues": [
          81,
          84,
          82,
          80,
          83
        ],
        "floor": {
          "status": "established",
          "metricId": "request_count",
          "unit": "count",
          "value": 1.2,
          "sampleCount": 24,
          "scalingFactor": 1.2
        },
        "confidence": "high"
      },
      {
        "metricId": "dom_node_count",
        "unit": "count",
        "median": 2140,
        "mad": 130,
        "min": 1880,
        "max": 2400,
        "sampleCount": 5,
        "runValues": [
          2023,
          2400,
          2140,
          1880,
          2270
        ],
        "floor": {
          "status": "established",
          "metricId": "dom_node_count",
          "unit": "count",
          "value": 160.2,
          "sampleCount": 24,
          "scalingFactor": 1.2
        },
        "confidence": "medium"
      },
      {
        "metricId": "js_execution_ms",
        "unit": "ms",
        "median": 588,
        "mad": 17,
        "min": 554,
        "max": 622,
        "sampleCount": 5,
        "runValues": [
          572.7,
          622,
          588,
          554,
          605
        ],
        "floor": {
          "status": "established",
          "metricId": "js_execution_ms",
          "unit": "ms",
          "value": 20.910000000000014,
          "sampleCount": 24,
          "scalingFactor": 1.2
        },
        "confidence": "high"
      },
      {
        "metricId": "third_party_bytes",
        "unit": "bytes",
        "median": 478000,
        "mad": 4500,
        "min": 469000,
        "max": 487000,
        "sampleCount": 5,
        "runValues": [
          482500,
          469000,
          478000,
          487000,
          473950
        ],
        "floor": {
          "status": "established",
          "metricId": "third_party_bytes",
          "unit": "bytes",
          "value": 5535,
          "sampleCount": 24,
          "scalingFactor": 1.2
        },
        "confidence": "high"
      },
      {
        "metricId": "third_party_share_pct",
        "unit": "pct",
        "median": 37.99682034976153,
        "mad": 0.5230583026414735,
        "min": 36.92913385826772,
        "max": 39.08507223113965,
        "sampleCount": 5,
        "runValues": [
          38.519878652403,
          36.92913385826772,
          37.99682034976153,
          39.08507223113965,
          37.49604430379747
        ],
        "floor": {
          "status": "established",
          "metricId": "third_party_share_pct",
          "unit": "pct",
          "value": 0.6434327575943157,
          "sampleCount": 24,
          "scalingFactor": 1.2
        },
        "confidence": "high"
      }
    ]
  },
  {
    "id": "baseline",
    "scenarioId": "route-acte-naissance",
    "label": "#4790 · main",
    "pass": "cold",
    "sampleCount": 5,
    "fingerprintStable": true,
    "metrics": [
      {
        "metricId": "transferred_bytes",
        "unit": "bytes",
        "median": 1114000,
        "mad": 6000,
        "min": 1102000,
        "max": 1126000,
        "sampleCount": 5,
        "runValues": [
          1108600,
          1126000,
          1114000,
          1102000,
          1120000
        ],
        "floor": {
          "status": "established",
          "metricId": "transferred_bytes",
          "unit": "bytes",
          "value": 7380,
          "sampleCount": 24,
          "scalingFactor": 1.2
        },
        "confidence": "high"
      },
      {
        "metricId": "request_count",
        "unit": "count",
        "median": 82,
        "mad": 1,
        "min": 80,
        "max": 84,
        "sampleCount": 5,
        "runValues": [
          81,
          84,
          82,
          80,
          83
        ],
        "floor": {
          "status": "established",
          "metricId": "request_count",
          "unit": "count",
          "value": 1.2,
          "sampleCount": 24,
          "scalingFactor": 1.2
        },
        "confidence": "high"
      },
      {
        "metricId": "dom_node_count",
        "unit": "count",
        "median": 2118,
        "mad": 150,
        "min": 1818,
        "max": 2418,
        "sampleCount": 5,
        "runValues": [
          1983,
          2418,
          2118,
          1818,
          2268
        ],
        "floor": {
          "status": "established",
          "metricId": "dom_node_count",
          "unit": "count",
          "value": 184.79999999999998,
          "sampleCount": 24,
          "scalingFactor": 1.2
        },
        "confidence": "medium"
      },
      {
        "metricId": "js_execution_ms",
        "unit": "ms",
        "median": 548,
        "mad": 12,
        "min": 524,
        "max": 572,
        "sampleCount": 5,
        "runValues": [
          537.2,
          572,
          548,
          524,
          560
        ],
        "floor": {
          "status": "established",
          "metricId": "js_execution_ms",
          "unit": "ms",
          "value": 14.760000000000012,
          "sampleCount": 24,
          "scalingFactor": 1.2
        },
        "confidence": "high"
      },
      {
        "metricId": "third_party_bytes",
        "unit": "bytes",
        "median": 180000,
        "mad": 2000,
        "min": 176000,
        "max": 184000,
        "sampleCount": 5,
        "runValues": [
          182000,
          176000,
          180000,
          184000,
          178200
        ],
        "floor": {
          "status": "established",
          "metricId": "third_party_bytes",
          "unit": "bytes",
          "value": 2460,
          "sampleCount": 24,
          "scalingFactor": 1.2
        },
        "confidence": "high"
      },
      {
        "metricId": "third_party_share_pct",
        "unit": "pct",
        "median": 16.15798922800718,
        "mad": 0.2591134239863244,
        "min": 15.630550621669629,
        "max": 16.696914700544465,
        "sampleCount": 5,
        "runValues": [
          16.417102651993506,
          15.630550621669629,
          16.15798922800718,
          16.696914700544465,
          15.910714285714286
        ],
        "floor": {
          "status": "established",
          "metricId": "third_party_share_pct",
          "unit": "pct",
          "value": 0.31874927871458564,
          "sampleCount": 24,
          "scalingFactor": 1.2
        },
        "confidence": "high"
      }
    ]
  },
  {
    "id": "candidate",
    "scenarioId": "route-acte-naissance",
    "label": "#4812 · pr/412",
    "pass": "cold",
    "sampleCount": 5,
    "fingerprintStable": true,
    "metrics": [
      {
        "metricId": "transferred_bytes",
        "unit": "bytes",
        "median": 1298000,
        "mad": 9000,
        "min": 1280000,
        "max": 1316000,
        "sampleCount": 5,
        "runValues": [
          1289900,
          1316000,
          1298000,
          1280000,
          1307000
        ],
        "floor": {
          "status": "established",
          "metricId": "transferred_bytes",
          "unit": "bytes",
          "value": 7380,
          "sampleCount": 24,
          "scalingFactor": 1.2
        },
        "confidence": "high"
      },
      {
        "metricId": "request_count",
        "unit": "count",
        "median": 84,
        "mad": 1,
        "min": 82,
        "max": 86,
        "sampleCount": 5,
        "runValues": [
          83,
          86,
          84,
          82,
          85
        ],
        "floor": {
          "status": "established",
          "metricId": "request_count",
          "unit": "count",
          "value": 1.2,
          "sampleCount": 24,
          "scalingFactor": 1.2
        },
        "confidence": "high"
      },
      {
        "metricId": "dom_node_count",
        "unit": "count",
        "median": 2140,
        "mad": 160,
        "min": 1820,
        "max": 2460,
        "sampleCount": 5,
        "runValues": [
          1996,
          2460,
          2140,
          1820,
          2300
        ],
        "floor": {
          "status": "established",
          "metricId": "dom_node_count",
          "unit": "count",
          "value": 184.79999999999998,
          "sampleCount": 24,
          "scalingFactor": 1.2
        },
        "confidence": "medium"
      },
      {
        "metricId": "js_execution_ms",
        "unit": "ms",
        "median": 612,
        "mad": 15,
        "min": 582,
        "max": 642,
        "sampleCount": 5,
        "runValues": [
          598.5,
          642,
          612,
          582,
          627
        ],
        "floor": {
          "status": "established",
          "metricId": "js_execution_ms",
          "unit": "ms",
          "value": 14.760000000000012,
          "sampleCount": 24,
          "scalingFactor": 1.2
        },
        "confidence": "high"
      },
      {
        "metricId": "third_party_bytes",
        "unit": "bytes",
        "median": 378000,
        "mad": 3000,
        "min": 372000,
        "max": 384000,
        "sampleCount": 5,
        "runValues": [
          381000,
          372000,
          378000,
          384000,
          375300
        ],
        "floor": {
          "status": "established",
          "metricId": "third_party_bytes",
          "unit": "bytes",
          "value": 2460,
          "sampleCount": 24,
          "scalingFactor": 1.2
        },
        "confidence": "high"
      },
      {
        "metricId": "third_party_share_pct",
        "unit": "pct",
        "median": 29.121725731895225,
        "mad": 0.4154476924012336,
        "min": 28.267477203647417,
        "max": 30,
        "sampleCount": 5,
        "runValues": [
          29.53717342429646,
          28.267477203647417,
          29.121725731895225,
          30,
          28.71461361897475
        ],
        "floor": {
          "status": "established",
          "metricId": "third_party_share_pct",
          "unit": "pct",
          "value": 0.31874927871458564,
          "sampleCount": 24,
          "scalingFactor": 1.2
        },
        "confidence": "high"
      }
    ],
    "capture": {
      "serviceOrigin": "https://sevre-et-loire.fr",
      "pass": "cold",
      "resources": [
        {
          "url": "https://sevre-et-loire.fr/demarches/acte-naissance",
          "resourceType": "document",
          "transferredBytes": 42000,
          "decodedBytes": 186000,
          "unusedDecodedBytes": null,
          "startMs": 0,
          "durationMs": 240
        },
        {
          "url": "https://sevre-et-loire.fr/assets/app.9d1e.css",
          "resourceType": "stylesheet",
          "transferredBytes": 38000,
          "decodedBytes": 214000,
          "unusedDecodedBytes": 148000,
          "startMs": 252,
          "durationMs": 180
        },
        {
          "url": "https://sevre-et-loire.fr/assets/app.7c2f.js",
          "resourceType": "script",
          "transferredBytes": 122000,
          "decodedBytes": 402000,
          "unusedDecodedBytes": 176000,
          "startMs": 264,
          "durationMs": 420
        },
        {
          "url": "https://sevre-et-loire.fr/assets/fonts/martian-mono.woff2",
          "resourceType": "font",
          "transferredBytes": 62000,
          "decodedBytes": 62000,
          "unusedDecodedBytes": null,
          "startMs": 288,
          "durationMs": 190
        },
        {
          "url": "https://sevre-et-loire.fr/assets/fonts/public-sans.woff2",
          "resourceType": "font",
          "transferredBytes": 62000,
          "decodedBytes": 62000,
          "unusedDecodedBytes": null,
          "startMs": 296,
          "durationMs": 186
        },
        {
          "url": "https://sevre-et-loire.fr/assets/fonts/archivo-expanded.woff2",
          "resourceType": "font",
          "transferredBytes": 62000,
          "decodedBytes": 62000,
          "unusedDecodedBytes": null,
          "startMs": 304,
          "durationMs": 194
        },
        {
          "url": "https://geo.api.gouv.fr/communes?code=44",
          "resourceType": "other",
          "transferredBytes": 12000,
          "decodedBytes": 48000,
          "unusedDecodedBytes": null,
          "startMs": 720,
          "durationMs": 210
        },
        {
          "url": "https://matomo.selo.fr/matomo.js",
          "resourceType": "script",
          "transferredBytes": 72000,
          "decodedBytes": 214000,
          "unusedDecodedBytes": 96000,
          "startMs": 832,
          "durationMs": 260
        },
        {
          "url": "https://tarteaucitron.io/load.js",
          "resourceType": "script",
          "transferredBytes": 96000,
          "decodedBytes": 288000,
          "unusedDecodedBytes": 121000,
          "startMs": 936,
          "durationMs": 300
        },
        {
          "url": "https://sevre-et-loire.fr/assets/vendor-dates.c40e.js",
          "resourceType": "script",
          "transferredBytes": 157000,
          "decodedBytes": 470000,
          "unusedDecodedBytes": 442000,
          "startMs": 340,
          "durationMs": 460
        },
        {
          "url": "https://sevre-et-loire.fr/assets/media/hero.webp",
          "resourceType": "image",
          "transferredBytes": 165000,
          "decodedBytes": 165000,
          "unusedDecodedBytes": null,
          "startMs": 468,
          "durationMs": 480
        },
        {
          "url": "https://player.dailymotion.com/embed.js",
          "resourceType": "script",
          "transferredBytes": 176000,
          "decodedBytes": 512000,
          "unusedDecodedBytes": 214000,
          "startMs": 1092,
          "durationMs": 420
        },
        {
          "url": "https://player.dailymotion.com/poster/x8k2p1.jpg",
          "resourceType": "image",
          "transferredBytes": 22000,
          "decodedBytes": 22000,
          "unusedDecodedBytes": null,
          "startMs": 1520,
          "durationMs": 180
        },
        {
          "url": "https://sevre-et-loire.fr/assets/media/vignette-01.webp",
          "resourceType": "image",
          "transferredBytes": 2000,
          "decodedBytes": 2000,
          "unusedDecodedBytes": null,
          "startMs": 620,
          "durationMs": 120
        },
        {
          "url": "https://sevre-et-loire.fr/assets/media/vignette-02.webp",
          "resourceType": "image",
          "transferredBytes": 2137,
          "decodedBytes": 2137,
          "unusedDecodedBytes": null,
          "startMs": 642,
          "durationMs": 173
        },
        {
          "url": "https://sevre-et-loire.fr/assets/media/vignette-03.webp",
          "resourceType": "image",
          "transferredBytes": 2274,
          "decodedBytes": 2274,
          "unusedDecodedBytes": null,
          "startMs": 664,
          "durationMs": 226
        },
        {
          "url": "https://sevre-et-loire.fr/assets/media/vignette-04.webp",
          "resourceType": "image",
          "transferredBytes": 2411,
          "decodedBytes": 2411,
          "unusedDecodedBytes": null,
          "startMs": 686,
          "durationMs": 139
        },
        {
          "url": "https://sevre-et-loire.fr/assets/media/vignette-05.webp",
          "resourceType": "image",
          "transferredBytes": 2548,
          "decodedBytes": 2548,
          "unusedDecodedBytes": null,
          "startMs": 708,
          "durationMs": 192
        },
        {
          "url": "https://sevre-et-loire.fr/assets/media/vignette-06.webp",
          "resourceType": "image",
          "transferredBytes": 2685,
          "decodedBytes": 2685,
          "unusedDecodedBytes": null,
          "startMs": 730,
          "durationMs": 245
        },
        {
          "url": "https://sevre-et-loire.fr/assets/media/vignette-07.webp",
          "resourceType": "image",
          "transferredBytes": 2822,
          "decodedBytes": 2822,
          "unusedDecodedBytes": null,
          "startMs": 752,
          "durationMs": 158
        },
        {
          "url": "https://sevre-et-loire.fr/assets/media/vignette-08.webp",
          "resourceType": "image",
          "transferredBytes": 2959,
          "decodedBytes": 2959,
          "unusedDecodedBytes": null,
          "startMs": 774,
          "durationMs": 211
        },
        {
          "url": "https://sevre-et-loire.fr/assets/media/vignette-09.webp",
          "resourceType": "image",
          "transferredBytes": 3096,
          "decodedBytes": 3096,
          "unusedDecodedBytes": null,
          "startMs": 796,
          "durationMs": 124
        },
        {
          "url": "https://sevre-et-loire.fr/assets/media/vignette-10.webp",
          "resourceType": "image",
          "transferredBytes": 3233,
          "decodedBytes": 3233,
          "unusedDecodedBytes": null,
          "startMs": 818,
          "durationMs": 177
        },
        {
          "url": "https://sevre-et-loire.fr/assets/media/vignette-11.webp",
          "resourceType": "image",
          "transferredBytes": 3370,
          "decodedBytes": 3370,
          "unusedDecodedBytes": null,
          "startMs": 840,
          "durationMs": 230
        },
        {
          "url": "https://sevre-et-loire.fr/assets/media/vignette-12.webp",
          "resourceType": "image",
          "transferredBytes": 3507,
          "decodedBytes": 3507,
          "unusedDecodedBytes": null,
          "startMs": 862,
          "durationMs": 143
        },
        {
          "url": "https://sevre-et-loire.fr/assets/media/vignette-13.webp",
          "resourceType": "image",
          "transferredBytes": 3644,
          "decodedBytes": 3644,
          "unusedDecodedBytes": null,
          "startMs": 884,
          "durationMs": 196
        },
        {
          "url": "https://sevre-et-loire.fr/assets/media/vignette-14.webp",
          "resourceType": "image",
          "transferredBytes": 3781,
          "decodedBytes": 3781,
          "unusedDecodedBytes": null,
          "startMs": 906,
          "durationMs": 249
        },
        {
          "url": "https://sevre-et-loire.fr/assets/media/vignette-15.webp",
          "resourceType": "image",
          "transferredBytes": 2118,
          "decodedBytes": 2118,
          "unusedDecodedBytes": null,
          "startMs": 928,
          "durationMs": 162
        },
        {
          "url": "https://sevre-et-loire.fr/assets/media/vignette-16.webp",
          "resourceType": "image",
          "transferredBytes": 2255,
          "decodedBytes": 2255,
          "unusedDecodedBytes": null,
          "startMs": 950,
          "durationMs": 215
        },
        {
          "url": "https://sevre-et-loire.fr/assets/media/vignette-17.webp",
          "resourceType": "image",
          "transferredBytes": 2392,
          "decodedBytes": 2392,
          "unusedDecodedBytes": null,
          "startMs": 972,
          "durationMs": 128
        },
        {
          "url": "https://sevre-et-loire.fr/assets/media/vignette-18.webp",
          "resourceType": "image",
          "transferredBytes": 2529,
          "decodedBytes": 2529,
          "unusedDecodedBytes": null,
          "startMs": 994,
          "durationMs": 181
        },
        {
          "url": "https://sevre-et-loire.fr/assets/media/vignette-19.webp",
          "resourceType": "image",
          "transferredBytes": 2666,
          "decodedBytes": 2666,
          "unusedDecodedBytes": null,
          "startMs": 1016,
          "durationMs": 234
        },
        {
          "url": "https://sevre-et-loire.fr/assets/media/vignette-20.webp",
          "resourceType": "image",
          "transferredBytes": 2803,
          "decodedBytes": 2803,
          "unusedDecodedBytes": null,
          "startMs": 1038,
          "durationMs": 147
        },
        {
          "url": "https://sevre-et-loire.fr/assets/media/vignette-21.webp",
          "resourceType": "image",
          "transferredBytes": 2940,
          "decodedBytes": 2940,
          "unusedDecodedBytes": null,
          "startMs": 1060,
          "durationMs": 200
        },
        {
          "url": "https://sevre-et-loire.fr/assets/media/vignette-22.webp",
          "resourceType": "image",
          "transferredBytes": 3077,
          "decodedBytes": 3077,
          "unusedDecodedBytes": null,
          "startMs": 1082,
          "durationMs": 253
        },
        {
          "url": "https://sevre-et-loire.fr/assets/media/vignette-23.webp",
          "resourceType": "image",
          "transferredBytes": 3214,
          "decodedBytes": 3214,
          "unusedDecodedBytes": null,
          "startMs": 1104,
          "durationMs": 166
        },
        {
          "url": "https://sevre-et-loire.fr/assets/media/vignette-24.webp",
          "resourceType": "image",
          "transferredBytes": 3351,
          "decodedBytes": 3351,
          "unusedDecodedBytes": null,
          "startMs": 1126,
          "durationMs": 219
        },
        {
          "url": "https://sevre-et-loire.fr/assets/media/vignette-25.webp",
          "resourceType": "image",
          "transferredBytes": 3488,
          "decodedBytes": 3488,
          "unusedDecodedBytes": null,
          "startMs": 1148,
          "durationMs": 132
        },
        {
          "url": "https://sevre-et-loire.fr/assets/media/vignette-26.webp",
          "resourceType": "image",
          "transferredBytes": 3625,
          "decodedBytes": 3625,
          "unusedDecodedBytes": null,
          "startMs": 1170,
          "durationMs": 185
        },
        {
          "url": "https://sevre-et-loire.fr/assets/media/vignette-27.webp",
          "resourceType": "image",
          "transferredBytes": 3762,
          "decodedBytes": 3762,
          "unusedDecodedBytes": null,
          "startMs": 1192,
          "durationMs": 238
        },
        {
          "url": "https://sevre-et-loire.fr/assets/media/vignette-28.webp",
          "resourceType": "image",
          "transferredBytes": 2099,
          "decodedBytes": 2099,
          "unusedDecodedBytes": null,
          "startMs": 1214,
          "durationMs": 151
        },
        {
          "url": "https://sevre-et-loire.fr/assets/media/vignette-29.webp",
          "resourceType": "image",
          "transferredBytes": 2236,
          "decodedBytes": 2236,
          "unusedDecodedBytes": null,
          "startMs": 1236,
          "durationMs": 204
        },
        {
          "url": "https://sevre-et-loire.fr/assets/media/vignette-30.webp",
          "resourceType": "image",
          "transferredBytes": 2373,
          "decodedBytes": 2373,
          "unusedDecodedBytes": null,
          "startMs": 1258,
          "durationMs": 257
        },
        {
          "url": "https://sevre-et-loire.fr/assets/media/vignette-31.webp",
          "resourceType": "image",
          "transferredBytes": 2510,
          "decodedBytes": 2510,
          "unusedDecodedBytes": null,
          "startMs": 1280,
          "durationMs": 170
        },
        {
          "url": "https://sevre-et-loire.fr/assets/media/vignette-32.webp",
          "resourceType": "image",
          "transferredBytes": 2647,
          "decodedBytes": 2647,
          "unusedDecodedBytes": null,
          "startMs": 1302,
          "durationMs": 223
        },
        {
          "url": "https://sevre-et-loire.fr/assets/media/vignette-33.webp",
          "resourceType": "image",
          "transferredBytes": 2784,
          "decodedBytes": 2784,
          "unusedDecodedBytes": null,
          "startMs": 1324,
          "durationMs": 136
        },
        {
          "url": "https://sevre-et-loire.fr/assets/media/vignette-34.webp",
          "resourceType": "image",
          "transferredBytes": 2921,
          "decodedBytes": 2921,
          "unusedDecodedBytes": null,
          "startMs": 1346,
          "durationMs": 189
        },
        {
          "url": "https://sevre-et-loire.fr/assets/media/vignette-35.webp",
          "resourceType": "image",
          "transferredBytes": 3058,
          "decodedBytes": 3058,
          "unusedDecodedBytes": null,
          "startMs": 1368,
          "durationMs": 242
        },
        {
          "url": "https://sevre-et-loire.fr/assets/media/vignette-36.webp",
          "resourceType": "image",
          "transferredBytes": 3195,
          "decodedBytes": 3195,
          "unusedDecodedBytes": null,
          "startMs": 1390,
          "durationMs": 155
        },
        {
          "url": "https://sevre-et-loire.fr/assets/media/vignette-37.webp",
          "resourceType": "image",
          "transferredBytes": 3332,
          "decodedBytes": 3332,
          "unusedDecodedBytes": null,
          "startMs": 1412,
          "durationMs": 208
        },
        {
          "url": "https://sevre-et-loire.fr/assets/media/vignette-38.webp",
          "resourceType": "image",
          "transferredBytes": 3469,
          "decodedBytes": 3469,
          "unusedDecodedBytes": null,
          "startMs": 1434,
          "durationMs": 121
        },
        {
          "url": "https://sevre-et-loire.fr/assets/media/vignette-39.webp",
          "resourceType": "image",
          "transferredBytes": 3606,
          "decodedBytes": 3606,
          "unusedDecodedBytes": null,
          "startMs": 1456,
          "durationMs": 174
        },
        {
          "url": "https://sevre-et-loire.fr/assets/media/vignette-40.webp",
          "resourceType": "image",
          "transferredBytes": 3743,
          "decodedBytes": 3743,
          "unusedDecodedBytes": null,
          "startMs": 1478,
          "durationMs": 227
        },
        {
          "url": "https://sevre-et-loire.fr/assets/media/vignette-41.webp",
          "resourceType": "image",
          "transferredBytes": 2080,
          "decodedBytes": 2080,
          "unusedDecodedBytes": null,
          "startMs": 1500,
          "durationMs": 140
        },
        {
          "url": "https://sevre-et-loire.fr/assets/media/vignette-42.webp",
          "resourceType": "image",
          "transferredBytes": 2217,
          "decodedBytes": 2217,
          "unusedDecodedBytes": null,
          "startMs": 1522,
          "durationMs": 193
        },
        {
          "url": "https://sevre-et-loire.fr/assets/media/vignette-43.webp",
          "resourceType": "image",
          "transferredBytes": 2354,
          "decodedBytes": 2354,
          "unusedDecodedBytes": null,
          "startMs": 1544,
          "durationMs": 246
        },
        {
          "url": "https://sevre-et-loire.fr/assets/media/vignette-44.webp",
          "resourceType": "image",
          "transferredBytes": 2491,
          "decodedBytes": 2491,
          "unusedDecodedBytes": null,
          "startMs": 1566,
          "durationMs": 159
        },
        {
          "url": "https://sevre-et-loire.fr/assets/media/vignette-45.webp",
          "resourceType": "image",
          "transferredBytes": 2628,
          "decodedBytes": 2628,
          "unusedDecodedBytes": null,
          "startMs": 1588,
          "durationMs": 212
        },
        {
          "url": "https://sevre-et-loire.fr/assets/media/vignette-46.webp",
          "resourceType": "image",
          "transferredBytes": 2765,
          "decodedBytes": 2765,
          "unusedDecodedBytes": null,
          "startMs": 1610,
          "durationMs": 125
        },
        {
          "url": "https://sevre-et-loire.fr/assets/media/vignette-47.webp",
          "resourceType": "image",
          "transferredBytes": 2902,
          "decodedBytes": 2902,
          "unusedDecodedBytes": null,
          "startMs": 1632,
          "durationMs": 178
        },
        {
          "url": "https://sevre-et-loire.fr/assets/media/vignette-48.webp",
          "resourceType": "image",
          "transferredBytes": 3039,
          "decodedBytes": 3039,
          "unusedDecodedBytes": null,
          "startMs": 1654,
          "durationMs": 231
        },
        {
          "url": "https://sevre-et-loire.fr/assets/media/vignette-49.webp",
          "resourceType": "image",
          "transferredBytes": 3176,
          "decodedBytes": 3176,
          "unusedDecodedBytes": null,
          "startMs": 1676,
          "durationMs": 144
        },
        {
          "url": "https://sevre-et-loire.fr/assets/media/vignette-50.webp",
          "resourceType": "image",
          "transferredBytes": 3313,
          "decodedBytes": 3313,
          "unusedDecodedBytes": null,
          "startMs": 1698,
          "durationMs": 197
        },
        {
          "url": "https://sevre-et-loire.fr/assets/media/vignette-51.webp",
          "resourceType": "image",
          "transferredBytes": 3450,
          "decodedBytes": 3450,
          "unusedDecodedBytes": null,
          "startMs": 1720,
          "durationMs": 250
        },
        {
          "url": "https://sevre-et-loire.fr/assets/media/vignette-52.webp",
          "resourceType": "image",
          "transferredBytes": 3587,
          "decodedBytes": 3587,
          "unusedDecodedBytes": null,
          "startMs": 1742,
          "durationMs": 163
        },
        {
          "url": "https://sevre-et-loire.fr/assets/media/vignette-53.webp",
          "resourceType": "image",
          "transferredBytes": 3724,
          "decodedBytes": 3724,
          "unusedDecodedBytes": null,
          "startMs": 1764,
          "durationMs": 216
        },
        {
          "url": "https://sevre-et-loire.fr/assets/media/vignette-54.webp",
          "resourceType": "image",
          "transferredBytes": 2061,
          "decodedBytes": 2061,
          "unusedDecodedBytes": null,
          "startMs": 1786,
          "durationMs": 129
        },
        {
          "url": "https://sevre-et-loire.fr/assets/media/vignette-55.webp",
          "resourceType": "image",
          "transferredBytes": 2198,
          "decodedBytes": 2198,
          "unusedDecodedBytes": null,
          "startMs": 1808,
          "durationMs": 182
        },
        {
          "url": "https://sevre-et-loire.fr/assets/media/vignette-56.webp",
          "resourceType": "image",
          "transferredBytes": 2335,
          "decodedBytes": 2335,
          "unusedDecodedBytes": null,
          "startMs": 1830,
          "durationMs": 235
        },
        {
          "url": "https://sevre-et-loire.fr/assets/media/vignette-57.webp",
          "resourceType": "image",
          "transferredBytes": 2472,
          "decodedBytes": 2472,
          "unusedDecodedBytes": null,
          "startMs": 1852,
          "durationMs": 148
        },
        {
          "url": "https://sevre-et-loire.fr/assets/media/vignette-58.webp",
          "resourceType": "image",
          "transferredBytes": 2609,
          "decodedBytes": 2609,
          "unusedDecodedBytes": null,
          "startMs": 1874,
          "durationMs": 201
        },
        {
          "url": "https://sevre-et-loire.fr/assets/media/vignette-59.webp",
          "resourceType": "image",
          "transferredBytes": 2746,
          "decodedBytes": 2746,
          "unusedDecodedBytes": null,
          "startMs": 1896,
          "durationMs": 254
        },
        {
          "url": "https://sevre-et-loire.fr/assets/media/vignette-60.webp",
          "resourceType": "image",
          "transferredBytes": 2883,
          "decodedBytes": 2883,
          "unusedDecodedBytes": null,
          "startMs": 1918,
          "durationMs": 167
        },
        {
          "url": "https://sevre-et-loire.fr/assets/media/vignette-61.webp",
          "resourceType": "image",
          "transferredBytes": 3020,
          "decodedBytes": 3020,
          "unusedDecodedBytes": null,
          "startMs": 1940,
          "durationMs": 220
        },
        {
          "url": "https://sevre-et-loire.fr/assets/media/vignette-62.webp",
          "resourceType": "image",
          "transferredBytes": 3157,
          "decodedBytes": 3157,
          "unusedDecodedBytes": null,
          "startMs": 1962,
          "durationMs": 133
        },
        {
          "url": "https://sevre-et-loire.fr/assets/media/vignette-63.webp",
          "resourceType": "image",
          "transferredBytes": 3294,
          "decodedBytes": 3294,
          "unusedDecodedBytes": null,
          "startMs": 1984,
          "durationMs": 186
        },
        {
          "url": "https://sevre-et-loire.fr/assets/media/vignette-64.webp",
          "resourceType": "image",
          "transferredBytes": 3431,
          "decodedBytes": 3431,
          "unusedDecodedBytes": null,
          "startMs": 2006,
          "durationMs": 239
        },
        {
          "url": "https://sevre-et-loire.fr/assets/media/vignette-65.webp",
          "resourceType": "image",
          "transferredBytes": 3568,
          "decodedBytes": 3568,
          "unusedDecodedBytes": null,
          "startMs": 2028,
          "durationMs": 152
        },
        {
          "url": "https://sevre-et-loire.fr/assets/media/vignette-66.webp",
          "resourceType": "image",
          "transferredBytes": 3705,
          "decodedBytes": 3705,
          "unusedDecodedBytes": null,
          "startMs": 2050,
          "durationMs": 205
        },
        {
          "url": "https://sevre-et-loire.fr/assets/media/vignette-67.webp",
          "resourceType": "image",
          "transferredBytes": 2042,
          "decodedBytes": 2042,
          "unusedDecodedBytes": null,
          "startMs": 2072,
          "durationMs": 258
        },
        {
          "url": "https://sevre-et-loire.fr/assets/media/vignette-68.webp",
          "resourceType": "image",
          "transferredBytes": 2179,
          "decodedBytes": 2179,
          "unusedDecodedBytes": null,
          "startMs": 2094,
          "durationMs": 171
        },
        {
          "url": "https://sevre-et-loire.fr/assets/media/vignette-69.webp",
          "resourceType": "image",
          "transferredBytes": 2316,
          "decodedBytes": 2316,
          "unusedDecodedBytes": null,
          "startMs": 2116,
          "durationMs": 224
        },
        {
          "url": "https://sevre-et-loire.fr/assets/media/vignette-70.webp",
          "resourceType": "image",
          "transferredBytes": 2453,
          "decodedBytes": 2453,
          "unusedDecodedBytes": null,
          "startMs": 2138,
          "durationMs": 137
        },
        {
          "url": "https://sevre-et-loire.fr/assets/media/vignette-71.webp",
          "resourceType": "image",
          "transferredBytes": 9145,
          "decodedBytes": 9145,
          "unusedDecodedBytes": null,
          "startMs": 2160,
          "durationMs": 190
        }
      ],
      "requestCount": 84,
      "domNodeCountAtLoad": 2062,
      "domNodeCountAtNetworkIdle": 2140,
      "jsExecutionMs": 612
    }
  },
  {
    "id": "journey",
    "scenarioId": "journey-demande-acte",
    "label": "demande d'acte",
    "pass": "cold",
    "sampleCount": 5,
    "fingerprintStable": true,
    "metrics": [
      {
        "metricId": "transferred_bytes",
        "unit": "bytes",
        "median": 1258000,
        "mad": 12000,
        "min": 1234000,
        "max": 1282000,
        "sampleCount": 5,
        "runValues": [
          1247200,
          1282000,
          1258000,
          1234000,
          1270000
        ],
        "floor": {
          "status": "established",
          "metricId": "transferred_bytes",
          "unit": "bytes",
          "value": 14760,
          "sampleCount": 24,
          "scalingFactor": 1.2
        },
        "confidence": "high",
        "history": [
          {
            "median": 1236000,
            "low": 1216800,
            "high": 1255200,
            "mad": 9600
          },
          {
            "median": 1229000,
            "low": 1202600,
            "high": 1255400,
            "mad": 13200
          },
          {
            "median": 1241000,
            "low": 1219400,
            "high": 1262600,
            "mad": 10800
          },
          {
            "median": 1233000,
            "low": 1201800,
            "high": 1264200,
            "mad": 15600
          },
          {
            "median": 1246000,
            "low": 1222000,
            "high": 1270000,
            "mad": 12000
          },
          {
            "median": 1238000,
            "low": 1221200,
            "high": 1254800,
            "mad": 8400
          },
          {
            "median": 1252000,
            "low": 1223200,
            "high": 1280800,
            "mad": 14400
          },
          {
            "median": 1244000,
            "low": 1221200,
            "high": 1266800,
            "mad": 11400
          },
          {
            "median": 1237000,
            "low": 1211800,
            "high": 1262200,
            "mad": 12600
          },
          {
            "median": 1250000,
            "low": 1222400,
            "high": 1277600,
            "mad": 13800
          },
          {
            "median": 1243000,
            "low": 1223800,
            "high": 1262200,
            "mad": 9600
          },
          {
            "median": 1242000,
            "low": 1215600,
            "high": 1268400,
            "mad": 13200
          },
          {
            "median": 1238000,
            "low": 1216400,
            "high": 1259600,
            "mad": 10800
          },
          {
            "median": 1251000,
            "low": 1219800,
            "high": 1282200,
            "mad": 15600
          },
          {
            "median": 1247000,
            "low": 1223000,
            "high": 1271000,
            "mad": 12000
          },
          {
            "median": 1244000,
            "low": 1227200,
            "high": 1260800,
            "mad": 8400
          },
          {
            "median": 1258000,
            "low": 1229200,
            "high": 1286800,
            "mad": 14400
          },
          {
            "median": 1262000,
            "low": 1239200,
            "high": 1284800,
            "mad": 11400
          },
          {
            "median": 1255000,
            "low": 1229800,
            "high": 1280200,
            "mad": 12600
          },
          {
            "median": 1249000,
            "low": 1221400,
            "high": 1276600,
            "mad": 13800
          },
          {
            "median": 1421000,
            "low": 1401800,
            "high": 1440200,
            "mad": 9600
          },
          {
            "median": 1418000,
            "low": 1391600,
            "high": 1444400,
            "mad": 13200
          },
          {
            "median": 1424000,
            "low": 1402400,
            "high": 1445600,
            "mad": 10800
          },
          {
            "median": 1263000,
            "low": 1231800,
            "high": 1294200,
            "mad": 15600
          }
        ]
      },
      {
        "metricId": "request_count",
        "unit": "count",
        "median": 96,
        "mad": 2,
        "min": 93,
        "max": 99,
        "sampleCount": 5,
        "runValues": [
          95,
          99,
          96,
          93,
          98
        ],
        "floor": {
          "status": "established",
          "metricId": "request_count",
          "unit": "count",
          "value": 2.4,
          "sampleCount": 24,
          "scalingFactor": 1.2
        },
        "confidence": "high"
      },
      {
        "metricId": "dom_node_count",
        "unit": "count",
        "median": 4180,
        "mad": 160,
        "min": 3860,
        "max": 4500,
        "sampleCount": 5,
        "runValues": [
          4036,
          4500,
          4180,
          3860,
          4340
        ],
        "floor": {
          "status": "established",
          "metricId": "dom_node_count",
          "unit": "count",
          "value": 196.79999999999998,
          "sampleCount": 24,
          "scalingFactor": 1.2
        },
        "confidence": "high"
      },
      {
        "metricId": "third_party_bytes",
        "unit": "bytes",
        "median": 226000,
        "mad": 3000,
        "min": 220000,
        "max": 232000,
        "sampleCount": 5,
        "runValues": [
          229000,
          220000,
          226000,
          232000,
          223300
        ],
        "floor": {
          "status": "established",
          "metricId": "third_party_bytes",
          "unit": "bytes",
          "value": 3690,
          "sampleCount": 24,
          "scalingFactor": 1.2
        },
        "confidence": "high"
      },
      {
        "metricId": "third_party_share_pct",
        "unit": "pct",
        "median": 17.965023847376788,
        "mad": 0.3961050814237268,
        "min": 17.160686427457097,
        "max": 18.80064829821718,
        "sampleCount": 5,
        "runValues": [
          18.361128928800515,
          17.160686427457097,
          17.965023847376788,
          18.80064829821718,
          17.58267716535433
        ],
        "floor": {
          "status": "established",
          "metricId": "third_party_share_pct",
          "unit": "pct",
          "value": 0.4814881464749618,
          "sampleCount": 24,
          "scalingFactor": 1.2
        },
        "confidence": "high"
      }
    ]
  },
  {
    "id": "scan",
    "scenarioId": "scan",
    "label": "bibliotheques-selo.fr",
    "pass": "cold",
    "sampleCount": 1,
    "fingerprintStable": true,
    "metrics": [
      {
        "metricId": "transferred_bytes",
        "unit": "bytes",
        "median": 980000,
        "mad": 0,
        "min": 980000,
        "max": 980000,
        "sampleCount": 1,
        "runValues": [
          980000
        ],
        "floor": {
          "status": "insufficient-history",
          "metricId": "transferred_bytes",
          "sampleCount": 0,
          "requiredCount": 20
        },
        "confidence": "low"
      },
      {
        "metricId": "request_count",
        "unit": "count",
        "median": 61,
        "mad": 0,
        "min": 61,
        "max": 61,
        "sampleCount": 1,
        "runValues": [
          61
        ],
        "floor": {
          "status": "insufficient-history",
          "metricId": "request_count",
          "sampleCount": 0,
          "requiredCount": 20
        },
        "confidence": "low"
      },
      {
        "metricId": "dom_node_count",
        "unit": "count",
        "median": 1830,
        "mad": 0,
        "min": 1830,
        "max": 1830,
        "sampleCount": 1,
        "runValues": [
          1830
        ],
        "floor": {
          "status": "insufficient-history",
          "metricId": "dom_node_count",
          "sampleCount": 0,
          "requiredCount": 20
        },
        "confidence": "low"
      }
    ]
  }
] as ReadonlyArray<{
    id: string;
    scenarioId: string;
    label: string;
    pass: 'cold' | 'warm';
    sampleCount: number;
    fingerprintStable: boolean;
    metrics: readonly CanonMetric[];
    /**
     * the median run's capture, where a surface renders its inventory. absent
     * on an aggregate over several pages, which has no single capture, and on
     * one nothing shows an inventory for.
     */
    capture?: RawCapture;
  }>,
} as const;

export type { CanonHistoryPoint, CanonMetric };
