// generated by scripts/generate-measurement-canon.ts. do not edit by hand.
// run `pnpm gen:measurement-canon` to rebuild; measurement-canon.test.ts
// fails if this file and the generator ever disagree.
//
// every median, dispersion, noise floor and confidence grade below was computed
// by @balise/measure-core from the runs recorded beside it. no statistic here
// was chosen: the mad is the mad of those run values, the floor is the scaled
// median of the historical mads, and the grade is what gradeConfidence
// returned for that dispersion at that sample count.

import type { CanonHistoryPoint, CanonMetric } from './measurement-types';

export const measurementCanon = {
  scalingFactor: 1.2,
  minHistory: 20,
  runOffsets: [-0.45,1,0,-1,0.5],
  scenarios: [
  {
    "id": "service",
    "label": "médiane du service",
    "pass": "cold",
    "historyCount": 24,
    "aggregationIds": [
      "service"
    ]
  },
  {
    "id": "route-acte-naissance",
    "label": "/demarches/acte-naissance",
    "pass": "cold",
    "historyCount": 24,
    "aggregationIds": [
      "baseline",
      "candidate"
    ]
  },
  {
    "id": "journey-demande-acte",
    "label": "journey:demande-acte",
    "pass": "cold",
    "historyCount": 24,
    "aggregationIds": [
      "journey"
    ]
  },
  {
    "id": "scan",
    "label": "bibliotheques-selo.fr",
    "pass": "cold",
    "historyCount": 0,
    "aggregationIds": [
      "scan"
    ]
  }
] as ReadonlyArray<{
    id: string;
    label: string;
    pass: 'cold' | 'warm';
    historyCount: number;
    /** the aggregations this scenario publishes, all read against its one floor. */
    aggregationIds: readonly string[];
  }>,
  aggregations: [
  {
    "id": "service",
    "scenarioId": "service",
    "label": "médiane du service",
    "pass": "cold",
    "sampleCount": 5,
    "fingerprintStable": true,
    "metrics": [
      {
        "metricId": "transferred_bytes",
        "unit": "bytes",
        "median": 1258000,
        "mad": 6000,
        "min": 1246000,
        "max": 1270000,
        "sampleCount": 5,
        "runValues": [
          1252600,
          1270000,
          1258000,
          1246000,
          1264000
        ],
        "floor": {
          "status": "established",
          "metricId": "transferred_bytes",
          "unit": "bytes",
          "value": 7380,
          "sampleCount": 24,
          "scalingFactor": 1.2
        },
        "confidence": "high"
      },
      {
        "metricId": "request_count",
        "unit": "count",
        "median": 82,
        "mad": 1,
        "min": 80,
        "max": 84,
        "sampleCount": 5,
        "runValues": [
          81,
          84,
          82,
          80,
          83
        ],
        "floor": {
          "status": "established",
          "metricId": "request_count",
          "unit": "count",
          "value": 1.2,
          "sampleCount": 24,
          "scalingFactor": 1.2
        },
        "confidence": "high"
      },
      {
        "metricId": "dom_node_count",
        "unit": "count",
        "median": 2140,
        "mad": 130,
        "min": 1880,
        "max": 2400,
        "sampleCount": 5,
        "runValues": [
          2023,
          2400,
          2140,
          1880,
          2270
        ],
        "floor": {
          "status": "established",
          "metricId": "dom_node_count",
          "unit": "count",
          "value": 160.2,
          "sampleCount": 24,
          "scalingFactor": 1.2
        },
        "confidence": "medium"
      },
      {
        "metricId": "js_execution_ms",
        "unit": "ms",
        "median": 588,
        "mad": 17,
        "min": 554,
        "max": 622,
        "sampleCount": 5,
        "runValues": [
          572.7,
          622,
          588,
          554,
          605
        ],
        "floor": {
          "status": "established",
          "metricId": "js_execution_ms",
          "unit": "ms",
          "value": 20.910000000000014,
          "sampleCount": 24,
          "scalingFactor": 1.2
        },
        "confidence": "high"
      },
      {
        "metricId": "third_party_bytes",
        "unit": "bytes",
        "median": 478000,
        "mad": 4500,
        "min": 469000,
        "max": 487000,
        "sampleCount": 5,
        "runValues": [
          478000,
          469000,
          482500,
          473950,
          487000
        ],
        "floor": {
          "status": "established",
          "metricId": "third_party_bytes",
          "unit": "bytes",
          "value": 5535,
          "sampleCount": 24,
          "scalingFactor": 1.2
        },
        "confidence": "high"
      },
      {
        "metricId": "third_party_share_pct",
        "unit": "pct",
        "median": 38.16062589813188,
        "mad": 0.19390510345794354,
        "min": 36.92913385826772,
        "max": 38.528481012658226,
        "sampleCount": 5,
        "runValues": [
          38.16062589813188,
          36.92913385826772,
          38.35453100158983,
          38.03772070626003,
          38.528481012658226
        ],
        "floor": {
          "status": "established",
          "metricId": "third_party_share_pct",
          "unit": "pct",
          "value": 0.2384810280667281,
          "sampleCount": 24,
          "scalingFactor": 1.2
        },
        "confidence": "high"
      }
    ]
  },
  {
    "id": "baseline",
    "scenarioId": "route-acte-naissance",
    "label": "#4790 · main",
    "pass": "cold",
    "sampleCount": 5,
    "fingerprintStable": true,
    "metrics": [
      {
        "metricId": "transferred_bytes",
        "unit": "bytes",
        "median": 1114000,
        "mad": 6000,
        "min": 1102000,
        "max": 1126000,
        "sampleCount": 5,
        "runValues": [
          1108600,
          1126000,
          1114000,
          1102000,
          1120000
        ],
        "floor": {
          "status": "established",
          "metricId": "transferred_bytes",
          "unit": "bytes",
          "value": 7380,
          "sampleCount": 24,
          "scalingFactor": 1.2
        },
        "confidence": "high"
      },
      {
        "metricId": "request_count",
        "unit": "count",
        "median": 82,
        "mad": 1,
        "min": 80,
        "max": 84,
        "sampleCount": 5,
        "runValues": [
          81,
          84,
          82,
          80,
          83
        ],
        "floor": {
          "status": "established",
          "metricId": "request_count",
          "unit": "count",
          "value": 1.2,
          "sampleCount": 24,
          "scalingFactor": 1.2
        },
        "confidence": "high"
      },
      {
        "metricId": "dom_node_count",
        "unit": "count",
        "median": 2118,
        "mad": 150,
        "min": 1818,
        "max": 2418,
        "sampleCount": 5,
        "runValues": [
          1983,
          2418,
          2118,
          1818,
          2268
        ],
        "floor": {
          "status": "established",
          "metricId": "dom_node_count",
          "unit": "count",
          "value": 184.79999999999998,
          "sampleCount": 24,
          "scalingFactor": 1.2
        },
        "confidence": "medium"
      },
      {
        "metricId": "js_execution_ms",
        "unit": "ms",
        "median": 548,
        "mad": 12,
        "min": 524,
        "max": 572,
        "sampleCount": 5,
        "runValues": [
          537.2,
          572,
          548,
          524,
          560
        ],
        "floor": {
          "status": "established",
          "metricId": "js_execution_ms",
          "unit": "ms",
          "value": 14.760000000000012,
          "sampleCount": 24,
          "scalingFactor": 1.2
        },
        "confidence": "high"
      },
      {
        "metricId": "third_party_bytes",
        "unit": "bytes",
        "median": 340000,
        "mad": 3500,
        "min": 333000,
        "max": 347000,
        "sampleCount": 5,
        "runValues": [
          340000,
          333000,
          343500,
          336850,
          347000
        ],
        "floor": {
          "status": "established",
          "metricId": "third_party_bytes",
          "unit": "bytes",
          "value": 4305,
          "sampleCount": 24,
          "scalingFactor": 1.2
        },
        "confidence": "high"
      },
      {
        "metricId": "third_party_share_pct",
        "unit": "pct",
        "median": 30.669312646581275,
        "mad": 0.16551679686576293,
        "min": 29.573712255772644,
        "max": 30.982142857142858,
        "sampleCount": 5,
        "runValues": [
          30.669312646581275,
          29.573712255772644,
          30.83482944344704,
          30.567150635208712,
          30.982142857142858
        ],
        "floor": {
          "status": "established",
          "metricId": "third_party_share_pct",
          "unit": "pct",
          "value": 0.20356284370734343,
          "sampleCount": 24,
          "scalingFactor": 1.2
        },
        "confidence": "high"
      }
    ]
  },
  {
    "id": "candidate",
    "scenarioId": "route-acte-naissance",
    "label": "#4812 · pr/412",
    "pass": "cold",
    "sampleCount": 5,
    "fingerprintStable": true,
    "metrics": [
      {
        "metricId": "transferred_bytes",
        "unit": "bytes",
        "median": 1298000,
        "mad": 9000,
        "min": 1280000,
        "max": 1316000,
        "sampleCount": 5,
        "runValues": [
          1289900,
          1316000,
          1298000,
          1280000,
          1307000
        ],
        "floor": {
          "status": "established",
          "metricId": "transferred_bytes",
          "unit": "bytes",
          "value": 7380,
          "sampleCount": 24,
          "scalingFactor": 1.2
        },
        "confidence": "high"
      },
      {
        "metricId": "request_count",
        "unit": "count",
        "median": 84,
        "mad": 1,
        "min": 82,
        "max": 86,
        "sampleCount": 5,
        "runValues": [
          83,
          86,
          84,
          82,
          85
        ],
        "floor": {
          "status": "established",
          "metricId": "request_count",
          "unit": "count",
          "value": 1.2,
          "sampleCount": 24,
          "scalingFactor": 1.2
        },
        "confidence": "high"
      },
      {
        "metricId": "dom_node_count",
        "unit": "count",
        "median": 2140,
        "mad": 160,
        "min": 1820,
        "max": 2460,
        "sampleCount": 5,
        "runValues": [
          1996,
          2460,
          2140,
          1820,
          2300
        ],
        "floor": {
          "status": "established",
          "metricId": "dom_node_count",
          "unit": "count",
          "value": 184.79999999999998,
          "sampleCount": 24,
          "scalingFactor": 1.2
        },
        "confidence": "medium"
      },
      {
        "metricId": "js_execution_ms",
        "unit": "ms",
        "median": 612,
        "mad": 15,
        "min": 582,
        "max": 642,
        "sampleCount": 5,
        "runValues": [
          598.5,
          642,
          612,
          582,
          627
        ],
        "floor": {
          "status": "established",
          "metricId": "js_execution_ms",
          "unit": "ms",
          "value": 14.760000000000012,
          "sampleCount": 24,
          "scalingFactor": 1.2
        },
        "confidence": "high"
      },
      {
        "metricId": "third_party_bytes",
        "unit": "bytes",
        "median": 366000,
        "mad": 4000,
        "min": 358000,
        "max": 374000,
        "sampleCount": 5,
        "runValues": [
          366000,
          358000,
          370000,
          362400,
          374000
        ],
        "floor": {
          "status": "established",
          "metricId": "third_party_bytes",
          "unit": "bytes",
          "value": 4305,
          "sampleCount": 24,
          "scalingFactor": 1.2
        },
        "confidence": "high"
      },
      {
        "metricId": "third_party_share_pct",
        "unit": "pct",
        "median": 28.37429258082022,
        "mad": 0.13110033135235,
        "min": 27.203647416413375,
        "max": 28.61514919663351,
        "sampleCount": 5,
        "runValues": [
          28.37429258082022,
          27.203647416413375,
          28.50539291217257,
          28.3125,
          28.61514919663351
        ],
        "floor": {
          "status": "established",
          "metricId": "third_party_share_pct",
          "unit": "pct",
          "value": 0.20356284370734343,
          "sampleCount": 24,
          "scalingFactor": 1.2
        },
        "confidence": "high"
      }
    ]
  },
  {
    "id": "journey",
    "scenarioId": "journey-demande-acte",
    "label": "demande d'acte",
    "pass": "cold",
    "sampleCount": 5,
    "fingerprintStable": true,
    "metrics": [
      {
        "metricId": "transferred_bytes",
        "unit": "bytes",
        "median": 1258000,
        "mad": 12000,
        "min": 1234000,
        "max": 1282000,
        "sampleCount": 5,
        "runValues": [
          1247200,
          1282000,
          1258000,
          1234000,
          1270000
        ],
        "floor": {
          "status": "established",
          "metricId": "transferred_bytes",
          "unit": "bytes",
          "value": 14760,
          "sampleCount": 24,
          "scalingFactor": 1.2
        },
        "confidence": "high",
        "history": [
          {
            "median": 1236000,
            "low": 1216800,
            "high": 1255200,
            "mad": 9600
          },
          {
            "median": 1229000,
            "low": 1202600,
            "high": 1255400,
            "mad": 13200
          },
          {
            "median": 1241000,
            "low": 1219400,
            "high": 1262600,
            "mad": 10800
          },
          {
            "median": 1233000,
            "low": 1201800,
            "high": 1264200,
            "mad": 15600
          },
          {
            "median": 1246000,
            "low": 1222000,
            "high": 1270000,
            "mad": 12000
          },
          {
            "median": 1238000,
            "low": 1221200,
            "high": 1254800,
            "mad": 8400
          },
          {
            "median": 1252000,
            "low": 1223200,
            "high": 1280800,
            "mad": 14400
          },
          {
            "median": 1244000,
            "low": 1221200,
            "high": 1266800,
            "mad": 11400
          },
          {
            "median": 1237000,
            "low": 1211800,
            "high": 1262200,
            "mad": 12600
          },
          {
            "median": 1250000,
            "low": 1222400,
            "high": 1277600,
            "mad": 13800
          },
          {
            "median": 1243000,
            "low": 1223800,
            "high": 1262200,
            "mad": 9600
          },
          {
            "median": 1242000,
            "low": 1215600,
            "high": 1268400,
            "mad": 13200
          },
          {
            "median": 1238000,
            "low": 1216400,
            "high": 1259600,
            "mad": 10800
          },
          {
            "median": 1251000,
            "low": 1219800,
            "high": 1282200,
            "mad": 15600
          },
          {
            "median": 1247000,
            "low": 1223000,
            "high": 1271000,
            "mad": 12000
          },
          {
            "median": 1244000,
            "low": 1227200,
            "high": 1260800,
            "mad": 8400
          },
          {
            "median": 1258000,
            "low": 1229200,
            "high": 1286800,
            "mad": 14400
          },
          {
            "median": 1262000,
            "low": 1239200,
            "high": 1284800,
            "mad": 11400
          },
          {
            "median": 1255000,
            "low": 1229800,
            "high": 1280200,
            "mad": 12600
          },
          {
            "median": 1249000,
            "low": 1221400,
            "high": 1276600,
            "mad": 13800
          },
          {
            "median": 1421000,
            "low": 1401800,
            "high": 1440200,
            "mad": 9600
          },
          {
            "median": 1418000,
            "low": 1391600,
            "high": 1444400,
            "mad": 13200
          },
          {
            "median": 1424000,
            "low": 1402400,
            "high": 1445600,
            "mad": 10800
          },
          {
            "median": 1263000,
            "low": 1231800,
            "high": 1294200,
            "mad": 15600
          }
        ]
      },
      {
        "metricId": "request_count",
        "unit": "count",
        "median": 96,
        "mad": 2,
        "min": 93,
        "max": 99,
        "sampleCount": 5,
        "runValues": [
          95,
          99,
          96,
          93,
          98
        ],
        "floor": {
          "status": "established",
          "metricId": "request_count",
          "unit": "count",
          "value": 2.4,
          "sampleCount": 24,
          "scalingFactor": 1.2
        },
        "confidence": "high"
      },
      {
        "metricId": "dom_node_count",
        "unit": "count",
        "median": 4180,
        "mad": 160,
        "min": 3860,
        "max": 4500,
        "sampleCount": 5,
        "runValues": [
          4036,
          4500,
          4180,
          3860,
          4340
        ],
        "floor": {
          "status": "established",
          "metricId": "dom_node_count",
          "unit": "count",
          "value": 196.79999999999998,
          "sampleCount": 24,
          "scalingFactor": 1.2
        },
        "confidence": "high"
      },
      {
        "metricId": "third_party_bytes",
        "unit": "bytes",
        "median": 226000,
        "mad": 3000,
        "min": 220000,
        "max": 232000,
        "sampleCount": 5,
        "runValues": [
          226000,
          220000,
          229000,
          223300,
          232000
        ],
        "floor": {
          "status": "established",
          "metricId": "third_party_bytes",
          "unit": "bytes",
          "value": 3690,
          "sampleCount": 24,
          "scalingFactor": 1.2
        },
        "confidence": "high"
      },
      {
        "metricId": "third_party_share_pct",
        "unit": "pct",
        "median": 18.120590121872997,
        "mad": 0.08290749338932457,
        "min": 17.160686427457097,
        "max": 18.26771653543307,
        "sampleCount": 5,
        "runValues": [
          18.120590121872997,
          17.160686427457097,
          18.20349761526232,
          18.095623987034035,
          18.26771653543307
        ],
        "floor": {
          "status": "established",
          "metricId": "third_party_share_pct",
          "unit": "pct",
          "value": 0.10071221947615569,
          "sampleCount": 24,
          "scalingFactor": 1.2
        },
        "confidence": "high"
      }
    ]
  },
  {
    "id": "scan",
    "scenarioId": "scan",
    "label": "bibliotheques-selo.fr",
    "pass": "cold",
    "sampleCount": 1,
    "fingerprintStable": true,
    "metrics": [
      {
        "metricId": "transferred_bytes",
        "unit": "bytes",
        "median": 980000,
        "mad": 0,
        "min": 980000,
        "max": 980000,
        "sampleCount": 1,
        "runValues": [
          980000
        ],
        "floor": {
          "status": "insufficient-history",
          "metricId": "transferred_bytes",
          "sampleCount": 0,
          "requiredCount": 20
        },
        "confidence": "low"
      },
      {
        "metricId": "request_count",
        "unit": "count",
        "median": 61,
        "mad": 0,
        "min": 61,
        "max": 61,
        "sampleCount": 1,
        "runValues": [
          61
        ],
        "floor": {
          "status": "insufficient-history",
          "metricId": "request_count",
          "sampleCount": 0,
          "requiredCount": 20
        },
        "confidence": "low"
      },
      {
        "metricId": "dom_node_count",
        "unit": "count",
        "median": 1830,
        "mad": 0,
        "min": 1830,
        "max": 1830,
        "sampleCount": 1,
        "runValues": [
          1830
        ],
        "floor": {
          "status": "insufficient-history",
          "metricId": "dom_node_count",
          "sampleCount": 0,
          "requiredCount": 20
        },
        "confidence": "low"
      }
    ]
  }
] as ReadonlyArray<{
    id: string;
    scenarioId: string;
    label: string;
    pass: 'cold' | 'warm';
    sampleCount: number;
    fingerprintStable: boolean;
    metrics: readonly CanonMetric[];
  }>,
} as const;

export type { CanonHistoryPoint, CanonMetric };
