"""writes the typed pack module and its yaml twin from the extracted source.

the tier of each criterion is a proposal: it is what this measurement stack
can actually answer today, not a decision. the pack ships with
tiersSignedOff: false, and the engine answers nothing automatically until
that is reviewed and flipped.
"""

import json
from pathlib import Path

HERE = Path(__file__).parent
SOURCE = json.load(open(HERE / "rgesn-2024-v2.source.json", encoding="utf-8"))

FAMILY_IDS = {
    "1": "strategie",
    "2": "specifications",
    "3": "architecture",
    "4": "ux-ui",
    "5": "contenus",
    "6": "frontend",
    "7": "backend",
    "8": "hebergement",
    "9": "algorithmie",
}

PRIORITY_IDS = {"Prioritaire": "prioritaire", "Recommandé": "recommande", "Modéré": "modere"}

# proposed tiers. automated only where the current metric set answers the
# question outright; assisted where a capture produces evidence a person then
# confirms; declarative for everything organisational. deliberately
# under-claimed: inflating the automated count is how this collapses in an
# audit.
AUTOMATED = {"4.1", "5.1", "5.2", "6.1", "6.2", "6.3", "6.4", "6.5", "8.6"}
ASSISTED = {
    "2.2", "2.3", "2.4", "2.5",
    "4.2", "4.4", "4.5", "4.9", "4.10", "4.11", "4.12",
    "5.3", "5.4", "5.5", "5.6", "5.7",
    "6.6", "6.7",
    "7.1", "7.3",
    "8.1", "8.5",
}

# the evaluation rules the engine can run today, for the automated criteria
# whose question maps onto a metric we extract. the thresholds are ours, not
# the referential's: it sets no numbers.
EVALUATIONS = {
    "6.1": ("request_count", "lte", 90),
}


def tier_of(number):
    if number in AUTOMATED:
        return "automated"
    if number in ASSISTED:
        return "assisted"
    return "declarative"


def sort_key(number):
    major, minor = number.split(".")
    return int(major), int(minor)


def ts_string(value):
    return json.dumps(value, ensure_ascii=False)


def main():
    numbers = sorted(SOURCE["criteria"], key=sort_key)

    families = [
        {"id": FAMILY_IDS[key], "labelFr": label}
        for key, label in sorted(SOURCE["families"].items())
    ]

    criteria = []
    for number in numbers:
        entry = SOURCE["criteria"][number]
        criterion = {
            "id": number,
            "family": FAMILY_IDS[number.split(".")[0]],
            "tier": tier_of(number),
            "statementFr": entry["statement"],
            "evidenceRequired": [],
        }
        if entry["priority"]:
            criterion["priority"] = PRIORITY_IDS[entry["priority"]]
        if number in EVALUATIONS:
            metric, operator, value = EVALUATIONS[number]
            criterion["evaluation"] = {
                "type": "metric_threshold",
                "metric": metric,
                "operator": operator,
                "value": value,
            }
        if criterion["tier"] == "declarative":
            criterion["evidenceRequired"] = [
                {"kind": "attestation", "labelFr": "Responsable désigné"}
            ]
        criteria.append(criterion)

    lines = [
        "// generated by scripts/generate-pack.py from the official evaluation",
        "// spreadsheet. do not edit by hand: statementFr is the referential's own",
        "// text and must stay verbatim.",
        "",
        "import type { RulePack } from '@balise/schemas';",
        "",
        "export const rgesn2024v2: RulePack = {",
        "  id: 'rgesn',",
        "  version: '2024.2',",
        "  locale: 'fr',",
        "  source:",
        "    'https://ecoresponsable.numerique.gouv.fr/publications/referentiel-general-ecoconception/',",
        "  // the tiers below are proposed, not accepted. see the package readme.",
        "  tiersSignedOff: false,",
        "  families: [",
    ]
    for family in families:
        lines.append(
            f"    {{ id: {ts_string(family['id'])}, labelFr: {ts_string(family['labelFr'])} }},"
        )
    lines += ["  ],", "  criteria: ["]

    for criterion in criteria:
        lines.append("    {")
        lines.append(f"      id: {ts_string(criterion['id'])} as RulePack['criteria'][number]['id'],")
        lines.append(f"      family: {ts_string(criterion['family'])},")
        lines.append(f"      tier: {ts_string(criterion['tier'])},")
        if "priority" in criterion:
            lines.append(f"      priority: {ts_string(criterion['priority'])},")
        lines.append(f"      statementFr: {ts_string(criterion['statementFr'])},")
        if "evaluation" in criterion:
            ev = criterion["evaluation"]
            lines.append(
                "      evaluation: { type: 'metric_threshold', metric: "
                f"{ts_string(ev['metric'])}, operator: {ts_string(ev['operator'])}, value: {ev['value']} }},"
            )
        if criterion["evidenceRequired"]:
            items = ", ".join(
                f"{{ kind: {ts_string(item['kind'])}, labelFr: {ts_string(item['labelFr'])} }}"
                for item in criterion["evidenceRequired"]
            )
            lines.append(f"      evidenceRequired: [{items}],")
        else:
            lines.append("      evidenceRequired: [],")
        lines.append("    },")

    lines += ["  ],", "};", ""]
    (HERE.parent / "src" / "rgesn-2024-v2.ts").write_text("\n".join(lines), encoding="utf-8")

    # the yaml twin, for auditors reading the pack rather than importing it
    yaml = [
        "# generated from src/rgesn-2024-v2.ts. the typescript module is the one",
        "# the engine loads; this is the readable copy.",
        "pack:",
        "  id: rgesn",
        '  version: "2024.2"',
        "  locale: fr",
        "  source: https://ecoresponsable.numerique.gouv.fr/publications/referentiel-general-ecoconception/",
        "  tiers_signed_off: false",
        "  families:",
    ]
    for family in families:
        yaml.append(f"    - id: {family['id']}")
        yaml.append(f'      label_fr: "{family["labelFr"]}"')
    yaml.append("")
    yaml.append("criteria:")
    for criterion in criteria:
        yaml.append(f'  - id: "{criterion["id"]}"')
        yaml.append(f"    family: {criterion['family']}")
        yaml.append(f"    tier: {criterion['tier']}")
        if "priority" in criterion:
            yaml.append(f"    priority: {criterion['priority']}")
        statement = criterion["statementFr"].replace('"', '\\"')
        yaml.append(f'    statement_fr: "{statement}"')
        if "evaluation" in criterion:
            ev = criterion["evaluation"]
            yaml.append("    evaluation:")
            yaml.append("      type: metric_threshold")
            yaml.append(f"      metric: {ev['metric']}")
            yaml.append(f"      operator: {ev['operator']}")
            yaml.append(f"      value: {ev['value']}")
        if criterion["evidenceRequired"]:
            yaml.append("    evidence_required:")
            for item in criterion["evidenceRequired"]:
                yaml.append(f"      - kind: {item['kind']}")
                yaml.append(f'        label_fr: "{item["labelFr"]}"')
    yaml.append("")
    (HERE.parent / "packs" / "rgesn-2024-v2.yaml").write_text("\n".join(yaml), encoding="utf-8")

    counts = {tier: sum(1 for c in criteria if c["tier"] == tier) for tier in ("automated", "assisted", "declarative")}
    print(f"{len(criteria)} criteria: {counts}")


if __name__ == "__main__":
    main()
